{"abstract":[{"type":"text","text":"The version of the adapter."},{"text":" ","type":"text"},{"type":"text","text":"It should have either 5 or 6 digits separated by periods, where the first digit is Chartboost Mediation SDK’s major version, the"},{"type":"text","text":" "},{"type":"text","text":"last digit is the adapter’s build version, and intermediate digits are the partner SDK’s version."},{"type":"text","text":" "},{"type":"text","text":"Format: "},{"type":"codeVoice","code":"<Chartboost Mediation major version>.<Partner major version>.<Partner minor version>.<Partner patch version>. <Partner build version>.<Adapter build version>"},{"type":"text","text":" where "},{"type":"codeVoice","code":".<Partner build version>"},{"text":" is optional.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/adapterVersion","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/adapterversion"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/adapterversion"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adapterVersion"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"adapterVersion","required":true,"roleHeading":"Type Property","modules":[{"name":"ChartboostMediationSDK"}],"externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMPartnerAdapterConfiguration(cpy)adapterVersion","navigatorTitle":[{"kind":"identifier","text":"adapterVersion"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"adapterVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration"]]},"references":{"https://developers.chartboost.com/docs/mediation-ios-get-started":{"type":"link","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration":{"abstract":[{"text":"A configuration type that contains adapter and partner info.","type":"text"},{"text":" ","type":"text"},{"text":"It may also be used to expose custom partner SDK options to the publisher.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","title":"PartnerAdapterConfiguration","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapterConfiguration"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration","type":"topic","navigatorTitle":[{"text":"PartnerAdapterConfiguration","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration/adapterVersion":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/adapterVersion","abstract":[{"type":"text","text":"The version of the adapter."},{"text":" ","type":"text"},{"text":"It should have either 5 or 6 digits separated by periods, where the first digit is Chartboost Mediation SDK’s major version, the","type":"text"},{"type":"text","text":" "},{"text":"last digit is the adapter’s build version, and intermediate digits are the partner SDK’s version.","type":"text"},{"type":"text","text":" "},{"text":"Format: ","type":"text"},{"code":"<Chartboost Mediation major version>.<Partner major version>.<Partner minor version>.<Partner patch version>. <Partner build version>.<Adapter build version>","type":"codeVoice"},{"type":"text","text":" where "},{"code":".<Partner build version>","type":"codeVoice"},{"type":"text","text":" is optional."}],"url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/adapterversion","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"adapterVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"adapterVersion"}],"role":"symbol","title":"adapterVersion","type":"topic","kind":"symbol","required":true}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"adapterVersion"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"adapterVersion","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"adapterVersion","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"CBMPartnerAdapterConfiguration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/fragments","value":[{"text":"CBMPartnerAdapterConfiguration","kind":"identifier"}]},{"value":"adapterVersion","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1adapterVersion\/title","op":"replace"},{"value":[{"text":"adapterVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1adapterVersion\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}