{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerID"},"abstract":[{"text":"The partner’s unique identifier.","type":"text"}],"metadata":{"title":"partnerID","symbolKind":"property","role":"symbol","required":true,"externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMPartnerAdapterConfiguration(cpy)partnerID","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"partnerID","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa","text":"PartnerID"}],"modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"text":"partnerID","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/partnerid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/partnerid"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"partnerID","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID","kind":"typeIdentifier","text":"PartnerID","preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration":{"abstract":[{"text":"A configuration type that contains adapter and partner info.","type":"text"},{"text":" ","type":"text"},{"text":"It may also be used to expose custom partner SDK options to the publisher.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","title":"PartnerAdapterConfiguration","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapterConfiguration"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration","type":"topic","navigatorTitle":[{"text":"PartnerAdapterConfiguration","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerID":{"role":"symbol","abstract":[{"type":"text","text":"A "},{"code":"String","type":"codeVoice"},{"text":" that identifies a partner.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/partnerid","type":"topic","title":"PartnerID","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"PartnerID","kind":"identifier"}],"navigatorTitle":[{"text":"PartnerID","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","type":"link","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"title":"Chartboost Developers","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration/partnerID":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerID","abstract":[{"type":"text","text":"The partner’s unique identifier."}],"role":"symbol","title":"partnerID","url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/partnerid","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"partnerID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa","text":"PartnerID","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"partnerID","kind":"identifier"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"partnerID"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"partnerID","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"partnerID"}],"languages":["occ"]}]}},{"value":"CBMPartnerAdapterConfiguration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/title"},{"value":[{"kind":"identifier","text":"CBMPartnerAdapterConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/fragments"},{"op":"replace","value":"partnerID","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1partnerID\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1partnerID\/fragments","op":"replace","value":[{"text":"partnerID","kind":"identifier"}]}]}]}