{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/banneradview\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/banneradview\/init()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView\/init()","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"init","role":"symbol","title":"init()","modules":[{"name":"ChartboostMediationSDK"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView(im)init","roleHeading":"Initializer"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"kind":"symbol","type":"topic","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"title":"BannerAdView","type":"topic","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/banneradview","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","navigatorTitle":[{"kind":"identifier","text":"BannerAdView"}],"abstract":[{"type":"text","text":"A view that can load and display a Chartboost Mediation banner ad."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdView"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView/init()":{"title":"init()","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView\/init()","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/banneradview\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","value":"CBMBannerAdView","op":"replace"},{"op":"replace","value":[{"text":"CBMBannerAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView~1init()\/title","value":"init","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}