{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"reset","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Calling "},{"type":"codeVoice","code":"reset"},{"type":"text","text":" after calling "},{"type":"codeVoice","code":"load"},{"type":"text","text":", but before the load’s "},{"code":"completion","type":"codeVoice"},{"type":"text","text":" has been called, will result in"},{"text":" ","type":"text"},{"type":"codeVoice","code":"completion"},{"type":"text","text":" not being called."}]}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView(im)reset","navigatorTitle":[{"text":"reset","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"reset","kind":"identifier"},{"kind":"text","text":"()"}],"title":"reset()"},"kind":"symbol","variants":[{"paths":["\/documentation\/chartboostmediationsdk\/banneradview\/reset()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/banneradview\/reset()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView\/reset()","interfaceLanguage":"swift"},"abstract":[{"text":"Clears the loaded ad, removes the currently presented ad if any, and stops the auto-refresh process.","type":"text"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","abstract":[{"type":"text","text":"A view that can load and display a Chartboost Mediation banner ad."}],"role":"symbol","title":"BannerAdView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerAdView","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BannerAdView","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView/reset()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView\/reset()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reset","kind":"identifier"},{"kind":"text","text":"()"}],"title":"reset()","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Clears the loaded ad, removes the currently presented ad if any, and stops the auto-refresh process."}],"url":"\/documentation\/chartboostmediationsdk\/banneradview\/reset()","navigatorTitle":[{"text":"reset","kind":"identifier"}]},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","type":"link","title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"reset","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reset","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"reset","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"CBMBannerAdView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments","value":[{"kind":"identifier","text":"CBMBannerAdView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView~1reset()\/title","value":"reset"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView~1reset()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reset","kind":"identifier"}]}]}]}