{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"]]},"sections":[],"metadata":{"modules":[{"name":"ChartboostMediationSDK"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView(py)verticalAlignment","navigatorTitle":[{"kind":"identifier","text":"verticalAlignment"}],"roleHeading":"Instance Property","title":"verticalAlignment","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verticalAlignment"},{"kind":"text","text":": "},{"text":"BannerVerticalAlignment","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CBMBannerVerticalAlignment","kind":"typeIdentifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment","text":"BannerVerticalAlignment","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CBMBannerVerticalAlignment"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/center"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView\/verticalAlignment"},"abstract":[{"type":"text","text":"The vertical alignment of the banner ad within this view, if the size of this view is made larger than the banner ad."}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/banneradview\/verticalalignment"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/banneradview\/verticalalignment"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment":{"abstract":[{"type":"text","text":"The vertical alignment of an ad within "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerVerticalAlignment","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BannerVerticalAlignment"}],"title":"BannerVerticalAlignment","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment/center":{"title":"BannerVerticalAlignment.center","role":"symbol","type":"topic","abstract":[{"text":"The ad will be displayed at the center of the view.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CBMBannerVerticalAlignmentCenter"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/center","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment\/center"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdView"}],"title":"BannerAdView","type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview","navigatorTitle":[{"text":"BannerAdView","kind":"identifier"}],"abstract":[{"text":"A view that can load and display a Chartboost Mediation banner ad.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView/verticalAlignment":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView\/verticalAlignment","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview\/verticalalignment","abstract":[{"type":"text","text":"The vertical alignment of the banner ad within this view, if the size of this view is made larger than the banner ad."}],"title":"verticalAlignment","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verticalAlignment"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CBMBannerVerticalAlignment","text":"BannerVerticalAlignment"}],"navigatorTitle":[{"text":"verticalAlignment","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"verticalAlignment"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"verticalAlignment","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment","text":"CBMBannerVerticalAlignment","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CBMBannerVerticalAlignment"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verticalAlignment"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CBMBannerVerticalAlignment","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/fragments","value":[{"kind":"identifier","text":"CBMBannerVerticalAlignment"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/navigatorTitle","value":[{"kind":"identifier","text":"CBMBannerVerticalAlignment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment~1center\/title","value":"CBMBannerVerticalAlignmentCenter"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment~1center\/fragments","value":[{"text":"CBMBannerVerticalAlignmentCenter","kind":"identifier"}]},{"value":"CBMBannerAdView","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments","value":[{"kind":"identifier","text":"CBMBannerAdView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMBannerAdView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView~1verticalAlignment\/title","value":"verticalAlignment","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView~1verticalAlignment\/fragments","op":"replace","value":[{"kind":"identifier","text":"verticalAlignment"}]}]}]}