{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"winningBidInfo","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"If auto-refresh is enabled, this value will change over time. The"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/willAppear(bannerView:)","isActive":true},{"text":" delegate method will be called after","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"this value changes."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView\/winningBidInfo"},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/banneradview\/winningbidinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/banneradview\/winningbidinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Information about the winning bid, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if a banner is not loaded."}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView(py)winningBidInfo","modules":[{"name":"ChartboostMediationSDK"}],"role":"symbol","title":"winningBidInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"winningBidInfo","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"text":"winningBidInfo","kind":"identifier"}]},"sections":[],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView/winningBidInfo":{"type":"topic","abstract":[{"type":"text","text":"Information about the winning bid, or "},{"type":"codeVoice","code":"nil"},{"text":" if a banner is not loaded.","type":"text"}],"title":"winningBidInfo","url":"\/documentation\/chartboostmediationsdk\/banneradview\/winningbidinfo","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"winningBidInfo","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView\/winningBidInfo","navigatorTitle":[{"text":"winningBidInfo","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerAdView","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","title":"BannerAdView","type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview","navigatorTitle":[{"kind":"identifier","text":"BannerAdView"}],"abstract":[{"text":"A view that can load and display a Chartboost Mediation banner ad.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate/willAppear(bannerView:)":{"url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate\/willappear(bannerview:)","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/willAppear(bannerView:)","title":"willAppear(bannerView:)","type":"topic","abstract":[{"type":"text","text":"Called when a banner ad is about to appear in "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"willAppear","kind":"identifier"},{"kind":"text","text":"("},{"text":"bannerView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView","text":"BannerAdView"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"willAppearWithBannerView:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"winningBidInfo","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"winningBidInfo","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" * "},{"kind":"identifier","text":"winningBidInfo"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"winningBidInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView~1winningBidInfo\/title"},{"op":"replace","value":[{"kind":"identifier","text":"winningBidInfo"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView~1winningBidInfo\/fragments"},{"op":"replace","value":"CBMBannerAdView","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title"},{"value":[{"kind":"identifier","text":"CBMBannerAdView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments"},{"value":"willAppearWithBannerView:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate~1willAppear(bannerView:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate~1willAppear(bannerView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willAppearWithBannerView:","kind":"identifier"}],"op":"replace"}]}]}