{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ad","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","kind":"typeIdentifier","text":"FullscreenAd"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/cbmfullscreenadloadresult\/ad"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/cbmfullscreenadloadresult\/ad"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMFullscreenAdLoadResult\/ad","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadResult(py)ad","symbolKind":"property","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ad","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd"},{"text":"?","kind":"text"}],"title":"ad","navigatorTitle":[{"kind":"identifier","text":"ad"}],"roleHeading":"Instance Property"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The loaded ad if the load was successful, ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" otherwise.","type":"text"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","navigatorTitle":[{"text":"FullscreenAd","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAd"}],"abstract":[{"text":"A Chartboost Mediation fullscreen ad ready to be shown.","type":"text"}],"type":"topic","title":"FullscreenAd"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CBMFullscreenAdLoadResult/ad":{"url":"\/documentation\/chartboostmediationsdk\/cbmfullscreenadloadresult\/ad","type":"topic","navigatorTitle":[{"text":"ad","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMFullscreenAdLoadResult\/ad","kind":"symbol","title":"ad","abstract":[{"type":"text","text":"The loaded ad if the load was successful, "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" otherwise."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ad"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadResult":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"FullscreenAdLoadResult","kind":"identifier"}],"abstract":[{"text":"A result returned by Chartboost Mediation at the end of a fullscreen ad load operation.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdLoadResult"}],"title":"FullscreenAdLoadResult"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ad","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ad"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"CBMFullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd"},{"kind":"text","text":" * "},{"text":"ad","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"CBMFullscreenAd","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMFullscreenAdLoadResult~1ad\/title","value":"ad"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMFullscreenAdLoadResult~1ad\/fragments","value":[{"text":"ad","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/title","value":"CBMFullscreenAdLoadResult"},{"value":[{"text":"CBMFullscreenAdLoadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}