{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/heliumadapterinfo\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/heliumadapterinfo\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo\/isEqual(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)HeliumAdapterInfo(im)isEqual:","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumAdapterInfo":{"role":"symbol","title":"HeliumAdapterInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumAdapterInfo"}],"abstract":[{"type":"text","text":"General info about a partner adapter."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumAdapterInfo"}],"url":"\/documentation\/chartboostmediationsdk\/heliumadapterinfo"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumAdapterInfo/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/chartboostmediationsdk\/heliumadapterinfo\/isequal(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isEqual:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumAdapterInfo\/title","value":"HeliumAdapterInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumAdapterInfo\/fragments","value":[{"kind":"identifier","text":"HeliumAdapterInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumAdapterInfo~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumAdapterInfo~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}