{"kind":"symbol","variants":[{"paths":["\/documentation\/chartboostmediationsdk\/impressiondata\/placement"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/impressiondata\/placement"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ImpressionData\/placement"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The placement associated with Impression Level Revenue Data."}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placement","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"placement","kind":"identifier"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMImpressionData(py)placement","modules":[{"name":"ChartboostMediationSDK"}],"role":"symbol","title":"placement","symbolKind":"property","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placement"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ImpressionData"]]},"sections":[],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ImpressionData":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ImpressionData","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImpressionData"}],"abstract":[{"type":"text","text":"Impression Level Revenue Data (ILRD) object that will be contained in the "},{"code":"NSNotification.object","type":"codeVoice"},{"text":" field for","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"Notification.Name.chartboostMediationDidReceiveILRD"},{"type":"text","text":" notifications."}],"title":"ImpressionData","type":"topic","url":"\/documentation\/chartboostmediationsdk\/impressiondata","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImpressionData"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ImpressionData/placement":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ImpressionData\/placement","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"placement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"The placement associated with Impression Level Revenue Data.","type":"text"}],"title":"placement","type":"topic","url":"\/documentation\/chartboostmediationsdk\/impressiondata\/placement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"placement"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"placement","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"placement"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"placement","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ImpressionData\/title","value":"CBMImpressionData","op":"replace"},{"value":[{"kind":"identifier","text":"CBMImpressionData"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ImpressionData\/fragments"},{"value":[{"text":"CBMImpressionData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ImpressionData\/navigatorTitle"},{"value":"placement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ImpressionData~1placement\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ImpressionData~1placement\/fragments","value":[{"text":"placement","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}