{"abstract":[{"text":"The loaded ad if the load was successful, ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" otherwise.","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ad"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","kind":"typeIdentifier","text":"FullscreenAd"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult\/ad"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadloadresult\/ad"]},{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadloadresult\/ad"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"text":"ad","kind":"identifier"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadResult(py)ad","role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ad","kind":"identifier"},{"kind":"text","text":": "},{"text":"FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"ad","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"title":"FullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenAd","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenAd"}],"type":"topic","abstract":[{"text":"A Chartboost Mediation fullscreen ad ready to be shown.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadResult/ad":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult\/ad","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ad","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd"},{"text":"?","kind":"text"}],"type":"topic","title":"ad","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadresult\/ad","kind":"symbol","abstract":[{"type":"text","text":"The loaded ad if the load was successful, "},{"type":"codeVoice","code":"nil"},{"text":" otherwise.","type":"text"}],"navigatorTitle":[{"text":"ad","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAdLoadResult"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenAdLoadResult"}],"role":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadresult","title":"FullscreenAdLoadResult","kind":"symbol","abstract":[{"type":"text","text":"A result returned by Chartboost Mediation at the end of a fullscreen ad load operation."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ad"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ad","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","text":"CBMFullscreenAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd"},{"kind":"text","text":" * "},{"text":"ad","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title","op":"replace","value":"CBMFullscreenAd"},{"value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"CBMFullscreenAd"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult~1ad\/title","op":"replace","value":"ad"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult~1ad\/fragments","op":"replace","value":[{"kind":"identifier","text":"ad"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/title","op":"replace","value":"CBMFullscreenAdLoadResult"},{"value":[{"kind":"identifier","text":"CBMFullscreenAdLoadResult"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/fragments","op":"replace"},{"op":"replace","value":[{"text":"CBMFullscreenAdLoadResult","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/navigatorTitle"}]}]}