{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"This delegate method is called when an ad expires and is removed from the queue"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenAdQueueDidRemoveExpiredAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"adQueue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","text":"FullscreenAdQueue","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfAdsReady"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"},{"type":"text","text":" calling this method."}]}],"name":"adQueue"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Current count of loaded ads in the queue.","type":"text"}]}],"name":"numberOfAdsReady"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate\/fullscreenadqueuedidremoveexpiredad(_:numberofadsready:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate\/fullscreenadqueuedidremoveexpiredad(_:numberofadsready:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"]]},"metadata":{"role":"symbol","required":true,"symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdQueueDelegate(im)fullscreenAdQueueDidRemoveExpiredAd:numberOfAdsReady:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullscreenAdQueueDidRemoveExpiredAd"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenAdQueue","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue"},{"kind":"text","text":", "},{"text":"numberOfAdsReady","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ChartboostMediationSDK"}],"title":"fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"fullscreenAdQueueDidRemoveExpiredAd:numberOfAdsReady:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate\/fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate/fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)":{"title":"fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate\/fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fullscreenAdQueueDidRemoveExpiredAd:numberOfAdsReady:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenAdQueueDidRemoveExpiredAd","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","text":"FullscreenAdQueue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfAdsReady"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This delegate method is called when an ad expires and is removed from the queue"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate\/fullscreenadqueuedidremoveexpiredad(_:numberofadsready:)","required":true},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"title":"FullscreenAdQueue","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"FullscreenAdQueue","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdQueue"}],"abstract":[{"type":"text","text":"Manages the pre-loading of fullscreen ads. Each "},{"type":"codeVoice","code":"FullscreenAdQueue"},{"type":"text","text":" manages ads for one placement."}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate":{"role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate","navigatorTitle":[{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"title":"FullscreenAdQueueDelegate","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate","type":"topic","abstract":[{"text":"Delegate protocol for getting notified about ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"},{"text":" events.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"fullscreenAdQueueDidRemoveExpiredAd:numberOfAdsReady:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fullscreenAdQueueDidRemoveExpiredAd:numberOfAdsReady:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"fullscreenAdQueueDidRemoveExpiredAd:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","text":"CBMFullscreenAdQueue","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"},{"text":" *) ","kind":"text"},{"text":"adQueue","kind":"internalParam"},{"kind":"text","text":" "},{"text":"numberOfAdsReady:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"numberOfAdsReady","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"adQueue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","isActive":true},{"type":"text","text":" calling this method."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Current count of loaded ads in the queue."}],"type":"paragraph"}],"name":"numberOfAdsReady"}]}},{"value":"fullscreenAdQueueDidRemoveExpiredAd:numberOfAdsReady:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate~1fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"fullscreenAdQueueDidRemoveExpiredAd:numberOfAdsReady:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate~1fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)\/fragments"},{"value":"CBMFullscreenAdQueue","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdQueue"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/navigatorTitle","value":[{"text":"CBMFullscreenAdQueue","kind":"identifier"}]},{"value":"CBMFullscreenAdQueueDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdQueueDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"CBMFullscreenAdQueueDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}