{"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"ChartboostMediationSDK"}],"externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdQueueDelegate(im)fullscreenAdQueue:didFinishLoadingWithResult:numberOfAdsReady:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenAdQueue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"FullscreenAdQueue","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishLoadingWithResult","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdLoadResult","kind":"typeIdentifier","text":"AdLoadResult"},{"text":", ","kind":"text"},{"text":"numberOfAdsReady","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)","navigatorTitle":[{"kind":"identifier","text":"fullscreenAdQueue:didFinishLoadingWithResult:numberOfAdsReady:"}],"symbolKind":"method","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreenAdQueue"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"adQueue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenAdQueue","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue"},{"kind":"text","text":", "},{"text":"didFinishLoadingWithResult","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult","text":"AdLoadResult","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdLoadResult"},{"text":", ","kind":"text"},{"text":"numberOfAdsReady","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"adQueue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","isActive":true,"type":"reference"},{"type":"text","text":" calling this method."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Ad load result with load id, metrics, and error information (if applicable).","type":"text"}]}],"name":"result"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Current count of loaded ads in the queue.","type":"text"}]}],"name":"numberOfAdsReady"}],"kind":"parameters"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"This delegate method is called when a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","type":"reference"},{"type":"text","text":" completes a load request"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate\/fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate\/fullscreenadqueue(_:didfinishloadingwithresult:numberofadsready:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate\/fullscreenadqueue(_:didfinishloadingwithresult:numberofadsready:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate":{"abstract":[{"type":"text","text":"Delegate protocol for getting notified about "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","isActive":true,"type":"reference"},{"type":"text","text":" events."}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"title":"FullscreenAdQueueDelegate","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"navigatorTitle":[{"text":"FullscreenAdQueue","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","title":"FullscreenAdQueue","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FullscreenAdQueue","kind":"identifier"}],"abstract":[{"text":"Manages the pre-loading of fullscreen ads. Each ","type":"text"},{"code":"FullscreenAdQueue","type":"codeVoice"},{"text":" manages ads for one placement.","type":"text"}],"role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate/fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)":{"role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate\/fullscreenadqueue(_:didfinishloadingwithresult:numberofadsready:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fullscreenAdQueue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenAdQueue","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue"},{"text":", ","kind":"text"},{"text":"didFinishLoadingWithResult","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdLoadResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdLoadResult"},{"kind":"text","text":", "},{"text":"numberOfAdsReady","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)","type":"topic","navigatorTitle":[{"text":"fullscreenAdQueue:didFinishLoadingWithResult:numberOfAdsReady:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This delegate method is called when a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","type":"reference"},{"text":" completes a load request","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate\/fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdLoadResult":{"role":"symbol","abstract":[{"text":"A result returned by Chartboost Mediation at the end of an ad load operation.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdLoadResult","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult","kind":"symbol","title":"AdLoadResult","navigatorTitle":[{"text":"AdLoadResult","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/adloadresult"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"kind":"symbol","type":"topic","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"fullscreenAdQueue:didFinishLoadingWithResult:numberOfAdsReady:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fullscreenAdQueue:didFinishLoadingWithResult:numberOfAdsReady:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"fullscreenAdQueue:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","kind":"typeIdentifier","text":"CBMFullscreenAdQueue"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"adQueue"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFinishLoadingWithResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBMAdLoadResult","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdLoadResult"},{"kind":"text","text":" *) "},{"text":"result","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"numberOfAdsReady:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"numberOfAdsReady","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CBMFullscreenAdQueueDelegate","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/title","op":"replace"},{"value":[{"text":"CBMFullscreenAdQueueDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title","value":"CBMFullscreenAdQueue"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdQueue"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate~1fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)\/title","value":"fullscreenAdQueue:didFinishLoadingWithResult:numberOfAdsReady:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fullscreenAdQueue:didFinishLoadingWithResult:numberOfAdsReady:"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate~1fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadResult\/title","op":"replace","value":"CBMAdLoadResult"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadResult\/fragments","value":[{"text":"CBMAdLoadResult","kind":"identifier"}]}]}]}