{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(interstitialAdProviderWithDelegate:andPlacementName:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAdProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumInterstitialAdDelegate","text":"CHBHeliumInterstitialAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"placementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumInterstitialAd","text":"HeliumInterstitialAd"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Delegate to receive interstitial ad callbacks."}]}]},{"name":"placementName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Interstitial ad placement from the Chartboost dashboard."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The interstitial ad provider if successful; otherwise "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" will be returned."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/helium\/interstitialadprovider(with:andplacementname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/helium\/interstitialadprovider(with:andplacementname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/interstitialAdProvider(with:andPlacementName:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Factory method to create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd"},{"type":"text","text":" which will be used to load and show interstitial ads."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"interstitialAdProviderWithDelegate:andPlacementName:"}],"role":"symbol","title":"interstitialAdProvider(with:andPlacementName:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAdProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBHeliumInterstitialAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumInterstitialAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeliumInterstitialAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumInterstitialAd"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)Helium(im)interstitialAdProviderWithDelegate:andPlacementName:","modules":[{"name":"ChartboostMediationSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use loadFullscreenAd(with:completion:) for the most comprehensive fullscreen ad experience."}]}],"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium":{"role":"symbol","title":"Helium","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Helium"}],"url":"\/documentation\/chartboostmediationsdk\/helium"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInterstitialAd":{"role":"symbol","title":"HeliumInterstitialAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInterstitialAd"}],"abstract":[{"type":"text","text":"Helium interstitial ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumInterstitialAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminterstitialad"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/interstitialAdProvider(with:andPlacementName:)":{"deprecated":true,"role":"symbol","title":"interstitialAdProvider(with:andPlacementName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAdProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBHeliumInterstitialAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumInterstitialAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeliumInterstitialAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumInterstitialAd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Factory method to create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd"},{"type":"text","text":" which will be used to load and show interstitial ads."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/interstitialAdProvider(with:andPlacementName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"interstitialAdProviderWithDelegate:andPlacementName:"}],"url":"\/documentation\/chartboostmediationsdk\/helium\/interstitialadprovider(with:andplacementname:)"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumInterstitialAdDelegate":{"role":"symbol","title":"CHBHeliumInterstitialAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumInterstitialAdDelegate"}],"abstract":[{"type":"text","text":"Callbacks for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBHeliumInterstitialAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/chbheliuminterstitialaddelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"interstitialAdProviderWithDelegate:andPlacementName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialAdProviderWithDelegate:andPlacementName:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<HeliumInterstitialAd>","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)HeliumInterstitialAd"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"interstitialAdProviderWithDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<CHBHeliumInterstitialAdDelegate>","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)CHBHeliumInterstitialAdDelegate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"andPlacementName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"placementName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium\/title","value":"Helium"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium\/fragments","value":[{"kind":"identifier","text":"Helium"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInterstitialAd\/title","value":"HeliumInterstitialAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInterstitialAd\/fragments","value":[{"kind":"identifier","text":"HeliumInterstitialAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium~1interstitialAdProvider(with:andPlacementName:)\/title","value":"interstitialAdProviderWithDelegate:andPlacementName:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium~1interstitialAdProvider(with:andPlacementName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialAdProviderWithDelegate:andPlacementName:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CHBHeliumInterstitialAdDelegate\/title","value":"CHBHeliumInterstitialAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CHBHeliumInterstitialAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBHeliumInterstitialAdDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}