{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andAppSignature"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumInitializationOptions","text":"HeliumInitializationOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumSdkDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumSdkDelegate","text":"HeliumSdkDelegate"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Application identifier from the Chartboost dashboard."}]}]},{"name":"appSignature","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Application signature from the Chartboost dashboard."}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional initialization options."}]}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional delegate used to listen for the SDK initialization callback."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/helium\/start(withappid:andappsignature:options:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/helium\/start(withappid:andappsignature:options:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/start(withAppId:andAppSignature:options:delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes the Helium SDK."},{"type":"text","text":" "},{"type":"text","text":"This method must be called before ads can be served."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andAppSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumInitializationOptions","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumInitializationOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumSdkDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumSdkDelegate"},{"kind":"text","text":"?)"}],"title":"start(withAppId:andAppSignature:options:delegate:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)Helium(im)startWithAppId:andAppSignature:options:delegate:","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"startWithAppId:andAppSignature:options:delegate:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/start(withAppId:andAppSignature:options:delegate:)":{"role":"symbol","title":"start(withAppId:andAppSignature:options:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andAppSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumInitializationOptions","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumInitializationOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumSdkDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumSdkDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes the Helium SDK."},{"type":"text","text":" "},{"type":"text","text":"This method must be called before ads can be served."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/start(withAppId:andAppSignature:options:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:andAppSignature:options:delegate:"}],"url":"\/documentation\/chartboostmediationsdk\/helium\/start(withappid:andappsignature:options:delegate:)"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium":{"role":"symbol","title":"Helium","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Helium"}],"url":"\/documentation\/chartboostmediationsdk\/helium"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInitializationOptions":{"role":"symbol","title":"HeliumInitializationOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInitializationOptions"}],"abstract":[{"type":"text","text":"Options for Helium initialization."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumInitializationOptions"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminitializationoptions"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumSdkDelegate":{"role":"symbol","title":"HeliumSdkDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumSdkDelegate"}],"abstract":[{"type":"text","text":"Delegate for receiving "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium"},{"type":"text","text":" SDK initialization callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumSdkDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumSdkDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/heliumsdkdelegate"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startWithAppId:andAppSignature:options:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startWithAppId:andAppSignature:options:delegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startWithAppId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"kind":"text","text":" "},{"kind":"identifier","text":"andAppSignature:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appSignature"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumInitializationOptions","text":"HeliumInitializationOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<HeliumSdkDelegate>","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)HeliumSdkDelegate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium~1start(withAppId:andAppSignature:options:delegate:)\/title","value":"startWithAppId:andAppSignature:options:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium~1start(withAppId:andAppSignature:options:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startWithAppId:andAppSignature:options:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium\/title","value":"Helium"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium\/fragments","value":[{"kind":"identifier","text":"Helium"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions\/title","value":"HeliumInitializationOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions\/fragments","value":[{"kind":"identifier","text":"HeliumInitializationOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumSdkDelegate\/title","value":"HeliumSdkDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumSdkDelegate\/fragments","value":[{"kind":"identifier","text":"HeliumSdkDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}