{"metadata":{"required":true,"role":"symbol","symbolKind":"method","title":"didRecordImpression(bannerView:)","modules":[{"name":"ChartboostMediationSDK"}],"externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMBannerAdViewDelegate(im)didRecordImpressionWithBannerView:","navigatorTitle":[{"text":"didRecordImpressionWithBannerView:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView","text":"BannerAdView"},{"text":")","kind":"text"}]},"abstract":[{"text":"Called when Chartboost Mediation records an impression as result of the ad being shown.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didRecordImpression","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"BannerAdView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The banner that triggered this event."}],"type":"paragraph"}],"name":"bannerView"}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/banneradviewdelegate\/didrecordimpression(bannerview:)"]},{"paths":["\/documentation\/chartboostmediationsdk\/banneradviewdelegate\/didrecordimpression(bannerview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/didRecordImpression(bannerView:)"},"kind":"symbol","references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate":{"abstract":[{"type":"text","text":"A "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true,"type":"reference"},{"type":"text","text":" delegate that receives ad callbacks."}],"title":"BannerAdViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"BannerAdViewDelegate","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"BannerAdViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerAdView","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/banneradview","abstract":[{"text":"A view that can load and display a Chartboost Mediation banner ad.","type":"text"}],"role":"symbol","title":"BannerAdView","kind":"symbol","navigatorTitle":[{"text":"BannerAdView","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate/didRecordImpression(bannerView:)":{"type":"topic","title":"didRecordImpression(bannerView:)","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate\/didrecordimpression(bannerview:)","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didRecordImpressionWithBannerView:"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/didRecordImpression(bannerView:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didRecordImpression"},{"kind":"text","text":"("},{"text":"bannerView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"BannerAdView","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Called when Chartboost Mediation records an impression as result of the ad being shown.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"didRecordImpressionWithBannerView:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRecordImpressionWithBannerView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didRecordImpressionWithBannerView:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView","text":"CBMBannerAdView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bannerView"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The banner that triggered this event."}],"type":"paragraph"}],"name":"bannerView"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/title","op":"replace","value":"CBMBannerAdViewDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMBannerAdViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/navigatorTitle","value":[{"text":"CBMBannerAdViewDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","value":"CBMBannerAdView"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments","value":[{"kind":"identifier","text":"CBMBannerAdView"}],"op":"replace"},{"value":[{"text":"CBMBannerAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate~1didRecordImpression(bannerView:)\/title","value":"didRecordImpressionWithBannerView:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"didRecordImpressionWithBannerView:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate~1didRecordImpression(bannerView:)\/fragments"}]}]}