{"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/adloadrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/adloadrequest"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"metadata":{"modules":[{"name":"ChartboostMediationSDK"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdLoadRequest","kind":"identifier"}],"navigatorTitle":[{"text":"AdLoadRequest","kind":"identifier"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdLoadRequest","title":"AdLoadRequest","symbolKind":"class","roleHeading":"Class"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"A base class inherited by other request types."}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadRequest","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBMAdLoadRequest) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdLoadRequest"}]}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult"],"generated":true,"title":"Ad Request and Response"}],"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadRequest\/placement"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ChartboostMediationSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadRequest":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerAdLoadRequest"}],"url":"\/documentation\/chartboostmediationsdk\/banneradloadrequest","type":"topic","abstract":[{"type":"text","text":"A request used to load a banner ad."}],"role":"symbol","navigatorTitle":[{"text":"BannerAdLoadRequest","kind":"identifier"}],"title":"BannerAdLoadRequest","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest"},"doc://org.cocoapods.ChartboostMediationSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdLoadRequest/placement":{"title":"placement","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"placement","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"text":"placement","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadRequest\/placement","url":"\/documentation\/chartboostmediationsdk\/adloadrequest\/placement","kind":"symbol","abstract":[{"text":"Placement from the Chartboost Mediation dashboard.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdLoadRequest":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadRequest","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"AdLoadRequest","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/adloadrequest","abstract":[{"type":"text","text":"A base class inherited by other request types."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdLoadRequest"}],"title":"AdLoadRequest"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadRequest":{"kind":"symbol","navigatorTitle":[{"text":"FullscreenAdLoadRequest","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdLoadRequest"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadrequest","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","abstract":[{"text":"A request used to load a Chartboost Mediation fullscreen ad.","type":"text"}],"title":"FullscreenAdLoadRequest"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdLoadResult":{"url":"\/documentation\/chartboostmediationsdk\/adloadresult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdLoadResult"}],"role":"symbol","title":"AdLoadResult","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult","navigatorTitle":[{"text":"AdLoadResult","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A result returned by Chartboost Mediation at the end of an ad load operation."}]},"doc://org.cocoapods.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CBMAdLoadRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"CBMAdLoadRequest"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CBMAdLoadRequest"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadRequest\/placement"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest"]}]},{"value":[{"title":"Ad Request and Response","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMAdLoadRequest"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"CBMBannerAdLoadRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/fragments","op":"replace","value":[{"text":"CBMBannerAdLoadRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadRequest~1placement\/title","value":"placement"},{"value":[{"kind":"identifier","text":"placement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadRequest~1placement\/fragments"},{"value":"CBMAdLoadRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadRequest\/fragments","value":[{"text":"CBMAdLoadRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/title","value":"CBMFullscreenAdLoadRequest"},{"op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAdLoadRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadResult\/title","op":"replace","value":"CBMAdLoadResult"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadResult\/fragments","op":"replace","value":[{"text":"CBMAdLoadResult","kind":"identifier"}]}]}]}