{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(CBMBannerVerticalAlignment) ","kind":"text"},{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerVerticalAlignment","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"If "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"type":"text","text":" is made larger than the size of the displayed ad, this will be used to determine the"},{"text":" ","type":"text"},{"type":"text","text":"vertical position of the ad within the view."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/bottom","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/center","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/top"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/Equatable-Implementations","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/bannerverticalalignment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/bannerverticalalignment"]}],"metadata":{"externalID":"c:@M@ChartboostMediationSDK@E@CBMBannerVerticalAlignment","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"BannerVerticalAlignment"}],"modules":[{"name":"ChartboostMediationSDK"}],"title":"BannerVerticalAlignment","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerVerticalAlignment"}],"roleHeading":"Enumeration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment","interfaceLanguage":"swift"},"abstract":[{"text":"The vertical alignment of an ad within ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"text":".","type":"text"}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SY"],"kind":"relationships","title":"Conforms To"}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment"],"generated":true,"title":"Banner Ads"}],"kind":"symbol","references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BannerVerticalAlignment","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment","type":"topic","abstract":[{"text":"The vertical alignment of an ad within ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerVerticalAlignment"}],"title":"BannerVerticalAlignment","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BannerHorizontalAlignment","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment","type":"topic","abstract":[{"type":"text","text":"The horizontal alignment of an ad within "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerHorizontalAlignment"}],"title":"BannerHorizontalAlignment","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment/top":{"title":"BannerVerticalAlignment.top","kind":"symbol","abstract":[{"text":"The ad will be displayed at the top of the view.","type":"text"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment\/top","role":"symbol","navigatorTitle":[{"text":"CBMBannerVerticalAlignmentTop","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/top"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BannerSize","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannersize","type":"topic","abstract":[{"type":"text","text":"The size of a banner ad."}],"role":"symbol","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"title":"BannerSize","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment/center":{"title":"BannerVerticalAlignment.center","abstract":[{"text":"The ad will be displayed at the center of the view.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CBMBannerVerticalAlignmentCenter"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/center","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"center"}],"url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment\/center","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerAdView","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","title":"BannerAdView","type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview","navigatorTitle":[{"kind":"identifier","text":"BannerAdView"}],"abstract":[{"text":"A view that can load and display a Chartboost Mediation banner ad.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerAdViewDelegate","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate","type":"topic","abstract":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"type":"text","text":" delegate that receives ad callbacks."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerAdViewDelegate"}],"title":"BannerAdViewDelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerType":{"url":"\/documentation\/chartboostmediationsdk\/bannertype","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","abstract":[{"type":"text","text":"The type of a banner ad."}],"title":"BannerType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerType"}],"kind":"symbol","navigatorTitle":[{"text":"BannerType","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment\/rawrepresentable-implementations","kind":"article"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadRequest":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerAdLoadRequest"}],"url":"\/documentation\/chartboostmediationsdk\/banneradloadrequest","type":"topic","abstract":[{"type":"text","text":"A request used to load a banner ad."}],"role":"symbol","navigatorTitle":[{"text":"BannerAdLoadRequest","kind":"identifier"}],"title":"BannerAdLoadRequest","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadResult":{"url":"\/documentation\/chartboostmediationsdk\/banneradloadresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerAdLoadResult","kind":"identifier"}],"role":"symbol","title":"BannerAdLoadResult","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","navigatorTitle":[{"kind":"identifier","text":"BannerAdLoadResult"}],"type":"topic","abstract":[{"type":"text","text":"The result of a banner load operation."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment/init(rawValue:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(rawValue:)","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/init(rawValue:)","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment/bottom":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBMBannerVerticalAlignmentBottom"}],"title":"BannerVerticalAlignment.bottom","role":"symbol","abstract":[{"text":"The ad will be displayed at the bottom of the view.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"bottom","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/bottom","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment\/bottom"},"doc://org.cocoapods.ChartboostMediationSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SY"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment/Equatable-Implementations":{"kind":"article","type":"topic","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/Equatable-Implementations","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment\/equatable-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"CBMBannerVerticalAlignment","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"CBMBannerVerticalAlignment"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CBMBannerVerticalAlignment","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/bottom","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/center","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/top"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Banner Ads","generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CBMBannerVerticalAlignment","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/title","value":"CBMBannerVerticalAlignment"},{"op":"replace","value":[{"text":"CBMBannerVerticalAlignment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/title","value":"CBMBannerHorizontalAlignment"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/fragments","value":[{"text":"CBMBannerHorizontalAlignment","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment~1top\/title","value":"CBMBannerVerticalAlignmentTop"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment~1top\/fragments","value":[{"kind":"identifier","text":"CBMBannerVerticalAlignmentTop"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title","value":"CBMBannerSize","op":"replace"},{"value":[{"kind":"identifier","text":"CBMBannerSize"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment~1center\/title","value":"CBMBannerVerticalAlignmentCenter","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment~1center\/fragments","value":[{"text":"CBMBannerVerticalAlignmentCenter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","op":"replace","value":"CBMBannerAdView"},{"value":[{"kind":"identifier","text":"CBMBannerAdView"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments","op":"replace"},{"value":"CBMBannerAdViewDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/title"},{"value":[{"kind":"identifier","text":"CBMBannerAdViewDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/title","value":"CBMBannerType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/fragments","value":[{"text":"CBMBannerType","kind":"identifier"}],"op":"replace"},{"value":"CBMBannerAdLoadRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/title"},{"value":[{"kind":"identifier","text":"CBMBannerAdLoadRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/title","value":"CBMBannerAdLoadResult"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMBannerAdLoadResult"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment~1bottom\/title","op":"replace","value":"CBMBannerVerticalAlignmentBottom"},{"value":[{"text":"CBMBannerVerticalAlignmentBottom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment~1bottom\/fragments"}]}]}