{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBMBannerHorizontalAlignment) "},{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BannerHorizontalAlignment","kind":"identifier"}]}]},{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true,"type":"reference"},{"type":"text","text":" is made larger than the size of the displayed ad, this will be used to determine the"},{"type":"text","text":" "},{"type":"text","text":"horizontal position of the ad within the view."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/center","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/left","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/right"],"generated":true,"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/Equatable-Implementations","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/RawRepresentable-Implementations"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@ChartboostMediationSDK@E@CBMBannerHorizontalAlignment","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerHorizontalAlignment"}],"symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"text":"BannerHorizontalAlignment","kind":"identifier"}],"modules":[{"name":"ChartboostMediationSDK"}],"role":"symbol","title":"BannerHorizontalAlignment"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/s15BitwiseCopyableP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SY","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s8SendableP"]}],"abstract":[{"type":"text","text":"The horizontal alignment of an ad within "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"type":"text","text":"."}],"seeAlsoSections":[{"title":"Banner Ads","generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"],"anchor":"Banner-Ads"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/center":{"kind":"symbol","role":"symbol","type":"topic","title":"BannerHorizontalAlignment.center","abstract":[{"text":"The ad will be displayed at the center of the view.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/center","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/center","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"center"}],"navigatorTitle":[{"text":"CBMBannerHorizontalAlignmentCenter","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/init(rawValue:)":{"role":"symbol","kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/init(rawValue:)","type":"topic","abstract":[],"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/Equatable-Implementations":{"abstract":[],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/equatable-implementations"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate":{"abstract":[{"text":"A ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"text":" delegate that receives ad callbacks.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdViewDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerAdViewDelegate"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","title":"BannerAdViewDelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadRequest":{"title":"BannerAdLoadRequest","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A request used to load a banner ad."}],"navigatorTitle":[{"text":"BannerAdLoadRequest","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdLoadRequest"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","url":"\/documentation\/chartboostmediationsdk\/banneradloadrequest"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerType":{"title":"BannerType","abstract":[{"text":"The type of a banner ad.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerType","kind":"identifier"}],"navigatorTitle":[{"text":"BannerType","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannertype","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"url":"\/documentation\/chartboostmediationsdk\/bannersize","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"abstract":[{"type":"text","text":"The size of a banner ad."}],"kind":"symbol","title":"BannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerSize"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadResult":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","type":"topic","title":"BannerAdLoadResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdLoadResult"}],"abstract":[{"type":"text","text":"The result of a banner load operation."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerAdLoadResult"}],"url":"\/documentation\/chartboostmediationsdk\/banneradloadresult"},"doc://org.cocoapods.ChartboostMediationSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","kind":"article","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/RawRepresentable-Implementations","url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/rawrepresentable-implementations"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/left":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/left","abstract":[{"type":"text","text":"The ad will be displayed at the left of the view."}],"title":"BannerHorizontalAlignment.left","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentLeft"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/left"},"doc://org.cocoapods.ChartboostMediationSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/right":{"type":"topic","title":"BannerHorizontalAlignment.right","abstract":[{"type":"text","text":"The ad will be displayed at the right of the view."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"right","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/right","navigatorTitle":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentRight"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/right","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment":{"abstract":[{"text":"The horizontal alignment of an ad within ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment","role":"symbol","title":"BannerHorizontalAlignment","navigatorTitle":[{"text":"BannerHorizontalAlignment","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"BannerHorizontalAlignment","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment":{"abstract":[{"type":"text","text":"The vertical alignment of an ad within "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerVerticalAlignment","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BannerVerticalAlignment"}],"title":"BannerVerticalAlignment","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdView"}],"title":"BannerAdView","type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview","navigatorTitle":[{"text":"BannerAdView","kind":"identifier"}],"abstract":[{"text":"A view that can load and display a Chartboost Mediation banner ad.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ChartboostMediationSDK/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"CBMBannerHorizontalAlignment","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"kind":"identifier","text":"CBMBannerHorizontalAlignment"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CBMBannerHorizontalAlignment","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/center","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/left","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/right"],"generated":true,"title":"Enumeration Cases"}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Banner Ads","anchor":"Banner-Ads","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMBannerHorizontalAlignment"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"CBMBannerHorizontalAlignmentCenter","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1center\/title"},{"value":[{"text":"CBMBannerHorizontalAlignmentCenter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1center\/fragments"},{"op":"replace","value":"CBMBannerAdViewDelegate","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/fragments","value":[{"kind":"identifier","text":"CBMBannerAdViewDelegate"}]},{"op":"replace","value":[{"text":"CBMBannerAdViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/navigatorTitle"},{"op":"replace","value":"CBMBannerAdLoadRequest","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/fragments","value":[{"kind":"identifier","text":"CBMBannerAdLoadRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMBannerAdLoadRequest"}]},{"value":"CBMBannerType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/fragments","value":[{"kind":"identifier","text":"CBMBannerType"}]},{"value":[{"text":"CBMBannerType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/navigatorTitle"},{"value":"CBMBannerSize","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title","op":"replace"},{"value":[{"text":"CBMBannerSize","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/navigatorTitle","value":[{"text":"CBMBannerSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/title","value":"CBMBannerAdLoadResult","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/fragments","value":[{"text":"CBMBannerAdLoadResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/navigatorTitle","op":"replace","value":[{"text":"CBMBannerAdLoadResult","kind":"identifier"}]},{"op":"replace","value":"CBMBannerHorizontalAlignmentLeft","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1left\/title"},{"value":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentLeft"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1left\/fragments","op":"replace"},{"value":"CBMBannerHorizontalAlignmentRight","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1right\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1right\/fragments","value":[{"text":"CBMBannerHorizontalAlignmentRight","kind":"identifier"}],"op":"replace"},{"value":"CBMBannerHorizontalAlignment","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMBannerHorizontalAlignment"}]},{"value":[{"kind":"identifier","text":"CBMBannerHorizontalAlignment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/navigatorTitle"},{"op":"replace","value":"CBMBannerVerticalAlignment","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CBMBannerVerticalAlignment"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMBannerVerticalAlignment"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","op":"replace","value":"CBMBannerAdView"},{"op":"replace","value":[{"kind":"identifier","text":"CBMBannerAdView"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/navigatorTitle","value":[{"kind":"identifier","text":"CBMBannerAdView"}],"op":"replace"}]}]}