{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadRequest"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(CBMBannerAdLoadRequest) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerAdLoadRequest","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A request used to load a banner ad."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest\/init(placement:size:)"],"anchor":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest\/size"],"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/banneradloadrequest"]},{"paths":["\/documentation\/chartboostmediationsdk\/banneradloadrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest"},"metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdLoadRequest","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"BannerAdLoadRequest","kind":"identifier"}],"title":"BannerAdLoadRequest","modules":[{"name":"ChartboostMediationSDK"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerAdLoadRequest"}]},"seeAlsoSections":[{"title":"Banner Ads","anchor":"Banner-Ads","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"],"generated":true}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment":{"abstract":[{"type":"text","text":"The vertical alignment of an ad within "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerVerticalAlignment","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BannerVerticalAlignment"}],"title":"BannerVerticalAlignment","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadRequest/size":{"url":"\/documentation\/chartboostmediationsdk\/banneradloadrequest\/size","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest\/size","title":"size","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"text":"BannerSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"}],"kind":"symbol","abstract":[{"text":"The maximum size of banner to request.","type":"text"}],"navigatorTitle":[{"text":"size","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadRequest/init(placement:size:)":{"url":"\/documentation\/chartboostmediationsdk\/banneradloadrequest\/init(placement:size:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest\/init(placement:size:)","title":"init(placement:size:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"placement"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"text":"BannerSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Initializes the banner load request with the desired parameters.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPlacement:size:"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadResult":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","type":"topic","title":"BannerAdLoadResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdLoadResult"}],"abstract":[{"type":"text","text":"The result of a banner load operation."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerAdLoadResult"}],"url":"\/documentation\/chartboostmediationsdk\/banneradloadresult"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadRequest":{"title":"BannerAdLoadRequest","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A request used to load a banner ad."}],"navigatorTitle":[{"text":"BannerAdLoadRequest","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdLoadRequest"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","url":"\/documentation\/chartboostmediationsdk\/banneradloadrequest"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate":{"abstract":[{"text":"A ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"text":" delegate that receives ad callbacks.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdViewDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerAdViewDelegate"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","title":"BannerAdViewDelegate"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"url":"\/documentation\/chartboostmediationsdk\/bannersize","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"abstract":[{"type":"text","text":"The size of a banner ad."}],"kind":"symbol","title":"BannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerSize"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadRequest/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest\/isEqual(_:)","abstract":[],"type":"topic","role":"symbol","title":"isEqual(_:)","url":"\/documentation\/chartboostmediationsdk\/banneradloadrequest\/isequal(_:)","kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdLoadRequest":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdLoadRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AdLoadRequest"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/adloadrequest","abstract":[{"text":"A base class inherited by other request types.","type":"text"}],"title":"AdLoadRequest","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadRequest"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdView"}],"title":"BannerAdView","type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview","navigatorTitle":[{"text":"BannerAdView","kind":"identifier"}],"abstract":[{"text":"A view that can load and display a Chartboost Mediation banner ad.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment":{"abstract":[{"text":"The horizontal alignment of an ad within ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment","role":"symbol","title":"BannerHorizontalAlignment","navigatorTitle":[{"text":"BannerHorizontalAlignment","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"BannerHorizontalAlignment","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerType":{"title":"BannerType","abstract":[{"text":"The type of a banner ad.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerType","kind":"identifier"}],"navigatorTitle":[{"text":"BannerType","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannertype","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CBMBannerAdLoadRequest"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"CBMBannerAdLoadRequest","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"CBMBannerAdLoadRequest"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest\/size"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest\/init(placement:size:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true}]},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadRequest"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"anchor":"Banner-Ads","title":"Banner Ads","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"],"generated":true}],"op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"CBMBannerAdLoadRequest","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadRequest","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdLoadRequest","text":"CBMAdLoadRequest"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/title","value":"CBMBannerVerticalAlignment","op":"replace"},{"value":[{"kind":"identifier","text":"CBMBannerVerticalAlignment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/fragments"},{"value":[{"text":"CBMBannerVerticalAlignment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest~1size\/title","value":"size"},{"value":[{"text":"size","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest~1size\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest~1init(placement:size:)\/title","value":"initWithPlacement:size:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest~1init(placement:size:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithPlacement:size:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/title","value":"CBMBannerAdLoadResult"},{"op":"replace","value":[{"kind":"identifier","text":"CBMBannerAdLoadResult"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/navigatorTitle","value":[{"text":"CBMBannerAdLoadResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/title","value":"CBMBannerAdLoadRequest"},{"op":"replace","value":[{"text":"CBMBannerAdLoadRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/navigatorTitle","value":[{"text":"CBMBannerAdLoadRequest","kind":"identifier"}]},{"value":"CBMBannerAdViewDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/fragments","op":"replace","value":[{"text":"CBMBannerAdViewDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/navigatorTitle","value":[{"text":"CBMBannerAdViewDelegate","kind":"identifier"}]},{"value":"CBMBannerSize","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMBannerSize"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMBannerSize"}]},{"value":"isEqual:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest~1isEqual(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadRequest\/title","op":"replace","value":"CBMAdLoadRequest"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadRequest\/fragments","value":[{"text":"CBMAdLoadRequest","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadRequest\/navigatorTitle","value":[{"kind":"identifier","text":"CBMAdLoadRequest"}]},{"value":"CBMBannerAdView","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments","value":[{"text":"CBMBannerAdView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/navigatorTitle","op":"replace","value":[{"text":"CBMBannerAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/title","op":"replace","value":"CBMBannerHorizontalAlignment"},{"op":"replace","value":[{"kind":"identifier","text":"CBMBannerHorizontalAlignment"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/fragments"},{"value":[{"kind":"identifier","text":"CBMBannerHorizontalAlignment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/title","value":"CBMBannerType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/fragments","op":"replace","value":[{"text":"CBMBannerType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/navigatorTitle","value":[{"text":"CBMBannerType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}