{"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMBannerAdLoadResult\/size"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult"},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"],"generated":true,"title":"Banner Ads"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBMBannerAdLoadResult) "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdLoadResult"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/banneradloadresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/banneradloadresult"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdLoadResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerAdLoadResult","kind":"identifier"}],"symbolKind":"class","title":"BannerAdLoadResult","navigatorTitle":[{"kind":"identifier","text":"BannerAdLoadResult"}],"roleHeading":"Class","modules":[{"name":"ChartboostMediationSDK"}],"role":"symbol"},"abstract":[{"type":"text","text":"The result of a banner load operation."}],"kind":"symbol","references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BannerHorizontalAlignment","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment","type":"topic","abstract":[{"type":"text","text":"The horizontal alignment of an ad within "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerHorizontalAlignment"}],"title":"BannerHorizontalAlignment","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerType":{"url":"\/documentation\/chartboostmediationsdk\/bannertype","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","abstract":[{"type":"text","text":"The type of a banner ad."}],"title":"BannerType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerType"}],"kind":"symbol","navigatorTitle":[{"text":"BannerType","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerAdView","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","title":"BannerAdView","type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview","navigatorTitle":[{"kind":"identifier","text":"BannerAdView"}],"abstract":[{"text":"A view that can load and display a Chartboost Mediation banner ad.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadRequest":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerAdLoadRequest"}],"url":"\/documentation\/chartboostmediationsdk\/banneradloadrequest","type":"topic","abstract":[{"type":"text","text":"A request used to load a banner ad."}],"role":"symbol","navigatorTitle":[{"text":"BannerAdLoadRequest","kind":"identifier"}],"title":"BannerAdLoadRequest","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BannerVerticalAlignment","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment","type":"topic","abstract":[{"text":"The vertical alignment of an ad within ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerVerticalAlignment"}],"title":"BannerVerticalAlignment","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BannerSize","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannersize","type":"topic","abstract":[{"type":"text","text":"The size of a banner ad."}],"role":"symbol","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"title":"BannerSize","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CBMBannerAdLoadResult/size":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"text":"BannerSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"},{"text":"?","kind":"text"}],"url":"\/documentation\/chartboostmediationsdk\/cbmbanneradloadresult\/size","type":"topic","abstract":[{"text":"The size of the loaded ad, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" in the case of load error.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"size"}],"title":"size","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMBannerAdLoadResult\/size"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerAdViewDelegate","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate","type":"topic","abstract":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"type":"text","text":" delegate that receives ad callbacks."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerAdViewDelegate"}],"title":"BannerAdViewDelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate"},"doc://org.cocoapods.ChartboostMediationSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdLoadResult":{"url":"\/documentation\/chartboostmediationsdk\/adloadresult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdLoadResult"}],"role":"symbol","title":"AdLoadResult","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult","navigatorTitle":[{"text":"AdLoadResult","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A result returned by Chartboost Mediation at the end of an ad load operation."}]},"doc://org.cocoapods.ChartboostMediationSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadResult":{"url":"\/documentation\/chartboostmediationsdk\/banneradloadresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerAdLoadResult","kind":"identifier"}],"role":"symbol","title":"BannerAdLoadResult","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","navigatorTitle":[{"kind":"identifier","text":"BannerAdLoadResult"}],"type":"topic","abstract":[{"type":"text","text":"The result of a banner load operation."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"CBMBannerAdLoadResult"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"CBMBannerAdLoadResult","kind":"identifier"}],"op":"replace"},{"value":[{"text":"CBMBannerAdLoadResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMBannerAdLoadResult\/size"]}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Banner Ads","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"CBMBannerAdLoadResult","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdLoadResult","text":"CBMAdLoadResult"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"CBMBannerHorizontalAlignment","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/title"},{"value":[{"text":"CBMBannerHorizontalAlignment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/title","value":"CBMBannerType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/fragments","value":[{"kind":"identifier","text":"CBMBannerType"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","op":"replace","value":"CBMBannerAdView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments","value":[{"text":"CBMBannerAdView","kind":"identifier"}]},{"op":"replace","value":"CBMBannerAdLoadRequest","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/fragments","value":[{"text":"CBMBannerAdLoadRequest","kind":"identifier"}]},{"value":"CBMBannerVerticalAlignment","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/title"},{"op":"replace","value":[{"text":"CBMBannerVerticalAlignment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title","op":"replace","value":"CBMBannerSize"},{"op":"replace","value":[{"kind":"identifier","text":"CBMBannerSize"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMBannerAdLoadResult~1size\/title","value":"size"},{"value":[{"text":"size","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMBannerAdLoadResult~1size\/fragments"},{"value":"CBMBannerAdViewDelegate","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/title","op":"replace"},{"value":[{"text":"CBMBannerAdViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/fragments"},{"value":"CBMAdLoadResult","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadResult\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadResult\/fragments","value":[{"text":"CBMAdLoadResult","kind":"identifier"}],"op":"replace"},{"value":"CBMBannerAdLoadResult","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/fragments","value":[{"text":"CBMBannerAdLoadResult","kind":"identifier"}],"op":"replace"}]}]}