{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"metadata":{"role":"symbol","symbolKind":"protocol","roleHeading":"Protocol","title":"BannerAdViewDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerAdViewDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"BannerAdViewDelegate"}],"modules":[{"name":"ChartboostMediationSDK"}],"externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMBannerAdViewDelegate"},"abstract":[{"text":"A ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","type":"reference","isActive":true},{"text":" delegate that receives ad callbacks.","type":"text"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/didClick(bannerView:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/didRecordImpression(bannerView:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/willAppear(bannerView:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/banneradviewdelegate"]},{"paths":["\/documentation\/chartboostmediationsdk\/banneradviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(CBMBannerAdViewDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerAdViewDelegate","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate"},"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"],"title":"Banner Ads"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate/willAppear(bannerView:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/willAppear(bannerView:)","abstract":[{"text":"Called when a banner ad is about to appear in ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"text":".","type":"text"}],"required":true,"title":"willAppear(bannerView:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"willAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BannerAdView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"willAppearWithBannerView:","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate\/willappear(bannerview:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment","abstract":[{"type":"text","text":"The vertical alignment of an ad within "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","type":"reference","isActive":true},{"text":".","type":"text"}],"role":"symbol","title":"BannerVerticalAlignment","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerVerticalAlignment","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BannerVerticalAlignment","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","abstract":[{"type":"text","text":"A view that can load and display a Chartboost Mediation banner ad."}],"role":"symbol","title":"BannerAdView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerAdView","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BannerAdView","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerType":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","type":"topic","kind":"symbol","title":"BannerType","url":"\/documentation\/chartboostmediationsdk\/bannertype","abstract":[{"type":"text","text":"The type of a banner ad."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerType"}],"navigatorTitle":[{"text":"BannerType","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","abstract":[{"text":"The horizontal alignment of an ad within ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"type":"text","text":"."}],"role":"symbol","title":"BannerHorizontalAlignment","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerHorizontalAlignment"}],"kind":"symbol","navigatorTitle":[{"text":"BannerHorizontalAlignment","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadResult":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","abstract":[{"type":"text","text":"The result of a banner load operation."}],"role":"symbol","title":"BannerAdLoadResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BannerAdLoadResult","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BannerAdLoadResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradloadresult"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadRequest":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","abstract":[{"type":"text","text":"A request used to load a banner ad."}],"role":"symbol","title":"BannerAdLoadRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdLoadRequest"}],"kind":"symbol","navigatorTitle":[{"text":"BannerAdLoadRequest","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradloadrequest"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate/didClick(bannerView:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/didClick(bannerView:)","abstract":[{"type":"text","text":"Called when the ad is clicked by the user."}],"required":true,"title":"didClick(bannerView:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didClick","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView","text":"BannerAdView","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"didClickWithBannerView:","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate\/didclick(bannerview:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate","abstract":[{"text":"A ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"text":" delegate that receives ad callbacks.","type":"text"}],"role":"symbol","title":"BannerAdViewDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerAdViewDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BannerAdViewDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"url":"\/documentation\/chartboostmediationsdk\/bannersize","navigatorTitle":[{"kind":"identifier","text":"BannerSize"}],"type":"topic","title":"BannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","abstract":[{"text":"The size of a banner ad.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerSize","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdViewDelegate/didRecordImpression(bannerView:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/didRecordImpression(bannerView:)","abstract":[{"type":"text","text":"Called when Chartboost Mediation records an impression as result of the ad being shown."}],"role":"symbol","title":"didRecordImpression(bannerView:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didRecordImpression","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bannerView"},{"text":": ","kind":"text"},{"text":"BannerAdView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdView"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"didRecordImpressionWithBannerView:","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradviewdelegate\/didrecordimpression(bannerview:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"CBMBannerAdViewDelegate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"text":"CBMBannerAdViewDelegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"CBMBannerAdViewDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/didClick(bannerView:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/didRecordImpression(bannerView:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdViewDelegate\/willAppear(bannerView:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Banner Ads","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerType","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"]}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBMBannerAdViewDelegate"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"willAppearWithBannerView:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate~1willAppear(bannerView:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"willAppearWithBannerView:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate~1willAppear(bannerView:)\/fragments"},{"op":"replace","value":"CBMBannerVerticalAlignment","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/title"},{"value":[{"text":"CBMBannerVerticalAlignment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","value":"CBMBannerAdView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments","value":[{"text":"CBMBannerAdView","kind":"identifier"}]},{"op":"replace","value":"CBMBannerType","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/title"},{"op":"replace","value":[{"text":"CBMBannerType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/title","value":"CBMBannerHorizontalAlignment"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/fragments","op":"replace","value":[{"text":"CBMBannerHorizontalAlignment","kind":"identifier"}]},{"value":"CBMBannerAdLoadResult","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/title"},{"value":[{"text":"CBMBannerAdLoadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadResult\/fragments"},{"value":"CBMBannerAdLoadRequest","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/fragments","value":[{"text":"CBMBannerAdLoadRequest","kind":"identifier"}],"op":"replace"},{"value":"didClickWithBannerView:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate~1didClick(bannerView:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate~1didClick(bannerView:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didClickWithBannerView:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/title","value":"CBMBannerAdViewDelegate"},{"value":[{"text":"CBMBannerAdViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title","op":"replace","value":"CBMBannerSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments","value":[{"text":"CBMBannerSize","kind":"identifier"}]},{"value":"didRecordImpressionWithBannerView:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate~1didRecordImpression(bannerView:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRecordImpressionWithBannerView:"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdViewDelegate~1didRecordImpression(bannerView:)\/fragments"}]}]}