{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerViewDelegate"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationbannerviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationbannerviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView"},{"type":"text","text":" delegate that receives ad callbacks."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerViewDelegate"}],"title":"ChartboostMediationBannerViewDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationBannerViewDelegate","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerViewDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate\/didClick(bannerView:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate\/didRecordImpression(bannerView:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate\/willAppear(bannerView:)"]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView":{"role":"symbol","title":"ChartboostMediationBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerView"}],"abstract":[{"type":"text","text":"A view that can load and display a Chartboost Mediation banner ad."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerView"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerViewDelegate":{"role":"symbol","title":"ChartboostMediationBannerViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerViewDelegate"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView"},{"type":"text","text":" delegate that receives ad callbacks."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerViewDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerviewdelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerViewDelegate/didClick(bannerView:)":{"role":"symbol","title":"didClick(bannerView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationBannerView","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationBannerView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the ad is clicked by the user."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate\/didClick(bannerView:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerviewdelegate\/didclick(bannerview:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerViewDelegate/willAppear(bannerView:)":{"role":"symbol","title":"willAppear(bannerView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willAppear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationBannerView","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationBannerView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a banner ad is about to appear in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate\/willAppear(bannerView:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerviewdelegate\/willappear(bannerview:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerViewDelegate/didRecordImpression(bannerView:)":{"role":"symbol","title":"didRecordImpression(bannerView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationBannerView","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationBannerView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when Chartboost Mediation records an impression as result of the ad being shown."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate\/didRecordImpression(bannerView:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerviewdelegate\/didrecordimpression(bannerview:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerViewDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}