{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerLoadResult"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationbannerloadresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationbannerloadresult"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationAdLoadResult"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerLoadResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The result of a banner load operation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerLoadResult"}],"title":"ChartboostMediationBannerLoadResult","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationBannerLoadResult","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerLoadResult"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerLoadResult\/size"]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationAdLoadResult":{"role":"symbol","title":"ChartboostMediationAdLoadResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationAdLoadResult"}],"abstract":[{"type":"text","text":"A result returned by Chartboost Mediation at the end of an ad load operation."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationAdLoadResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationAdLoadResult"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationadloadresult"},"doc://org.cocoapods.ChartboostMediationSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerLoadResult/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationBannerSize"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The size of the loaded ad, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" in the case of load error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerLoadResult\/size","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerloadresult\/size"},"doc://org.cocoapods.ChartboostMediationSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerLoadResult":{"role":"symbol","title":"ChartboostMediationBannerLoadResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerLoadResult"}],"abstract":[{"type":"text","text":"The result of a banner load operation."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerLoadResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerLoadResult"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerloadresult"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":[],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerLoadResult"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationAdLoadResult","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationAdLoadResult","text":"ChartboostMediationAdLoadResult"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}