{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(CBMError) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChartboostMediationError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You may print a "},{"type":"codeVoice","code":"ChartboostMediationError"},{"type":"text","text":" directly on the console to read the information it contains, or you may read the value"},{"type":"text","text":" "},{"text":"of standard ","type":"text"},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" properties, like "},{"type":"codeVoice","code":"localizedDescription"},{"type":"text","text":", "},{"type":"codeVoice","code":"localizedRecoveryOptions"},{"type":"text","text":", "},{"type":"codeVoice","code":"localizedRecoverySuggestion"},{"type":"text","text":", and"},{"text":" ","type":"text"},{"code":"localizedFailureReason","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSError"],"type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSCoding","doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSCopying","doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSSecureCoding","doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s5ErrorP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s8SendableP"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationerror"]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationerror"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Error type passed by the Chartboost Mediation SDK in its public delegate methods to provide context relative to the failure of a","type":"text"},{"type":"text","text":" "},{"text":"certain operation.","type":"text"}],"metadata":{"title":"ChartboostMediationError","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMError","modules":[{"name":"ChartboostMediationSDK"}],"roleHeading":"Class","navigatorTitle":[{"text":"ChartboostMediationError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChartboostMediationError"}],"symbolKind":"class","role":"symbol"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/chartboostMediationCode","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/localizedDescription"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code"]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/localizedDescription":{"title":"localizedDescription","abstract":[{"type":"text","text":"A human readable, localized description of this error."}],"navigatorTitle":[{"text":"localizedDescription","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/localizedDescription","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/localizeddescription","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Chartboost Mediation SDK error codes."}],"title":"ChartboostMediationError.Code","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"},"doc://org.cocoapods.ChartboostMediationSDK/objc(cs)NSError":{"title":"NSError","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSError"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSCopying"},"doc://org.cocoapods.ChartboostMediationSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError":{"navigatorTitle":[{"text":"ChartboostMediationError","kind":"identifier"}],"abstract":[{"text":"Error type passed by the Chartboost Mediation SDK in its public delegate methods to provide context relative to the failure of a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"certain operation."}],"title":"ChartboostMediationError","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChartboostMediationError"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSSecureCoding":{"title":"Foundation.NSSecureCoding","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSSecureCoding","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"kind":"symbol","type":"topic","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}]},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSCoding","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/s5ErrorP":{"title":"Swift.Error","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s5ErrorP","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/chartboostMediationCode":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chartboostMediationCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22ChartboostMediationSDK0aB5ErrorC4CodeO","kind":"typeIdentifier","text":"Code"}],"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/chartboostmediationcode","title":"chartboostMediationCode","navigatorTitle":[{"text":"chartboostMediationCode","kind":"identifier"}],"abstract":[{"type":"text","text":"The underlying "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code","type":"reference"},{"text":" for this error.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/chartboostMediationCode"},"doc://org.cocoapods.ChartboostMediationSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"CBMError"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"CBMError","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CBMError"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/chartboostMediationCode","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/localizedDescription"],"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSError"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMError"},{"text":" : ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError~1localizedDescription\/title","op":"replace","value":"localizedDescription"},{"op":"replace","value":[{"text":"localizedDescription","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError~1localizedDescription\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/title","value":"CBMError"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/fragments","value":[{"kind":"identifier","text":"CBMError"}]},{"value":"chartboostMediationCode","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError~1chartboostMediationCode\/title","op":"replace"},{"value":[{"text":"chartboostMediationCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError~1chartboostMediationCode\/fragments","op":"replace"}]}]}