{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Callbacks for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"}],"title":"CHBHeliumRewardedAdDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumRewardedAdDelegate","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAd(withPlacementName:didClickWithError:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAd(withPlacementName:didCloseWithError:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAd(withPlacementName:didShowWithError:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAd(withPlacementName:requestIdentifier:winningBidInfo:didLoadWithError:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAdDidGetReward(withPlacementName:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAdDidRecordImpression(withPlacementName:)"]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumRewardedAdDelegate/heliumRewardedAd(withPlacementName:didCloseWithError:)":{"role":"symbol","title":"heliumRewardedAd(withPlacementName:didCloseWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumRewardedAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCloseWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Ad finished closing with an optional error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAd(withPlacementName:didCloseWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate\/heliumrewardedad(withplacementname:didclosewitherror:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumRewardedAdDelegate/heliumRewardedAd(withPlacementName:didClickWithError:)":{"role":"symbol","title":"heliumRewardedAd(withPlacementName:didClickWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumRewardedAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClickWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Ad click event with an optional error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAd(withPlacementName:didClickWithError:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate\/heliumrewardedad(withplacementname:didclickwitherror:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumRewardedAdDelegate/heliumRewardedAd(withPlacementName:requestIdentifier:winningBidInfo:didLoadWithError:)":{"role":"symbol","title":"heliumRewardedAd(withPlacementName:requestIdentifier:winningBidInfo:didLoadWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumRewardedAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requestIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"winningBidInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"didLoadWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Ad finished loading with an optional error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAd(withPlacementName:requestIdentifier:winningBidInfo:didLoadWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate\/heliumrewardedad(withplacementname:requestidentifier:winningbidinfo:didloadwitherror:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumRewardedAdDelegate/heliumRewardedAdDidGetReward(withPlacementName:)":{"role":"symbol","title":"heliumRewardedAdDidGetReward(withPlacementName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumRewardedAdDidGetReward"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Ad finished playing allowing the user to earn a reward."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAdDidGetReward(withPlacementName:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate\/heliumrewardedaddidgetreward(withplacementname:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumRewardedAd":{"role":"symbol","title":"HeliumRewardedAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumRewardedAd"}],"abstract":[{"type":"text","text":"Helium rewarded ad."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumRewardedAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliumrewardedad"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumRewardedAdDelegate":{"role":"symbol","title":"CHBHeliumRewardedAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"}],"abstract":[{"type":"text","text":"Callbacks for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumRewardedAdDelegate/heliumRewardedAd(withPlacementName:didShowWithError:)":{"role":"symbol","title":"heliumRewardedAd(withPlacementName:didShowWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumRewardedAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didShowWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Ad finished showing with an optional error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAd(withPlacementName:didShowWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate\/heliumrewardedad(withplacementname:didshowwitherror:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumRewardedAdDelegate/heliumRewardedAdDidRecordImpression(withPlacementName:)":{"role":"symbol","title":"heliumRewardedAdDidRecordImpression(withPlacementName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumRewardedAdDidRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Ad impression recorded by Helium as result of an ad being shown."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAdDidRecordImpression(withPlacementName:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate\/heliumrewardedaddidrecordimpression(withplacementname:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}