{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumInterstitialAdDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chbheliuminterstitialaddelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chbheliuminterstitialaddelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Callbacks for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumInterstitialAdDelegate"}],"title":"CHBHeliumInterstitialAdDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumInterstitialAdDelegate","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBHeliumInterstitialAdDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAd(withPlacementName:didClickWithError:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAd(withPlacementName:didCloseWithError:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAd(withPlacementName:didShowWithError:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAd(withPlacementName:requestIdentifier:winningBidInfo:didLoadWithError:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAdDidRecordImpression(withPlacementName:)"]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumInterstitialAdDelegate/heliumInterstitialAd(withPlacementName:requestIdentifier:winningBidInfo:didLoadWithError:)":{"role":"symbol","title":"heliumInterstitialAd(withPlacementName:requestIdentifier:winningBidInfo:didLoadWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumInterstitialAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requestIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"winningBidInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"didLoadWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Ad finished loading with an optional error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAd(withPlacementName:requestIdentifier:winningBidInfo:didLoadWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliuminterstitialaddelegate\/heliuminterstitialad(withplacementname:requestidentifier:winningbidinfo:didloadwitherror:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumInterstitialAdDelegate/heliumInterstitialAd(withPlacementName:didCloseWithError:)":{"role":"symbol","title":"heliumInterstitialAd(withPlacementName:didCloseWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumInterstitialAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCloseWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Ad finished closing with an optional error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAd(withPlacementName:didCloseWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliuminterstitialaddelegate\/heliuminterstitialad(withplacementname:didclosewitherror:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumInterstitialAdDelegate/heliumInterstitialAd(withPlacementName:didShowWithError:)":{"role":"symbol","title":"heliumInterstitialAd(withPlacementName:didShowWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumInterstitialAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didShowWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Ad finished showing with an optional error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAd(withPlacementName:didShowWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliuminterstitialaddelegate\/heliuminterstitialad(withplacementname:didshowwitherror:)"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumInterstitialAdDelegate":{"role":"symbol","title":"CHBHeliumInterstitialAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumInterstitialAdDelegate"}],"abstract":[{"type":"text","text":"Callbacks for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBHeliumInterstitialAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/chbheliuminterstitialaddelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumInterstitialAdDelegate/heliumInterstitialAd(withPlacementName:didClickWithError:)":{"role":"symbol","title":"heliumInterstitialAd(withPlacementName:didClickWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumInterstitialAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClickWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Ad click event with an optional error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAd(withPlacementName:didClickWithError:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliuminterstitialaddelegate\/heliuminterstitialad(withplacementname:didclickwitherror:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInterstitialAd":{"role":"symbol","title":"HeliumInterstitialAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInterstitialAd"}],"abstract":[{"type":"text","text":"Helium interstitial ad."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumInterstitialAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminterstitialad"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumInterstitialAdDelegate/heliumInterstitialAdDidRecordImpression(withPlacementName:)":{"role":"symbol","title":"heliumInterstitialAdDidRecordImpression(withPlacementName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumInterstitialAdDidRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Ad impression recorded by Helium as result of an ad being shown."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAdDidRecordImpression(withPlacementName:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliuminterstitialaddelegate\/heliuminterstitialaddidrecordimpression(withplacementname:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumInterstitialAdDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}