{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"A result returned by Chartboost Mediation at the end of a fullscreen ad load operation.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadloadresult"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadloadresult"]}],"metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadResult","roleHeading":"Class","symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FullscreenAdLoadResult","kind":"identifier"}],"title":"FullscreenAdLoadResult","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenAdLoadResult"}]},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"],"anchor":"Fullscreen-Ads","generated":true,"title":"Fullscreen Ads"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(CBMFullscreenAdLoadResult) "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAdLoadResult"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult"]},{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"sections":[],"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult\/ad"],"title":"Instance Properties"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol for getting notified about "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","isActive":true},{"type":"text","text":" events."}],"title":"FullscreenAdQueueDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdQueueDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"abstract":[{"text":"Manages the pre-loading of fullscreen ads. Each ","type":"text"},{"type":"codeVoice","code":"FullscreenAdQueue"},{"text":" manages ads for one placement.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","role":"symbol","title":"FullscreenAdQueue","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdQueue"}],"navigatorTitle":[{"text":"FullscreenAdQueue","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadResult/ad":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult\/ad","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ad","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd"},{"text":"?","kind":"text"}],"type":"topic","title":"ad","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadresult\/ad","kind":"symbol","abstract":[{"type":"text","text":"The loaded ad if the load was successful, "},{"type":"codeVoice","code":"nil"},{"text":" otherwise.","type":"text"}],"navigatorTitle":[{"text":"ad","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAdLoadResult"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenAdLoadResult"}],"role":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadresult","title":"FullscreenAdLoadResult","kind":"symbol","abstract":[{"type":"text","text":"A result returned by Chartboost Mediation at the end of a fullscreen ad load operation."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdLoadResult":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdLoadResult"}],"abstract":[{"type":"text","text":"A result returned by Chartboost Mediation at the end of an ad load operation."}],"type":"topic","kind":"symbol","title":"AdLoadResult","role":"symbol","navigatorTitle":[{"text":"AdLoadResult","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/adloadresult"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadRequest":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenAdLoadRequest"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","abstract":[{"type":"text","text":"A request used to load a Chartboost Mediation fullscreen ad."}],"title":"FullscreenAdLoadRequest","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadrequest","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenAdLoadRequest","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdShowResult":{"navigatorTitle":[{"kind":"identifier","text":"AdShowResult"}],"abstract":[{"type":"text","text":"A result returned by Chartboost Mediation at the end of an ad show operation."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdShowResult","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/adshowresult","title":"AdShowResult"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate":{"navigatorTitle":[{"text":"FullscreenAdDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenAdDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","title":"FullscreenAdDelegate","url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate","kind":"symbol","type":"topic","abstract":[{"text":"A ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"},{"type":"text","text":" delegate that receives ad callbacks."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"title":"FullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenAd","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenAd"}],"type":"topic","abstract":[{"text":"A Chartboost Mediation fullscreen ad ready to be shown.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"CBMFullscreenAdLoadResult"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdLoadResult"}],"op":"replace"},{"value":[{"kind":"identifier","text":"CBMFullscreenAdLoadResult"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult\/ad"],"title":"Instance Properties"}],"path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult"]}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"],"anchor":"Fullscreen-Ads","generated":true,"title":"Fullscreen Ads"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBMFullscreenAdLoadResult","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdLoadResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdLoadResult","text":"CBMAdLoadResult"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/title","value":"CBMFullscreenAdQueueDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/fragments","op":"replace","value":[{"text":"CBMFullscreenAdQueueDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/navigatorTitle","op":"replace","value":[{"text":"CBMFullscreenAdQueueDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title","value":"CBMFullscreenAdQueue","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAdQueue"}]},{"value":[{"kind":"identifier","text":"CBMFullscreenAdQueue"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult~1ad\/title","value":"ad","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ad"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult~1ad\/fragments"},{"value":"CBMFullscreenAdLoadResult","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/fragments","value":[{"text":"CBMFullscreenAdLoadResult","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"CBMFullscreenAdLoadResult"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadResult\/title","value":"CBMAdLoadResult"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadResult\/fragments","value":[{"kind":"identifier","text":"CBMAdLoadResult"}]},{"value":[{"text":"CBMAdLoadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdLoadResult\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/title","value":"CBMFullscreenAdLoadRequest"},{"op":"replace","value":[{"text":"CBMFullscreenAdLoadRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/fragments"},{"value":[{"kind":"identifier","text":"CBMFullscreenAdLoadRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/navigatorTitle"},{"value":"CBMAdShowResult","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/fragments","value":[{"kind":"identifier","text":"CBMAdShowResult"}]},{"value":[{"text":"CBMAdShowResult","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/navigatorTitle","op":"replace"},{"value":"CBMFullscreenAdDelegate","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/navigatorTitle","op":"replace","value":[{"text":"CBMFullscreenAdDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title","op":"replace","value":"CBMFullscreenAd"},{"value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments"},{"value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/navigatorTitle","op":"replace"}]}]}