{"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Delegate protocol for getting notified about "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"},{"type":"text","text":" events."}],"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate\/fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate\/fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"],"title":"Fullscreen Ads"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBMFullscreenAdQueueDelegate) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"FullscreenAdQueueDelegate","externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdQueueDelegate","role":"symbol","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdQueueDelegate"}],"navigatorTitle":[{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadRequest":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAdLoadRequest"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadrequest","navigatorTitle":[{"text":"FullscreenAdLoadRequest","kind":"identifier"}],"title":"FullscreenAdLoadRequest","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"A request used to load a Chartboost Mediation fullscreen ad.","type":"text"}]},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","type":"link","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","titleInlineContent":[{"text":"Chartboost Developers","type":"text"}],"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdShowResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdShowResult"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","url":"\/documentation\/chartboostmediationsdk\/adshowresult","navigatorTitle":[{"kind":"identifier","text":"AdShowResult"}],"title":"AdShowResult","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"A result returned by Chartboost Mediation at the end of an ad show operation.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate/fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)":{"required":true,"title":"fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullscreenAdQueue"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","text":"FullscreenAdQueue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishLoadingWithResult","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdLoadResult","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdLoadResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"numberOfAdsReady","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"fullscreenAdQueue:didFinishLoadingWithResult:numberOfAdsReady:","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate\/fullscreenadqueue(_:didfinishloadingwithresult:numberofadsready:)","role":"symbol","type":"topic","abstract":[{"text":"This delegate method is called when a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"},{"text":" completes a load request","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate\/fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"url":"\/documentation\/chartboostmediationsdk\/fullscreenad","navigatorTitle":[{"kind":"identifier","text":"FullscreenAd"}],"type":"topic","title":"FullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","abstract":[{"type":"text","text":"A Chartboost Mediation fullscreen ad ready to be shown."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FullscreenAd","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"title":"FullscreenAdQueue","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdQueue"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenAdQueue","kind":"identifier"}],"abstract":[{"type":"text","text":"Manages the pre-loading of fullscreen ads. Each "},{"code":"FullscreenAdQueue","type":"codeVoice"},{"text":" manages ads for one placement.","type":"text"}],"type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenAdLoadResult","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadresult","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdLoadResult"}],"title":"FullscreenAdLoadResult","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"A result returned by Chartboost Mediation at the end of a fullscreen ad load operation.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate/fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)":{"abstract":[{"text":"This delegate method is called when an ad expires and is removed from the queue","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate\/fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate\/fullscreenadqueuedidremoveexpiredad(_:numberofadsready:)","title":"fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenAdQueueDidRemoveExpiredAd","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","text":"FullscreenAdQueue","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"numberOfAdsReady","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"fullscreenAdQueueDidRemoveExpiredAd:numberOfAdsReady:","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate":{"title":"FullscreenAdQueueDelegate","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdQueueDelegate"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate protocol for getting notified about ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","isActive":true,"type":"reference"},{"type":"text","text":" events."}],"type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdDelegate"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate","navigatorTitle":[{"text":"FullscreenAdDelegate","kind":"identifier"}],"title":"FullscreenAdDelegate","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","isActive":true,"type":"reference"},{"text":" delegate that receives ad callbacks.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"CBMFullscreenAdQueueDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAdQueueDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CBMFullscreenAdQueueDelegate"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate\/fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate\/fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)"]}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Fullscreen Ads","generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"]}]},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMFullscreenAdQueueDelegate","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CBMFullscreenAdLoadRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/title"},{"value":[{"kind":"identifier","text":"CBMFullscreenAdLoadRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/fragments","op":"replace"},{"value":"CBMAdShowResult","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/fragments","value":[{"kind":"identifier","text":"CBMAdShowResult"}],"op":"replace"},{"value":"fullscreenAdQueue:didFinishLoadingWithResult:numberOfAdsReady:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate~1fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate~1fullscreenAdQueue(_:didFinishLoadingWithResult:numberOfAdsReady:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fullscreenAdQueue:didFinishLoadingWithResult:numberOfAdsReady:","kind":"identifier"}]},{"op":"replace","value":"CBMFullscreenAd","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title"},{"value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","op":"replace"},{"op":"replace","value":"CBMFullscreenAdQueue","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments","value":[{"text":"CBMFullscreenAdQueue","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/title","value":"CBMFullscreenAdLoadResult"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/fragments","value":[{"text":"CBMFullscreenAdLoadResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate~1fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)\/title","op":"replace","value":"fullscreenAdQueueDidRemoveExpiredAd:numberOfAdsReady:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate~1fullscreenAdQueueDidRemoveExpiredAd(_:numberOfAdsReady:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"fullscreenAdQueueDidRemoveExpiredAd:numberOfAdsReady:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/title","value":"CBMFullscreenAdQueueDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/fragments","value":[{"text":"CBMFullscreenAdQueueDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/title","value":"CBMFullscreenAdDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"CBMFullscreenAdDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/fragments","op":"replace"}]}]}