{"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/customData","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/delegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/loadID","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/request","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/winningBidInfo"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/invalidate()","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/show(with:completion:)"],"generated":true},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/load(with:completion:)"],"title":"Type Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenad"]},{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenad"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A Chartboost Mediation fullscreen ad ready to be shown."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(CBMFullscreenAd) "},{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAd"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to load a fullscreen ad use the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/load(with:completion:)"},{"text":" static method.","type":"text"}]}],"kind":"content"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"],"kind":"relationships"}],"sections":[],"metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAd"}],"navigatorTitle":[{"text":"FullscreenAd","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"ChartboostMediationSDK"}],"symbolKind":"class","role":"symbol","title":"FullscreenAd"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"seeAlsoSections":[{"title":"Fullscreen Ads","anchor":"Fullscreen-Ads","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"],"generated":true}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/customData":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"customData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Optional custom data that will be sent on every rewarded callback."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/customData","url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/customdata","navigatorTitle":[{"text":"customData","kind":"identifier"}],"title":"customData","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadRequest":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenAdLoadRequest"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","abstract":[{"type":"text","text":"A request used to load a Chartboost Mediation fullscreen ad."}],"title":"FullscreenAdLoadRequest","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadrequest","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenAdLoadRequest","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdShowResult":{"navigatorTitle":[{"kind":"identifier","text":"AdShowResult"}],"abstract":[{"type":"text","text":"A result returned by Chartboost Mediation at the end of an ad show operation."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdShowResult","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/adshowresult","title":"AdShowResult"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/request":{"abstract":[{"text":"The request that resulted in this ad getting loaded.","type":"text"}],"title":"request","type":"topic","navigatorTitle":[{"text":"request","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/request","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/request","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"request"},{"text":": ","kind":"text"},{"text":"FullscreenAdLoadRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadRequest"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"title":"FullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenAd","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenAd"}],"type":"topic","abstract":[{"text":"A Chartboost Mediation fullscreen ad ready to be shown.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAdLoadResult"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenAdLoadResult"}],"role":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadresult","title":"FullscreenAdLoadResult","kind":"symbol","abstract":[{"type":"text","text":"A result returned by Chartboost Mediation at the end of a fullscreen ad load operation."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/invalidate()":{"title":"invalidate()","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/invalidate()","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/invalidate()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidate","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"invalidate","kind":"identifier"}],"abstract":[{"text":"Invalidates the ad so it gets discarded by Chartboost Mediation’s internal cache.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol for getting notified about "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","isActive":true},{"type":"text","text":" events."}],"title":"FullscreenAdQueueDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdQueueDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/loadID":{"role":"symbol","abstract":[{"type":"text","text":"A unique identifier for the load request."}],"type":"topic","title":"loadID","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"loadID","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/loadID","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/loadid"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"abstract":[{"text":"Manages the pre-loading of fullscreen ads. Each ","type":"text"},{"type":"codeVoice","code":"FullscreenAdQueue"},{"text":" manages ads for one placement.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","role":"symbol","title":"FullscreenAdQueue","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdQueue"}],"navigatorTitle":[{"text":"FullscreenAdQueue","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate":{"navigatorTitle":[{"text":"FullscreenAdDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenAdDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","title":"FullscreenAdDelegate","url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate","kind":"symbol","type":"topic","abstract":[{"text":"A ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"},{"type":"text","text":" delegate that receives ad callbacks."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/delegate":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/delegate","title":"delegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate","text":"FullscreenAdDelegate"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"The delegate to receive ad callbacks."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/delegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/winningBidInfo":{"type":"topic","abstract":[{"text":"Information about the bid that won the auction.","type":"text"}],"title":"winningBidInfo","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/winningbidinfo","navigatorTitle":[{"kind":"identifier","text":"winningBidInfo"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"winningBidInfo"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/winningBidInfo"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/show(with:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/show(with:completion:)","kind":"symbol","navigatorTitle":[{"text":"showWith:completion:","kind":"identifier"}],"abstract":[{"text":"Shows the ad on the specified view controller.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/show(with:completion:)","title":"show(with:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"show"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdShowResult","text":"AdShowResult"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ChartboostMediationSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/load(with:completion:)":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadRequest","kind":"typeIdentifier","text":"FullscreenAdLoadRequest"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadResult","text":"FullscreenAdLoadResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"loadWith:completion:"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/load(with:completion:)","role":"symbol","abstract":[{"type":"text","text":"Loads a Chartboost Mediation fullscreen ad using the information provided in the request."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/load(with:completion:)","title":"load(with:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CBMFullscreenAd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/customData","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/delegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/loadID","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/request","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/winningBidInfo"]},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/invalidate()","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/show(with:completion:)"],"title":"Instance Methods"},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/load(with:completion:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"],"anchor":"Fullscreen-Ads","title":"Fullscreen Ads","generated":true}]},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"CBMFullscreenAd","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1customData\/title","op":"replace","value":"customData"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1customData\/fragments","value":[{"kind":"identifier","text":"customData"}],"op":"replace"},{"value":"CBMFullscreenAdLoadRequest","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/fragments","value":[{"text":"CBMFullscreenAdLoadRequest","kind":"identifier"}]},{"value":[{"text":"CBMFullscreenAdLoadRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/navigatorTitle","op":"replace"},{"value":"CBMAdShowResult","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/title","op":"replace"},{"op":"replace","value":[{"text":"CBMAdShowResult","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/navigatorTitle","value":[{"text":"CBMAdShowResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1request\/title","value":"request","op":"replace"},{"value":[{"kind":"identifier","text":"request"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1request\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title","op":"replace","value":"CBMFullscreenAd"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAd"}],"op":"replace"},{"value":[{"kind":"identifier","text":"CBMFullscreenAd"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/navigatorTitle","op":"replace"},{"value":"CBMFullscreenAdLoadResult","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/fragments","value":[{"text":"CBMFullscreenAdLoadResult","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAdLoadResult"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1invalidate()\/title","value":"invalidate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1invalidate()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"invalidate","kind":"identifier"}]},{"value":"CBMFullscreenAdQueueDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/title"},{"op":"replace","value":[{"text":"CBMFullscreenAdQueueDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/navigatorTitle","value":[{"text":"CBMFullscreenAdQueueDelegate","kind":"identifier"}],"op":"replace"},{"value":"loadID","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1loadID\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1loadID\/fragments","value":[{"text":"loadID","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title","op":"replace","value":"CBMFullscreenAdQueue"},{"value":[{"text":"CBMFullscreenAdQueue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments"},{"value":[{"kind":"identifier","text":"CBMFullscreenAdQueue"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/navigatorTitle","op":"replace"},{"op":"replace","value":"CBMFullscreenAdDelegate","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAdDelegate"}]},{"value":[{"text":"CBMFullscreenAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1delegate\/title","value":"delegate"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1delegate\/fragments"},{"value":"winningBidInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1winningBidInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1winningBidInfo\/fragments","value":[{"text":"winningBidInfo","kind":"identifier"}]},{"op":"replace","value":"showWith:completion:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1show(with:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1show(with:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showWith:completion:"}]},{"op":"replace","value":"loadWith:completion:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1load(with:completion:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"loadWith:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1load(with:completion:)\/fragments"}]}]}