{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(CBMFullscreenAdDelegate) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenAdDelegate","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"seeAlsoSections":[{"title":"Fullscreen Ads","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"],"generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didClick(ad:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didClose(ad:error:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didExpire(ad:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didRecordImpression(ad:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didReward(ad:)"],"title":"Instance Methods"}],"metadata":{"role":"symbol","externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdDelegate"}],"roleHeading":"Protocol","title":"FullscreenAdDelegate","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenAdDelegate","kind":"identifier"}],"modules":[{"name":"ChartboostMediationSDK"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenaddelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenaddelegate"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"A ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","type":"reference","isActive":true},{"text":" delegate that receives ad callbacks.","type":"text"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdDelegate"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate","navigatorTitle":[{"text":"FullscreenAdDelegate","kind":"identifier"}],"title":"FullscreenAdDelegate","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","isActive":true,"type":"reference"},{"text":" delegate that receives ad callbacks.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadRequest":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAdLoadRequest"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadrequest","navigatorTitle":[{"text":"FullscreenAdLoadRequest","kind":"identifier"}],"title":"FullscreenAdLoadRequest","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"A request used to load a Chartboost Mediation fullscreen ad.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenAdLoadResult","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadresult","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdLoadResult"}],"title":"FullscreenAdLoadResult","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"A result returned by Chartboost Mediation at the end of a fullscreen ad load operation.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate/didClick(ad:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didClick","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ad"},{"text":": ","kind":"text"},{"text":"FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"didClick(ad:)","kind":"symbol","navigatorTitle":[{"text":"didClickWithAd:","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate\/didclick(ad:)","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didClick(ad:)","abstract":[{"text":"Called when the ad is clicked by the user.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdShowResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdShowResult"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","url":"\/documentation\/chartboostmediationsdk\/adshowresult","navigatorTitle":[{"kind":"identifier","text":"AdShowResult"}],"title":"AdShowResult","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"A result returned by Chartboost Mediation at the end of an ad show operation.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate/didReward(ad:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didReward(ad:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"didRewardWithAd:"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate\/didreward(ad:)","required":true,"title":"didReward(ad:)","abstract":[{"type":"text","text":"Called when the ad finished playing, allowing the user to earn a reward."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReward"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","kind":"typeIdentifier","text":"FullscreenAd"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate/didExpire(ad:)":{"role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate\/didexpire(ad:)","required":true,"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didExpire(ad:)","abstract":[{"type":"text","text":"Called when the ad expired."}],"title":"didExpire(ad:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didExpire","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"text":"FullscreenAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"didExpireWithAd:"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"url":"\/documentation\/chartboostmediationsdk\/fullscreenad","navigatorTitle":[{"kind":"identifier","text":"FullscreenAd"}],"type":"topic","title":"FullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","abstract":[{"type":"text","text":"A Chartboost Mediation fullscreen ad ready to be shown."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FullscreenAd","kind":"identifier"}]},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","type":"link","titleInlineContent":[{"text":"Chartboost Developers","type":"text"}],"url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","title":"Chartboost Developers"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"title":"FullscreenAdQueue","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdQueue"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenAdQueue","kind":"identifier"}],"abstract":[{"type":"text","text":"Manages the pre-loading of fullscreen ads. Each "},{"code":"FullscreenAdQueue","type":"codeVoice"},{"text":" manages ads for one placement.","type":"text"}],"type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate/didClose(ad:error:)":{"title":"didClose(ad:error:)","abstract":[{"type":"text","text":"Called when the ad is closed and no longer visible."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didClose","kind":"identifier"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","text":"FullscreenAd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didCloseWithAd:error:"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didClose(ad:error:)","url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate\/didclose(ad:error:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate":{"title":"FullscreenAdQueueDelegate","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdQueueDelegate"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate protocol for getting notified about ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","isActive":true,"type":"reference"},{"type":"text","text":" events."}],"type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate/didRecordImpression(ad:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecordImpression"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","text":"FullscreenAd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"didRecordImpression(ad:)","navigatorTitle":[{"kind":"identifier","text":"didRecordImpressionWithAd:"}],"type":"topic","abstract":[{"text":"Called when Chartboost Mediation records an impression as result of the ad being shown.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didRecordImpression(ad:)","required":true,"url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate\/didrecordimpression(ad:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","value":"CBMFullscreenAdDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAdDelegate"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"CBMFullscreenAdDelegate","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didClick(ad:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didClose(ad:error:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didExpire(ad:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didRecordImpression(ad:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didReward(ad:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"title":"Fullscreen Ads","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"],"generated":true}],"op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"CBMFullscreenAdDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/title","op":"replace","value":"CBMFullscreenAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/title","value":"CBMFullscreenAdLoadRequest"},{"value":[{"text":"CBMFullscreenAdLoadRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/title","value":"CBMFullscreenAdLoadResult"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAdLoadResult"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didClick(ad:)\/title","op":"replace","value":"didClickWithAd:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didClick(ad:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didClickWithAd:"}]},{"value":"CBMAdShowResult","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/fragments","value":[{"text":"CBMAdShowResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didReward(ad:)\/title","value":"didRewardWithAd:"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didReward(ad:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didRewardWithAd:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didExpire(ad:)\/title","value":"didExpireWithAd:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didExpireWithAd:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didExpire(ad:)\/fragments","op":"replace"},{"op":"replace","value":"CBMFullscreenAd","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAd"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title","value":"CBMFullscreenAdQueue","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdQueue"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didClose(ad:error:)\/title","value":"didCloseWithAd:error:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didClose(ad:error:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didCloseWithAd:error:"}],"op":"replace"},{"value":"CBMFullscreenAdQueueDelegate","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/fragments","value":[{"text":"CBMFullscreenAdQueueDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didRecordImpression(ad:)\/title","value":"didRecordImpressionWithAd:"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didRecordImpression(ad:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didRecordImpressionWithAd:","kind":"identifier"}]}]}]}