{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/helium"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/helium"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"title":"Helium","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChartboostMediationSDK@objc(cs)Helium","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Helium"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/discardOversizedAds","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/initializedAdapterInfo","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/logLevel","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/partnerConsents","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/userIdentifier"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/attachLogHandler(_:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/bannerProvider(with:andPlacementName:andSize:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/detachLogHandler(_:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/interstitialAdProvider(with:andPlacementName:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/loadFullscreenAd(with:completion:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/rewardedAdProvider(with:andPlacementName:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/setCCPAConsent(_:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/setGameEngineName(_:version:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/setSubjectToCoppa(_:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/setSubjectToGDPR(_:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/setUserHasGivenConsent(_:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/start(withAppId:andAppSignature:options:delegate:)","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/start(withAppId:options:delegate:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/sdkVersion"]},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/shared()"]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/discardOversizedAds":{"role":"symbol","title":"discardOversizedAds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discardOversizedAds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Boolean value indicating that ads returned from adapters that are larger than the requested size should be discarded."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/discardOversizedAds","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/discardoversizedads"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/setSubjectToGDPR(_:)":{"role":"symbol","title":"setSubjectToGDPR(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSubjectToGDPR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Indicates that the user is subject to GDPR."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/setSubjectToGDPR(_:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/setsubjecttogdpr(_:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/initializedAdapterInfo":{"role":"symbol","title":"initializedAdapterInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializedAdapterInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HeliumAdapterInfo","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumAdapterInfo"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"An array of all initialized adapters, or an empty array if the SDK is not initialized."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/initializedAdapterInfo","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/initializedadapterinfo"},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/partnerConsents":{"role":"symbol","title":"partnerConsents","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerConsents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PartnerIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK17PartnerIdentifiera"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Allows to set user consent for a specific partner."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/partnerConsents","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/partnerconsents"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/rewardedAdProvider(with:andPlacementName:)":{"role":"symbol","title":"rewardedAdProvider(with:andPlacementName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBHeliumRewardedAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumRewardedAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeliumRewardedAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumRewardedAd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Factory method to create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd"},{"type":"text","text":" which will be used to load and show rewarded ads."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/rewardedAdProvider(with:andPlacementName:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/chartboostmediationsdk\/helium\/rewardedadprovider(with:andplacementname:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/start(withAppId:andAppSignature:options:delegate:)":{"role":"symbol","title":"start(withAppId:andAppSignature:options:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andAppSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumInitializationOptions","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumInitializationOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumSdkDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumSdkDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Deprecated."},{"type":"text","text":" "},{"type":"text","text":"Initializes the Helium SDK."},{"type":"text","text":" "},{"type":"text","text":"This method must be called before ads can be served."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/start(withAppId:andAppSignature:options:delegate:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/chartboostmediationsdk\/helium\/start(withappid:andappsignature:options:delegate:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium":{"role":"symbol","title":"Helium","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Helium"}],"url":"\/documentation\/chartboostmediationsdk\/helium"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/detachLogHandler(_:)":{"role":"symbol","title":"detachLogHandler(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachLogHandler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogHandler","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationLogHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Detatch a custom logger handler to the logging system."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/detachLogHandler(_:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/detachloghandler(_:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/sdkVersion":{"role":"symbol","title":"sdkVersion","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The Helium SDK version."},{"type":"text","text":" "},{"type":"text","text":"The value is a semantic versioning compliant string."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/sdkVersion","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/sdkversion"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/setCCPAConsent(_:)":{"role":"symbol","title":"setCCPAConsent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCCPAConsent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Indicates that the CCPA-applicable user has granted consent to the collection of Personally Identifiable Information."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/setCCPAConsent(_:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/setccpaconsent(_:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/attachLogHandler(_:)":{"role":"symbol","title":"attachLogHandler(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachLogHandler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogHandler","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationLogHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Attach a custom logger handler to the logging system."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/attachLogHandler(_:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/attachloghandler(_:)"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/shared()":{"role":"symbol","title":"shared()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Helium","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)Helium"}],"abstract":[{"type":"text","text":"Shared instance of the Helium SDK."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/shared()","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/shared()"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/setSubjectToCoppa(_:)":{"role":"symbol","title":"setSubjectToCoppa(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSubjectToCoppa"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Indicates that the user is subject to COPPA."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/setSubjectToCoppa(_:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/setsubjecttocoppa(_:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/bannerProvider(with:andPlacementName:andSize:)":{"role":"symbol","title":"bannerProvider(with:andPlacementName:andSize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumBannerAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumBannerAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBHBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CHBHBannerSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeliumBannerView","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumBannerView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Factory method to create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView"},{"type":"text","text":" which will be used to load and show banner ads."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/bannerProvider(with:andPlacementName:andSize:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/chartboostmediationsdk\/helium\/bannerprovider(with:andplacementname:andsize:)"},"doc://org.cocoapods.ChartboostMediationSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/logLevel":{"role":"symbol","title":"logLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@ChartboostMediationLogLevel"}],"abstract":[{"type":"text","text":"Set the logging level."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/logLevel","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/loglevel"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/loadFullscreenAd(with:completion:)":{"role":"symbol","title":"loadFullscreenAd(with:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadFullscreenAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationAdLoadRequest","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationAdLoadRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChartboostMediationFullscreenAdLoadResult","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationFullscreenAdLoadResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Loads a Chartboost Mediation fullscreen ad using the information provided in the request."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/loadFullscreenAd(with:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/loadfullscreenad(with:completion:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/interstitialAdProvider(with:andPlacementName:)":{"role":"symbol","title":"interstitialAdProvider(with:andPlacementName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAdProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBHeliumInterstitialAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumInterstitialAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeliumInterstitialAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumInterstitialAd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Factory method to create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd"},{"type":"text","text":" which will be used to load and show interstitial ads."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/interstitialAdProvider(with:andPlacementName:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/chartboostmediationsdk\/helium\/interstitialadprovider(with:andplacementname:)"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ"},"doc://org.cocoapods.ChartboostMediationSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/setGameEngineName(_:version:)":{"role":"symbol","title":"setGameEngineName(_:version:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setGameEngineName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Specifies to the Helium SDK the game engine environment that it is running in."},{"type":"text","text":" "},{"type":"text","text":"This method should be called before loading ads."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/setGameEngineName(_:version:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/setgameenginename(_:version:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumRewardedAd":{"role":"symbol","title":"HeliumRewardedAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumRewardedAd"}],"abstract":[{"type":"text","text":"Helium rewarded ad."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumRewardedAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliumrewardedad"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerView":{"role":"symbol","title":"HeliumBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumBannerView"}],"abstract":[{"type":"text","text":"Helium banner ad view."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumBannerView"}],"url":"\/documentation\/chartboostmediationsdk\/heliumbannerview"},"doc://org.cocoapods.ChartboostMediationSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/start(withAppId:options:delegate:)":{"role":"symbol","title":"start(withAppId:options:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumInitializationOptions","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumInitializationOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumSdkDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumSdkDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes the Helium SDK."},{"type":"text","text":" "},{"type":"text","text":"This method must be called before ads can be served."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/start(withAppId:options:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/start(withappid:options:delegate:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInterstitialAd":{"role":"symbol","title":"HeliumInterstitialAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInterstitialAd"}],"abstract":[{"type":"text","text":"Helium interstitial ad."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumInterstitialAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminterstitialad"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/setUserHasGivenConsent(_:)":{"role":"symbol","title":"setUserHasGivenConsent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserHasGivenConsent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Indicates that the GDPR-applicable user has granted consent to the collection of Personally Identifiable Information."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/setUserHasGivenConsent(_:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/setuserhasgivenconsent(_:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/userIdentifier":{"role":"symbol","title":"userIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Optional user identifier sent on every ad request."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/userIdentifier","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/useridentifier"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}