{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ChartboostMediationLogEntry) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogEntry"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For every log message emitted by the SDK, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogHandler\/handle(_:)"},{"type":"text","text":" will be called on all handlers that have been"},{"type":"text","text":" "},{"type":"text","text":"registered with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/attachLogHandler(_:)"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/logentry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/logentry"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object containing information about a single log message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogEntry"}],"title":"LogEntry","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationLogEntry","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"LogEntry"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/category","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/date","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/logLevel","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/message","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/subsystem"]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogEntry/date":{"role":"symbol","title":"date","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"date"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[{"type":"text","text":"The date that this log entry was created."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/date","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/logentry\/date"},"doc://org.cocoapods.ChartboostMediationSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogEntry/logLevel":{"role":"symbol","title":"logLevel","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@ChartboostMediationLogLevel"}],"abstract":[{"type":"text","text":"The log level for this entry."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/logLevel","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/logentry\/loglevel"},"doc://org.cocoapods.ChartboostMediationSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogEntry":{"role":"symbol","title":"LogEntry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogEntry"}],"abstract":[{"type":"text","text":"An object containing information about a single log message."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogEntry"}],"url":"\/documentation\/chartboostmediationsdk\/logentry"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogEntry/category":{"role":"symbol","title":"category","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"category"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The category for the log."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/category","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/logentry\/category"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/attachLogHandler(_:)":{"role":"symbol","title":"attachLogHandler(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachLogHandler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogHandler","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationLogHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Attach a custom logger handler to the logging system."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/attachLogHandler(_:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/attachloghandler(_:)"},"doc://org.cocoapods.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogEntry/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The message content of the log."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/message","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/logentry\/message"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogHandler/handle(_:)":{"role":"symbol","title":"handle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogEntry","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationLogEntry"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on every handler previously registered with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/attachLogHandler(_:)"},{"type":"text","text":" to handle "},{"type":"codeVoice","code":"entry"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogHandler\/handle(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/loghandler\/handle(_:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogEntry/subsystem":{"role":"symbol","title":"subsystem","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subsystem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"A subsystem for the log."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/subsystem","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/logentry\/subsystem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationLogEntry"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}