{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdPreBidRequest"}]}]}],"seeAlsoSections":[{"anchor":"Creating-Adapters","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterStorage","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormat","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerConfiguration","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerDetails","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorFactory","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorMapping","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerFullscreenAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerLogEvent"],"generated":true,"title":"Creating Adapters"}],"abstract":[{"type":"text","text":"A prebidding info request."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/partneradprebidrequest"]}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Structure","modules":[{"name":"ChartboostMediationSDK"}],"role":"symbol","externalID":"s:22ChartboostMediationSDK22PartnerAdPreBidRequestV","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdPreBidRequest"}],"navigatorTitle":[{"text":"PartnerAdPreBidRequest","kind":"identifier"}],"title":"PartnerAdPreBidRequest","symbolKind":"struct"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest\/bannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest\/format","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest\/keywords","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest\/mediationPlacement","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest\/partnerSettings"],"generated":true}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerErrorFactory":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorFactory","url":"\/documentation\/chartboostmediationsdk\/partnererrorfactory","abstract":[{"text":"Provides the capability to generate errors suitable to be passed in completion handlers for ","type":"text"},{"code":"PartnerAd","type":"codeVoice"},{"type":"text","text":" operations."},{"text":" ","type":"text"},{"text":"All functionality is provided by default implementations.","type":"text"}],"role":"symbol","title":"PartnerErrorFactory","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerErrorFactory"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerErrorFactory"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdLoadRequest":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradloadrequest","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLoadRequest","role":"symbol","kind":"symbol","abstract":[{"text":"A partner ad load request.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerAdLoadRequest"}],"title":"PartnerAdLoadRequest","navigatorTitle":[{"kind":"identifier","text":"PartnerAdLoadRequest"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerLogEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PartnerLogEvent","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partnerlogevent","kind":"symbol","type":"topic","abstract":[{"text":"List of predefined events for ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","type":"reference","isActive":true},{"type":"text","text":" types to log."}],"title":"PartnerLogEvent","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerLogEvent","navigatorTitle":[{"text":"PartnerLogEvent","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerErrorMapping":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorMapping","title":"PartnerErrorMapping","url":"\/documentation\/chartboostmediationsdk\/partnererrormapping","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PartnerErrorMapping","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PartnerErrorMapping"}],"role":"symbol","abstract":[{"text":"Methods to map a partner error code to a standard Chartboost Mediation error code.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerAd":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partnerbannerad","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerAd","role":"symbol","kind":"symbol","abstract":[{"text":"A type of ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true,"type":"reference"},{"text":" which partner banner ads should conform to.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerBannerAd"}],"title":"PartnerBannerAd","navigatorTitle":[{"kind":"identifier","text":"PartnerBannerAd"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdPreBidRequest/keywords":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"keywords","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"text":"Key-value pairs to be associated with the placement.","type":"text"}],"kind":"symbol","type":"topic","title":"keywords","url":"\/documentation\/chartboostmediationsdk\/partneradprebidrequest\/keywords","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest\/keywords"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A configuration type that contains adapter and partner info."},{"type":"text","text":" "},{"text":"It may also be used to expose custom partner SDK options to the publisher.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdapterConfiguration","kind":"identifier"}],"title":"PartnerAdapterConfiguration","navigatorTitle":[{"text":"PartnerAdapterConfiguration","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAd":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerAd","kind":"identifier"}],"type":"topic","abstract":[{"text":"A protocol to which ads created by ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","type":"reference","isActive":true},{"type":"text","text":" types conform to."},{"type":"text","text":" "},{"text":"Partner ads are in charge of communicating with a single partner SDK ad instance and reporting back ad life-cycle","type":"text"},{"type":"text","text":" "},{"type":"text","text":"events corresponding to that ad to the Chartboost Mediation SDK."},{"text":" ","type":"text"},{"text":"They also keep track of information related to a single load request.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerad","navigatorTitle":[{"kind":"identifier","text":"PartnerAd"}],"title":"PartnerAd"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdPreBidRequest/format":{"title":"format","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"format","kind":"identifier"},{"kind":"text","text":": "},{"text":"PartnerAdFormat","kind":"typeIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK15PartnerAdFormata"}],"abstract":[{"text":"Ad format.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/partneradprebidrequest\/format","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest\/format","type":"topic","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdPreBidRequest":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest","title":"PartnerAdPreBidRequest","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PartnerAdPreBidRequest","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partneradprebidrequest","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerAdPreBidRequest"}],"abstract":[{"text":"A prebidding info request.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterStorage":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterStorage","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partneradapterstorage","navigatorTitle":[{"text":"PartnerAdapterStorage","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Exposes storage managed by the Chartboost Mediation SDK to the adapter."}],"title":"PartnerAdapterStorage","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapterStorage"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdPreBidRequest/partnerSettings":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest\/partnerSettings","type":"topic","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/partneradprebidrequest\/partnersettings","abstract":[{"text":"Extra partner-specific information.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"partnerSettings"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"role":"symbol","title":"partnerSettings"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerFullscreenAd":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerFullscreenAd","title":"PartnerFullscreenAd","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerFullscreenAd"}],"url":"\/documentation\/chartboostmediationsdk\/partnerfullscreenad","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerFullscreenAd"}],"abstract":[{"type":"text","text":"A type of "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true,"type":"reference"},{"text":" which partner fullscreen ads should conform to.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdPreBidRequest/bannerSize":{"url":"\/documentation\/chartboostmediationsdk\/partneradprebidrequest\/bannersize","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"BannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest\/bannerSize","type":"topic","abstract":[{"text":"Ad size. ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for full-screen ads.","type":"text"}],"kind":"symbol","title":"bannerSize","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerConfiguration":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerConfiguration","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerconfiguration","navigatorTitle":[{"text":"PartnerConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Information used by partner adapters to set up.","type":"text"}],"title":"PartnerConfiguration","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerConfiguration","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdLogEvent":{"abstract":[{"type":"text","text":"List of predefined events for "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true},{"text":" types to log.","type":"text"}],"type":"topic","title":"PartnerAdLogEvent","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","url":"\/documentation\/chartboostmediationsdk\/partneradlogevent","navigatorTitle":[{"text":"PartnerAdLogEvent","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdLogEvent","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormat":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdFormat"}],"navigatorTitle":[{"text":"PartnerAdFormat","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradformat","title":"PartnerAdFormat","kind":"symbol","abstract":[{"type":"text","text":"Ad format."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormat"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdDelegate":{"title":"PartnerAdDelegate","abstract":[{"text":"Protocol that defines how a partner ad communicates life-cycle events back to the Chartboost Mediation SDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PartnerAdDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PartnerAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/partneraddelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormats":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats","url":"\/documentation\/chartboostmediationsdk\/partneradformats","abstract":[{"type":"text","text":"A namespace for Mediation’s "},{"code":"PartnerAdFormat","type":"codeVoice"},{"type":"text","text":" constants."}],"role":"symbol","title":"PartnerAdFormats","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerAdFormats"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerAdFormats","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapter":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","title":"PartnerAdapter","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerAdapter"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapter","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapter"}],"abstract":[{"type":"text","text":"The protocol to which all partner adapters conform to."},{"type":"text","text":" "},{"type":"text","text":"It defines how Chartboost Mediation SDK and its mediated networks communicate."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerDetails":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerDetails"}],"navigatorTitle":[{"kind":"identifier","text":"PartnerDetails"}],"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerdetails","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerDetails","title":"PartnerDetails","type":"topic","abstract":[{"text":"Extra information related to a partner event as a dictionary.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Pass an empty dictionary when there are no details to pass back to the Chartboost Mediation SDK."}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerSize":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize","url":"\/documentation\/chartboostmediationsdk\/partnerbannersize","abstract":[{"type":"text","text":"The size of a partner loaded banner ad."}],"role":"symbol","title":"PartnerBannerSize","type":"topic","kind":"symbol","navigatorTitle":[{"text":"PartnerBannerSize","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerBannerSize"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdPreBidRequest/mediationPlacement":{"title":"mediationPlacement","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"mediationPlacement","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partneradprebidrequest\/mediationplacement","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest\/mediationPlacement","abstract":[{"type":"text","text":"Chartboost Mediation’s placement identifier."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMPartnerAdapterConfiguration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/title"},{"value":[{"text":"CBMPartnerAdapterConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/navigatorTitle","value":[{"text":"CBMPartnerAdapterConfiguration","kind":"identifier"}],"op":"replace"}]}]}