{"metadata":{"role":"symbol","roleHeading":"Protocol","title":"PartnerAdapterConfiguration","modules":[{"name":"ChartboostMediationSDK"}],"symbolKind":"protocol","externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMPartnerAdapterConfiguration","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapterConfiguration"}],"navigatorTitle":[{"text":"PartnerAdapterConfiguration","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterStorage","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormat","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerConfiguration","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerDetails","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorFactory","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorMapping","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerFullscreenAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerLogEvent"],"generated":true,"title":"Creating Adapters"}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/adapterVersion","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerDisplayName","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerID","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerSDKVersion"]},{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/log(_:functionName:)"],"title":"Type Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBMPartnerAdapterConfiguration) "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdapterConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/partneradapterconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/partneradapterconfiguration"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"],"title":"Inherits From"}],"abstract":[{"type":"text","text":"A configuration type that contains adapter and partner info."},{"text":" ","type":"text"},{"text":"It may also be used to expose custom partner SDK options to the publisher.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration"},"kind":"symbol","references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormats":{"abstract":[{"type":"text","text":"A namespace for Mediation’s "},{"type":"codeVoice","code":"PartnerAdFormat"},{"text":" constants.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdFormats"}],"type":"topic","title":"PartnerAdFormats","navigatorTitle":[{"text":"PartnerAdFormats","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats","url":"\/documentation\/chartboostmediationsdk\/partneradformats","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration/partnerSDKVersion":{"url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/partnersdkversion","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerSDKVersion","abstract":[{"text":"The version of the partner SDK.","type":"text"}],"required":true,"navigatorTitle":[{"text":"partnerSDKVersion","kind":"identifier"}],"type":"topic","title":"partnerSDKVersion","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerSDKVersion"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdPreBidRequest":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest","type":"topic","abstract":[{"type":"text","text":"A prebidding info request."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerAdPreBidRequest"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdPreBidRequest"}],"title":"PartnerAdPreBidRequest","url":"\/documentation\/chartboostmediationsdk\/partneradprebidrequest"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration/adapterVersion":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/adapterVersion","abstract":[{"type":"text","text":"The version of the adapter."},{"text":" ","type":"text"},{"text":"It should have either 5 or 6 digits separated by periods, where the first digit is Chartboost Mediation SDK’s major version, the","type":"text"},{"type":"text","text":" "},{"text":"last digit is the adapter’s build version, and intermediate digits are the partner SDK’s version.","type":"text"},{"type":"text","text":" "},{"text":"Format: ","type":"text"},{"code":"<Chartboost Mediation major version>.<Partner major version>.<Partner minor version>.<Partner patch version>. <Partner build version>.<Adapter build version>","type":"codeVoice"},{"type":"text","text":" where "},{"code":".<Partner build version>","type":"codeVoice"},{"type":"text","text":" is optional."}],"url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/adapterversion","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"adapterVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"adapterVersion"}],"role":"symbol","title":"adapterVersion","type":"topic","kind":"symbol","required":true},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerConfiguration":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerConfiguration","type":"topic","abstract":[{"text":"Information used by partner adapters to set up.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PartnerConfiguration","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerConfiguration"}],"url":"\/documentation\/chartboostmediationsdk\/partnerconfiguration","title":"PartnerConfiguration"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterStorage":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterStorage","type":"topic","abstract":[{"text":"Exposes storage managed by the Chartboost Mediation SDK to the adapter.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PartnerAdapterStorage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PartnerAdapterStorage","kind":"identifier"}],"title":"PartnerAdapterStorage","url":"\/documentation\/chartboostmediationsdk\/partneradapterstorage"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAd":{"url":"\/documentation\/chartboostmediationsdk\/partnerad","navigatorTitle":[{"text":"PartnerAd","kind":"identifier"}],"type":"topic","title":"PartnerAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","abstract":[{"text":"A protocol to which ads created by ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter"},{"text":" types conform to.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Partner ads are in charge of communicating with a single partner SDK ad instance and reporting back ad life-cycle"},{"text":" ","type":"text"},{"type":"text","text":"events corresponding to that ad to the Chartboost Mediation SDK."},{"type":"text","text":" "},{"type":"text","text":"They also keep track of information related to a single load request."}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAd","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerDetails":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerDetails","type":"topic","abstract":[{"text":"Extra information related to a partner event as a dictionary.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Pass an empty dictionary when there are no details to pass back to the Chartboost Mediation SDK."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerDetails"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"PartnerDetails","kind":"identifier"}],"title":"PartnerDetails","url":"\/documentation\/chartboostmediationsdk\/partnerdetails"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration/partnerID":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerID","abstract":[{"type":"text","text":"The partner’s unique identifier."}],"role":"symbol","title":"partnerID","url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/partnerid","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"partnerID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa","text":"PartnerID","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"partnerID","kind":"identifier"}],"required":true},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","title":"Chartboost Developers","titleInlineContent":[{"text":"Chartboost Developers","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerAd":{"url":"\/documentation\/chartboostmediationsdk\/partnerbannerad","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerBannerAd","kind":"identifier"}],"navigatorTitle":[{"text":"PartnerBannerAd","kind":"identifier"}],"role":"symbol","type":"topic","title":"PartnerBannerAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerAd","kind":"symbol","abstract":[{"type":"text","text":"A type of "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true},{"type":"text","text":" which partner banner ads should conform to."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration/log(_:functionName:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/log(_:functionName:)","abstract":[{"text":"Logs an arbitrary message.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/log(_:functionname:)","role":"symbol","title":"log(_:functionName:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"functionName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"StaticString","preciseIdentifier":"s:s12StaticStringV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdLoadRequest":{"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdLoadRequest","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLoadRequest","title":"PartnerAdLoadRequest","url":"\/documentation\/chartboostmediationsdk\/partneradloadrequest","navigatorTitle":[{"text":"PartnerAdLoadRequest","kind":"identifier"}],"abstract":[{"text":"A partner ad load request.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerErrorMapping":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorMapping","kind":"symbol","abstract":[{"type":"text","text":"Methods to map a partner error code to a standard Chartboost Mediation error code."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PartnerErrorMapping","kind":"identifier"}],"title":"PartnerErrorMapping","url":"\/documentation\/chartboostmediationsdk\/partnererrormapping","navigatorTitle":[{"kind":"identifier","text":"PartnerErrorMapping"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerFullscreenAd":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerFullscreenAd","type":"topic","abstract":[{"type":"text","text":"A type of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd"},{"text":" which partner fullscreen ads should conform to.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerFullscreenAd"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PartnerFullscreenAd","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partnerfullscreenad","title":"PartnerFullscreenAd"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerSize":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerBannerSize","kind":"identifier"}],"navigatorTitle":[{"text":"PartnerBannerSize","kind":"identifier"}],"abstract":[{"text":"The size of a partner loaded banner ad.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerbannersize","title":"PartnerBannerSize","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdLogEvent":{"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/partneradlogevent","title":"PartnerAdLogEvent","role":"symbol","navigatorTitle":[{"text":"PartnerAdLogEvent","kind":"identifier"}],"type":"topic","abstract":[{"text":"List of predefined events for ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true,"type":"reference"},{"text":" types to log.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdLogEvent","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapter":{"url":"\/documentation\/chartboostmediationsdk\/partneradapter","navigatorTitle":[{"text":"PartnerAdapter","kind":"identifier"}],"type":"topic","title":"PartnerAdapter","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","abstract":[{"type":"text","text":"The protocol to which all partner adapters conform to."},{"type":"text","text":" "},{"text":"It defines how Chartboost Mediation SDK and its mediated networks communicate.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapter"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration":{"abstract":[{"text":"A configuration type that contains adapter and partner info.","type":"text"},{"text":" ","type":"text"},{"text":"It may also be used to expose custom partner SDK options to the publisher.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","title":"PartnerAdapterConfiguration","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapterConfiguration"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration","type":"topic","navigatorTitle":[{"text":"PartnerAdapterConfiguration","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdDelegate":{"url":"\/documentation\/chartboostmediationsdk\/partneraddelegate","navigatorTitle":[{"kind":"identifier","text":"PartnerAdDelegate"}],"type":"topic","title":"PartnerAdDelegate","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdDelegate","abstract":[{"type":"text","text":"Protocol that defines how a partner ad communicates life-cycle events back to the Chartboost Mediation SDK."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PartnerAdDelegate","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration/partnerDisplayName":{"abstract":[{"type":"text","text":"The human-friendly partner name."}],"kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerDisplayName","title":"partnerDisplayName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"partnerDisplayName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration\/partnerdisplayname","type":"topic","navigatorTitle":[{"kind":"identifier","text":"partnerDisplayName"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerErrorFactory":{"navigatorTitle":[{"text":"PartnerErrorFactory","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Provides the capability to generate errors suitable to be passed in completion handlers for "},{"type":"codeVoice","code":"PartnerAd"},{"type":"text","text":" operations."},{"type":"text","text":" "},{"text":"All functionality is provided by default implementations.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorFactory","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerErrorFactory"}],"title":"PartnerErrorFactory","url":"\/documentation\/chartboostmediationsdk\/partnererrorfactory"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormat":{"abstract":[{"text":"Ad format.","type":"text"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdFormat","kind":"identifier"}],"type":"topic","title":"PartnerAdFormat","navigatorTitle":[{"text":"PartnerAdFormat","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormat","url":"\/documentation\/chartboostmediationsdk\/partneradformat","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerLogEvent":{"title":"PartnerLogEvent","role":"symbol","navigatorTitle":[{"text":"PartnerLogEvent","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partnerlogevent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerLogEvent"}],"abstract":[{"text":"List of predefined events for ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","isActive":true},{"type":"text","text":" types to log."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerLogEvent","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"CBMPartnerAdapterConfiguration","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"kind":"identifier","text":"CBMPartnerAdapterConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"CBMPartnerAdapterConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/adapterVersion","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerDisplayName","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerID","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration\/partnerSDKVersion"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"],"title":"Inherits From"}]},{"op":"replace","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBMPartnerAdapterConfiguration"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"partnerSDKVersion","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1partnerSDKVersion\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1partnerSDKVersion\/fragments","value":[{"text":"partnerSDKVersion","kind":"identifier"}]},{"value":"adapterVersion","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1adapterVersion\/title"},{"value":[{"kind":"identifier","text":"adapterVersion"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1adapterVersion\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1partnerID\/title","op":"replace","value":"partnerID"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1partnerID\/fragments","op":"replace","value":[{"text":"partnerID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/title","value":"CBMPartnerAdapterConfiguration","op":"replace"},{"value":[{"text":"CBMPartnerAdapterConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1partnerDisplayName\/title","value":"partnerDisplayName"},{"op":"replace","value":[{"text":"partnerDisplayName","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration~1partnerDisplayName\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}