{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerID"},{"kind":"text","text":" = "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/partnerid"]}],"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo"],"title":"Initializing the SDK","anchor":"Initializing-the-SDK"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID"},"metadata":{"title":"PartnerID","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerID","kind":"identifier"}],"symbolKind":"typealias","externalID":"s:22ChartboostMediationSDK9PartnerIDa","navigatorTitle":[{"text":"PartnerID","kind":"identifier"}],"role":"symbol","roleHeading":"Type Alias"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"String"},{"text":" that identifies a partner.","type":"text"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PreinitializationConfiguration":{"title":"PreinitializationConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreinitializationConfiguration"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration for Chartboost Mediation preinitialization."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration","url":"\/documentation\/chartboostmediationsdk\/preinitializationconfiguration","role":"symbol","navigatorTitle":[{"text":"PreinitializationConfiguration","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation":{"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK that provides some configuration options."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediation"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","title":"ChartboostMediation","url":"\/documentation\/chartboostmediationsdk\/chartboostmediation","navigatorTitle":[{"text":"ChartboostMediation","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerID":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerID","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"code":"String","type":"codeVoice"},{"type":"text","text":" that identifies a partner."}],"title":"PartnerID","navigatorTitle":[{"text":"PartnerID","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partnerid","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID","type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterInfo":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo","kind":"symbol","navigatorTitle":[{"text":"PartnerAdapterInfo","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapterinfo","abstract":[{"type":"text","text":"General info about a partner adapter."}],"title":"PartnerAdapterInfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerAdapterInfo","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/title","value":"CBMPreinitializationConfiguration"},{"value":[{"text":"CBMPreinitializationConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/navigatorTitle","value":[{"text":"CBMPreinitializationConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/title","value":"ChartboostMediation"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/fragments","value":[{"text":"ChartboostMediation","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ChartboostMediation"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/title","value":"CBMPartnerAdapterInfo"},{"value":[{"text":"CBMPartnerAdapterInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/navigatorTitle","op":"replace","value":[{"text":"CBMPartnerAdapterInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}