{"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterStorage","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormat","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerConfiguration","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerDetails","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorFactory","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorMapping","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerFullscreenAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerLogEvent"],"title":"Creating Adapters","anchor":"Creating-Adapters","generated":true}],"kind":"symbol","metadata":{"modules":[{"name":"ChartboostMediationSDK"}],"title":"PartnerAdFormats","roleHeading":"Enumeration","navigatorTitle":[{"text":"PartnerAdFormats","kind":"identifier"}],"externalID":"s:22ChartboostMediationSDK16PartnerAdFormatsO","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerAdFormats","kind":"identifier"}],"symbolKind":"enum","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdFormats","kind":"identifier"}]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"name":"Note","style":"note","content":[{"inlineContent":[{"text":"Formats are defined as string constants instead of enum cases to prevent adapters from doing","type":"text"},{"type":"text","text":" "},{"text":"exhaustive switches over an ad format value. Doing so can break the adapter compatibility with new","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Mediation SDK minor versions if a new format is introduced."}],"type":"paragraph"}],"type":"aside"}]}],"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/partneradformats"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats\/banner","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats\/interstitial","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats\/rewarded","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats\/rewardedInterstitial"],"generated":true}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A namespace for Mediation’s "},{"code":"PartnerAdFormat","type":"codeVoice"},{"type":"text","text":" constants."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormats/banner":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats\/banner","abstract":[{"text":"Banner ad format.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/partneradformats\/banner","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"banner","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22ChartboostMediationSDK15PartnerAdFormata","kind":"typeIdentifier","text":"PartnerAdFormat"}],"title":"banner","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerConfiguration":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerConfiguration","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerconfiguration","navigatorTitle":[{"text":"PartnerConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Information used by partner adapters to set up.","type":"text"}],"title":"PartnerConfiguration","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerConfiguration","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterStorage":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterStorage","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partneradapterstorage","navigatorTitle":[{"text":"PartnerAdapterStorage","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Exposes storage managed by the Chartboost Mediation SDK to the adapter."}],"title":"PartnerAdapterStorage","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapterStorage"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormats/rewarded":{"abstract":[{"text":"Rewarded ad format.","type":"text"}],"title":"rewarded","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"rewarded","kind":"identifier"},{"kind":"text","text":": "},{"text":"PartnerAdFormat","kind":"typeIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK15PartnerAdFormata"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradformats\/rewarded","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats\/rewarded"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerAd":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partnerbannerad","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerAd","role":"symbol","kind":"symbol","abstract":[{"text":"A type of ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true,"type":"reference"},{"text":" which partner banner ads should conform to.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerBannerAd"}],"title":"PartnerBannerAd","navigatorTitle":[{"kind":"identifier","text":"PartnerBannerAd"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdPreBidRequest":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest","title":"PartnerAdPreBidRequest","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PartnerAdPreBidRequest","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partneradprebidrequest","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerAdPreBidRequest"}],"abstract":[{"text":"A prebidding info request.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerLogEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PartnerLogEvent","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partnerlogevent","kind":"symbol","type":"topic","abstract":[{"text":"List of predefined events for ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","type":"reference","isActive":true},{"type":"text","text":" types to log."}],"title":"PartnerLogEvent","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerLogEvent","navigatorTitle":[{"text":"PartnerLogEvent","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormats/interstitial":{"url":"\/documentation\/chartboostmediationsdk\/partneradformats\/interstitial","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats\/interstitial","abstract":[{"type":"text","text":"Interstitial ad format."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitial"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK15PartnerAdFormata","text":"PartnerAdFormat"}],"title":"interstitial","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerFullscreenAd":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerFullscreenAd","title":"PartnerFullscreenAd","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerFullscreenAd"}],"url":"\/documentation\/chartboostmediationsdk\/partnerfullscreenad","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerFullscreenAd"}],"abstract":[{"type":"text","text":"A type of "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true,"type":"reference"},{"text":" which partner fullscreen ads should conform to.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormats/rewardedInterstitial":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats\/rewardedInterstitial","abstract":[{"text":"Rewarded interstitial ad format.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/partneradformats\/rewardedinterstitial","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"rewardedInterstitial","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22ChartboostMediationSDK15PartnerAdFormata","kind":"typeIdentifier","text":"PartnerAdFormat"}],"title":"rewardedInterstitial","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerSize":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize","url":"\/documentation\/chartboostmediationsdk\/partnerbannersize","abstract":[{"type":"text","text":"The size of a partner loaded banner ad."}],"role":"symbol","title":"PartnerBannerSize","type":"topic","kind":"symbol","navigatorTitle":[{"text":"PartnerBannerSize","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerBannerSize"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormats":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats","url":"\/documentation\/chartboostmediationsdk\/partneradformats","abstract":[{"type":"text","text":"A namespace for Mediation’s "},{"code":"PartnerAdFormat","type":"codeVoice"},{"type":"text","text":" constants."}],"role":"symbol","title":"PartnerAdFormats","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerAdFormats"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerAdFormats","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A configuration type that contains adapter and partner info."},{"type":"text","text":" "},{"text":"It may also be used to expose custom partner SDK options to the publisher.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdapterConfiguration","kind":"identifier"}],"title":"PartnerAdapterConfiguration","navigatorTitle":[{"text":"PartnerAdapterConfiguration","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdDelegate":{"title":"PartnerAdDelegate","abstract":[{"text":"Protocol that defines how a partner ad communicates life-cycle events back to the Chartboost Mediation SDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PartnerAdDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PartnerAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/partneraddelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdLoadRequest":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradloadrequest","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLoadRequest","role":"symbol","kind":"symbol","abstract":[{"text":"A partner ad load request.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerAdLoadRequest"}],"title":"PartnerAdLoadRequest","navigatorTitle":[{"kind":"identifier","text":"PartnerAdLoadRequest"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAd":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerAd","kind":"identifier"}],"type":"topic","abstract":[{"text":"A protocol to which ads created by ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","type":"reference","isActive":true},{"type":"text","text":" types conform to."},{"type":"text","text":" "},{"text":"Partner ads are in charge of communicating with a single partner SDK ad instance and reporting back ad life-cycle","type":"text"},{"type":"text","text":" "},{"type":"text","text":"events corresponding to that ad to the Chartboost Mediation SDK."},{"text":" ","type":"text"},{"text":"They also keep track of information related to a single load request.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerad","navigatorTitle":[{"kind":"identifier","text":"PartnerAd"}],"title":"PartnerAd"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerDetails":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerDetails"}],"navigatorTitle":[{"kind":"identifier","text":"PartnerDetails"}],"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerdetails","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerDetails","title":"PartnerDetails","type":"topic","abstract":[{"text":"Extra information related to a partner event as a dictionary.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Pass an empty dictionary when there are no details to pass back to the Chartboost Mediation SDK."}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapter":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","title":"PartnerAdapter","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerAdapter"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapter","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapter"}],"abstract":[{"type":"text","text":"The protocol to which all partner adapters conform to."},{"type":"text","text":" "},{"type":"text","text":"It defines how Chartboost Mediation SDK and its mediated networks communicate."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerErrorFactory":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorFactory","url":"\/documentation\/chartboostmediationsdk\/partnererrorfactory","abstract":[{"text":"Provides the capability to generate errors suitable to be passed in completion handlers for ","type":"text"},{"code":"PartnerAd","type":"codeVoice"},{"type":"text","text":" operations."},{"text":" ","type":"text"},{"text":"All functionality is provided by default implementations.","type":"text"}],"role":"symbol","title":"PartnerErrorFactory","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerErrorFactory"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerErrorFactory"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdLogEvent":{"abstract":[{"type":"text","text":"List of predefined events for "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true},{"text":" types to log.","type":"text"}],"type":"topic","title":"PartnerAdLogEvent","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","url":"\/documentation\/chartboostmediationsdk\/partneradlogevent","navigatorTitle":[{"text":"PartnerAdLogEvent","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdLogEvent","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerErrorMapping":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorMapping","title":"PartnerErrorMapping","url":"\/documentation\/chartboostmediationsdk\/partnererrormapping","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PartnerErrorMapping","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PartnerErrorMapping"}],"role":"symbol","abstract":[{"text":"Methods to map a partner error code to a standard Chartboost Mediation error code.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormat":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdFormat"}],"navigatorTitle":[{"text":"PartnerAdFormat","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradformat","title":"PartnerAdFormat","kind":"symbol","abstract":[{"type":"text","text":"Ad format."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormat"}},"variantOverrides":[{"patch":[{"value":"CBMPartnerAdapterConfiguration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMPartnerAdapterConfiguration"}]},{"op":"replace","value":[{"kind":"identifier","text":"CBMPartnerAdapterConfiguration"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}