{"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterStorage","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdDelegate","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormat","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLoadRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerConfiguration","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerDetails","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorFactory","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorMapping","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerFullscreenAd","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerLogEvent"],"anchor":"Creating-Adapters","title":"Creating Adapters","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerBannerSize","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/partnerbannersize"]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","title":"PartnerBannerSize","navigatorTitle":[{"kind":"identifier","text":"PartnerBannerSize"}],"roleHeading":"Structure","modules":[{"name":"ChartboostMediationSDK"}],"symbolKind":"struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerBannerSize"}],"externalID":"s:22ChartboostMediationSDK17PartnerBannerSizeV"},"abstract":[{"text":"The size of a partner loaded banner ad.","type":"text"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize\/init(size:type:)"],"anchor":"Initializers","title":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize\/size","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize\/type"],"anchor":"Instance-Properties"},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize\/Equatable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerAd":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partnerbannerad","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerAd","role":"symbol","kind":"symbol","abstract":[{"text":"A type of ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true,"type":"reference"},{"text":" which partner banner ads should conform to.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerBannerAd"}],"title":"PartnerBannerAd","navigatorTitle":[{"kind":"identifier","text":"PartnerBannerAd"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerConfiguration":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerConfiguration","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerconfiguration","navigatorTitle":[{"text":"PartnerConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Information used by partner adapters to set up.","type":"text"}],"title":"PartnerConfiguration","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerConfiguration","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterStorage":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterStorage","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partneradapterstorage","navigatorTitle":[{"text":"PartnerAdapterStorage","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Exposes storage managed by the Chartboost Mediation SDK to the adapter."}],"title":"PartnerAdapterStorage","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapterStorage"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerSize":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize","url":"\/documentation\/chartboostmediationsdk\/partnerbannersize","abstract":[{"type":"text","text":"The size of a partner loaded banner ad."}],"role":"symbol","title":"PartnerBannerSize","type":"topic","kind":"symbol","navigatorTitle":[{"text":"PartnerBannerSize","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerBannerSize"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdLogEvent":{"abstract":[{"type":"text","text":"List of predefined events for "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true},{"text":" types to log.","type":"text"}],"type":"topic","title":"PartnerAdLogEvent","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLogEvent","url":"\/documentation\/chartboostmediationsdk\/partneradlogevent","navigatorTitle":[{"text":"PartnerAdLogEvent","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdLogEvent","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerSize/Equatable-Implementations":{"kind":"article","url":"\/documentation\/chartboostmediationsdk\/partnerbannersize\/equatable-implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize\/Equatable-Implementations"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdDelegate":{"title":"PartnerAdDelegate","abstract":[{"text":"Protocol that defines how a partner ad communicates life-cycle events back to the Chartboost Mediation SDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PartnerAdDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PartnerAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/partneraddelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerErrorMapping":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorMapping","title":"PartnerErrorMapping","url":"\/documentation\/chartboostmediationsdk\/partnererrormapping","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PartnerErrorMapping","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PartnerErrorMapping"}],"role":"symbol","abstract":[{"text":"Methods to map a partner error code to a standard Chartboost Mediation error code.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormat":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdFormat"}],"navigatorTitle":[{"text":"PartnerAdFormat","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradformat","title":"PartnerAdFormat","kind":"symbol","abstract":[{"type":"text","text":"Ad format."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormat"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerSize/init(size:type:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize\/init(size:type:)","title":"init(size:type:)","role":"symbol","abstract":[{"text":"Public constructor.","type":"text"}],"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerbannersize\/init(size:type:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BannerType","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CBMBannerType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerFullscreenAd":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerFullscreenAd","title":"PartnerFullscreenAd","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerFullscreenAd"}],"url":"\/documentation\/chartboostmediationsdk\/partnerfullscreenad","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerFullscreenAd"}],"abstract":[{"type":"text","text":"A type of "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","isActive":true,"type":"reference"},{"text":" which partner fullscreen ads should conform to.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAd":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerAd","kind":"identifier"}],"type":"topic","abstract":[{"text":"A protocol to which ads created by ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","type":"reference","isActive":true},{"type":"text","text":" types conform to."},{"type":"text","text":" "},{"text":"Partner ads are in charge of communicating with a single partner SDK ad instance and reporting back ad life-cycle","type":"text"},{"type":"text","text":" "},{"type":"text","text":"events corresponding to that ad to the Chartboost Mediation SDK."},{"text":" ","type":"text"},{"text":"They also keep track of information related to a single load request.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAd","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerad","navigatorTitle":[{"kind":"identifier","text":"PartnerAd"}],"title":"PartnerAd"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerSize/size":{"url":"\/documentation\/chartboostmediationsdk\/partnerbannersize\/size","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"abstract":[{"text":"The underlying ","type":"text"},{"code":"CGSize","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize\/size","kind":"symbol","title":"size","type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdPreBidRequest":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdPreBidRequest","title":"PartnerAdPreBidRequest","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PartnerAdPreBidRequest","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partneradprebidrequest","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerAdPreBidRequest"}],"abstract":[{"text":"A prebidding info request.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerLogEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PartnerLogEvent","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partnerlogevent","kind":"symbol","type":"topic","abstract":[{"text":"List of predefined events for ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","type":"reference","isActive":true},{"type":"text","text":" types to log."}],"title":"PartnerLogEvent","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerLogEvent","navigatorTitle":[{"text":"PartnerLogEvent","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerDetails":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerDetails"}],"navigatorTitle":[{"kind":"identifier","text":"PartnerDetails"}],"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerdetails","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerDetails","title":"PartnerDetails","type":"topic","abstract":[{"text":"Extra information related to a partner event as a dictionary.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Pass an empty dictionary when there are no details to pass back to the Chartboost Mediation SDK."}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A configuration type that contains adapter and partner info."},{"type":"text","text":" "},{"text":"It may also be used to expose custom partner SDK options to the publisher.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdapterConfiguration","kind":"identifier"}],"title":"PartnerAdapterConfiguration","navigatorTitle":[{"text":"PartnerAdapterConfiguration","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapter":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","title":"PartnerAdapter","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerAdapter"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapter","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapter"}],"abstract":[{"type":"text","text":"The protocol to which all partner adapters conform to."},{"type":"text","text":" "},{"type":"text","text":"It defines how Chartboost Mediation SDK and its mediated networks communicate."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdFormats":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdFormats","url":"\/documentation\/chartboostmediationsdk\/partneradformats","abstract":[{"type":"text","text":"A namespace for Mediation’s "},{"code":"PartnerAdFormat","type":"codeVoice"},{"type":"text","text":" constants."}],"role":"symbol","title":"PartnerAdFormats","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerAdFormats"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerAdFormats","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerErrorFactory":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerErrorFactory","url":"\/documentation\/chartboostmediationsdk\/partnererrorfactory","abstract":[{"text":"Provides the capability to generate errors suitable to be passed in completion handlers for ","type":"text"},{"code":"PartnerAd","type":"codeVoice"},{"type":"text","text":" operations."},{"text":" ","type":"text"},{"text":"All functionality is provided by default implementations.","type":"text"}],"role":"symbol","title":"PartnerErrorFactory","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerErrorFactory"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerErrorFactory"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerBannerSize/type":{"url":"\/documentation\/chartboostmediationsdk\/partnerbannersize\/type","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerBannerSize\/type","abstract":[{"text":"The banner type.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CBMBannerType","text":"BannerType","kind":"typeIdentifier"}],"role":"symbol","title":"type","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdLoadRequest":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradloadrequest","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdLoadRequest","role":"symbol","kind":"symbol","abstract":[{"text":"A partner ad load request.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerAdLoadRequest"}],"title":"PartnerAdLoadRequest","navigatorTitle":[{"kind":"identifier","text":"PartnerAdLoadRequest"}]},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/title","value":"CBMPartnerAdapterConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/fragments","value":[{"text":"CBMPartnerAdapterConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMPartnerAdapterConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}