{"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/preinitializationconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/preinitializationconfiguration"]}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration\/init(skippedPartnerIDs:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration\/skippedPartnerIDs"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(CBMPreinitializationConfiguration) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PreinitializationConfiguration","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"PreinitializationConfiguration","kind":"identifier"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMPreinitializationConfiguration","modules":[{"name":"ChartboostMediationSDK"}],"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PreinitializationConfiguration","kind":"identifier"}],"title":"PreinitializationConfiguration","symbolKind":"class"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Configuration for Chartboost Mediation preinitialization."}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ","doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID"],"generated":true,"anchor":"Initializing-the-SDK","title":"Initializing the SDK"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s7CVarArgP"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterInfo":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PartnerAdapterInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"General info about a partner adapter."}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradapterinfo","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PartnerAdapterInfo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo","title":"PartnerAdapterInfo"},"doc://org.cocoapods.ChartboostMediationSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SQ"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerID":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"String"},{"type":"text","text":" that identifies a partner."}],"navigatorTitle":[{"text":"PartnerID","kind":"identifier"}],"title":"PartnerID","type":"topic","url":"\/documentation\/chartboostmediationsdk\/partnerid","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"PartnerID","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PreinitializationConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PreinitializationConfiguration"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration","title":"PreinitializationConfiguration","type":"topic","abstract":[{"text":"Configuration for Chartboost Mediation preinitialization.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"PreinitializationConfiguration","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/preinitializationconfiguration"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PreinitializationConfiguration/skippedPartnerIDs":{"type":"topic","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/preinitializationconfiguration\/skippedpartnerids","abstract":[{"text":"Set of Partner adapters to skip during Chartboost Mediation SDK initialization.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"skippedPartnerIDs","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration\/skippedPartnerIDs","title":"skippedPartnerIDs","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skippedPartnerIDs"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"PartnerID","kind":"typeIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa"},{"kind":"text","text":">"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PreinitializationConfiguration/init(skippedPartnerIDs:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"skippedPartnerIDs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"PartnerID","preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa"},{"text":"])","kind":"text"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/preinitializationconfiguration\/init(skippedpartnerids:)","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration\/init(skippedPartnerIDs:)","navigatorTitle":[{"text":"initWithSkippedPartnerIDs:","kind":"identifier"}],"role":"symbol","title":"init(skippedPartnerIDs:)","abstract":[{"text":"Initializes a ","type":"text"},{"type":"codeVoice","code":"PreinitializationConfiguration"},{"type":"text","text":" instance."}]},"doc://org.cocoapods.ChartboostMediationSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.ChartboostMediationSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChartboostMediation","kind":"identifier"}],"abstract":[{"text":"The main interface to the Chartboost Mediation SDK that provides some configuration options.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediation"}],"type":"topic","title":"ChartboostMediation"},"doc://org.cocoapods.ChartboostMediationSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/SH"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"CBMPreinitializationConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CBMPreinitializationConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CBMPreinitializationConfiguration"}]},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration\/skippedPartnerIDs"]},{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration\/init(skippedPartnerIDs:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/objc(cs)NSObject"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo"],"generated":true,"anchor":"Initializing-the-SDK","title":"Initializing the SDK"}]},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBMPreinitializationConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/title","value":"CBMPartnerAdapterInfo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/fragments","value":[{"text":"CBMPartnerAdapterInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/navigatorTitle","value":[{"text":"CBMPartnerAdapterInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/title","value":"CBMPreinitializationConfiguration"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMPreinitializationConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"CBMPreinitializationConfiguration"}]},{"op":"replace","value":"skippedPartnerIDs","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration~1skippedPartnerIDs\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration~1skippedPartnerIDs\/fragments","value":[{"text":"skippedPartnerIDs","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration~1init(skippedPartnerIDs:)\/title","value":"initWithSkippedPartnerIDs:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration~1init(skippedPartnerIDs:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSkippedPartnerIDs:"}]},{"op":"replace","value":"ChartboostMediation","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/fragments","value":[{"text":"ChartboostMediation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/navigatorTitle","value":[{"kind":"identifier","text":"ChartboostMediation"}]}]}]}