{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(showAdWithViewController:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"View controller used to present the ad."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When complete, the delegate method "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAd(withPlacementName:didShowWithError:)"},{"type":"text","text":" "},{"type":"text","text":"will be invoked."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/heliuminterstitialad\/show(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/heliuminterstitialad\/show(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd\/show(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Asynchronously shows the ad with the specified view controller."}],"kind":"symbol","metadata":{"role":"symbol","title":"show(with:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(pl)HeliumInterstitialAd(im)showAdWithViewController:","required":true,"modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInterstitialAd":{"role":"symbol","title":"HeliumInterstitialAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInterstitialAd"}],"abstract":[{"type":"text","text":"Helium interstitial ad."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumInterstitialAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminterstitialad"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumInterstitialAdDelegate/heliumInterstitialAd(withPlacementName:didShowWithError:)":{"role":"symbol","title":"heliumInterstitialAd(withPlacementName:didShowWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumInterstitialAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didShowWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Ad finished showing with an optional error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumInterstitialAdDelegate\/heliumInterstitialAd(withPlacementName:didShowWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbheliuminterstitialaddelegate\/heliuminterstitialad(withplacementname:didshowwitherror:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInterstitialAd/show(with:)":{"role":"symbol","title":"show(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Asynchronously shows the ad with the specified view controller."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd\/show(with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/heliuminterstitialad\/show(with:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showAdWithViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}