{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"text":"BannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Depending on your dashboard setup, the actual ad returned may be smaller than the requested size.","type":"text"}]}],"name":"Note"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/cbmbanneradloadrequest\/size"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/cbmbanneradloadrequest\/size"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerAdLoadRequest(py)size","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"size"}],"modules":[{"name":"ChartboostMediationSDK"}],"title":"size","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"text":"BannerSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMBannerAdLoadRequest\/size"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest"]]},"abstract":[{"type":"text","text":"The maximum size of banner to request."}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CBMBannerAdLoadRequest/size":{"url":"\/documentation\/chartboostmediationsdk\/cbmbanneradloadrequest\/size","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"size","kind":"identifier"}],"title":"size","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier","text":"BannerSize"}],"abstract":[{"text":"The maximum size of banner to request.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMBannerAdLoadRequest\/size"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdLoadRequest":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerAdLoadRequest"}],"url":"\/documentation\/chartboostmediationsdk\/banneradloadrequest","type":"topic","abstract":[{"type":"text","text":"A request used to load a banner ad."}],"role":"symbol","navigatorTitle":[{"text":"BannerAdLoadRequest","kind":"identifier"}],"title":"BannerAdLoadRequest","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdLoadRequest"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BannerSize","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannersize","type":"topic","abstract":[{"type":"text","text":"The size of a banner ad."}],"role":"symbol","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"title":"BannerSize","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"size","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"size","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"CBMBannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"},{"text":" * ","kind":"text"},{"text":"size","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"size","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMBannerAdLoadRequest~1size\/title"},{"value":[{"kind":"identifier","text":"size"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMBannerAdLoadRequest~1size\/fragments","op":"replace"},{"op":"replace","value":"CBMBannerAdLoadRequest","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdLoadRequest\/fragments","value":[{"text":"CBMBannerAdLoadRequest","kind":"identifier"}],"op":"replace"},{"value":"CBMBannerSize","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments","value":[{"kind":"identifier","text":"CBMBannerSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}