{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"configuration","externalID":"s:22ChartboostMediationSDK14PartnerAdapterP13configurationAA0dE13Configuration_pXpvp","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"text":"PartnerAdapterConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMPartnerAdapterConfiguration"},{"kind":"text","text":".Type"}],"role":"symbol","roleHeading":"Instance Property","required":true,"symbolKind":"property"},"abstract":[{"type":"text","text":"The adapter configuration type that contains adapter and partner info."},{"type":"text","text":" "},{"text":"It may also be used to expose custom partner SDK options to the publisher.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PartnerAdapterConfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMPartnerAdapterConfiguration"},{"kind":"text","text":".Type { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter\/configuration"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/partneradapter\/configuration"]}],"kind":"symbol","references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapter":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter","title":"PartnerAdapter","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PartnerAdapter"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapter","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapter"}],"abstract":[{"type":"text","text":"The protocol to which all partner adapters conform to."},{"type":"text","text":" "},{"type":"text","text":"It defines how Chartboost Mediation SDK and its mediated networks communicate."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration":{"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A configuration type that contains adapter and partner info."},{"type":"text","text":" "},{"text":"It may also be used to expose custom partner SDK options to the publisher.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PartnerAdapterConfiguration","kind":"identifier"}],"title":"PartnerAdapterConfiguration","navigatorTitle":[{"text":"PartnerAdapterConfiguration","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapter/configuration":{"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMPartnerAdapterConfiguration","text":"PartnerAdapterConfiguration"},{"kind":"text","text":".Type"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapter\/configuration","title":"configuration","url":"\/documentation\/chartboostmediationsdk\/partneradapter\/configuration","abstract":[{"text":"The adapter configuration type that contains adapter and partner info.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It may also be used to expose custom partner SDK options to the publisher."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/title","value":"CBMPartnerAdapterConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/fragments","value":[{"kind":"identifier","text":"CBMPartnerAdapterConfiguration"}]},{"value":[{"kind":"identifier","text":"CBMPartnerAdapterConfiguration"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}