{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidate"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Calling this is unnecessary when the ad is shown. Use it only if you want to discard a particular ad and get a"},{"type":"text","text":" "},{"type":"text","text":"new one when loading again with the same placement."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad\/invalidate()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad\/invalidate()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/invalidate()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invalidates the ad so it gets discarded by Chartboost Mediation’s internal cache."}],"kind":"symbol","metadata":{"role":"symbol","title":"invalidate()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidate"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAd(im)invalidate","required":true,"modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd/invalidate()":{"role":"symbol","title":"invalidate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidate"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Invalidates the ad so it gets discarded by Chartboost Mediation’s internal cache."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/invalidate()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad\/invalidate()"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd":{"role":"symbol","title":"ChartboostMediationFullscreenAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"abstract":[{"type":"text","text":"A Chartboost Mediation fullscreen ad ready to be shown."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"invalidate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}