{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Initializes a ","type":"text"},{"code":"PreinitializationConfiguration","type":"codeVoice"},{"text":" instance.","type":"text"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSkippedPartnerIDs:"}],"roleHeading":"Initializer","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMPreinitializationConfiguration(im)initWithSkippedPartnerIDs:","modules":[{"name":"ChartboostMediationSDK"}],"symbolKind":"init","title":"init(skippedPartnerIDs:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"skippedPartnerIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa","text":"PartnerID"},{"kind":"text","text":"])"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration\/init(skippedPartnerIDs:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"skippedPartnerIDs","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa","text":"PartnerID","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID"},{"text":"])","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"skippedPartnerIDs","content":[{"inlineContent":[{"type":"text","text":"Optional partner adapters to skip initialization."}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/preinitializationconfiguration\/init(skippedpartnerids:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/preinitializationconfiguration\/init(skippedpartnerids:)"]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerID":{"title":"PartnerID","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"String"},{"text":" that identifies a partner.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partnerid","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID","navigatorTitle":[{"kind":"identifier","text":"PartnerID"}],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PartnerID","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"kind":"symbol","type":"topic","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PreinitializationConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreinitializationConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/preinitializationconfiguration","title":"PreinitializationConfiguration","navigatorTitle":[{"kind":"identifier","text":"PreinitializationConfiguration"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration","abstract":[{"text":"Configuration for Chartboost Mediation preinitialization.","type":"text"}],"type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PreinitializationConfiguration/init(skippedPartnerIDs:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSkippedPartnerIDs:"}],"type":"topic","title":"init(skippedPartnerIDs:)","url":"\/documentation\/chartboostmediationsdk\/preinitializationconfiguration\/init(skippedpartnerids:)","abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"PreinitializationConfiguration"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration\/init(skippedPartnerIDs:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"skippedPartnerIDs"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa","kind":"typeIdentifier","text":"PartnerID"},{"text":"])","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithSkippedPartnerIDs:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSkippedPartnerIDs:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithSkippedPartnerIDs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"text":"skippedPartnerIDs","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"CBMPreinitializationConfiguration","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/title"},{"value":[{"kind":"identifier","text":"CBMPreinitializationConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/fragments"},{"value":"initWithSkippedPartnerIDs:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration~1init(skippedPartnerIDs:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSkippedPartnerIDs:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration~1init(skippedPartnerIDs:)\/fragments"}]}]}