{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"skippedPartnerIDs","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID","kind":"typeIdentifier","text":"PartnerID","preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration"]]},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMPreinitializationConfiguration(py)skippedPartnerIDs","symbolKind":"property","roleHeading":"Instance Property","title":"skippedPartnerIDs","role":"symbol","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skippedPartnerIDs"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"PartnerID","preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa"},{"text":">","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"skippedPartnerIDs"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/preinitializationconfiguration\/skippedpartnerids"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/preinitializationconfiguration\/skippedpartnerids"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration\/skippedPartnerIDs"},"abstract":[{"type":"text","text":"Set of Partner adapters to skip during Chartboost Mediation SDK initialization."}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PreinitializationConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"PreinitializationConfiguration"}],"url":"\/documentation\/chartboostmediationsdk\/preinitializationconfiguration","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration","title":"PreinitializationConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreinitializationConfiguration"}],"abstract":[{"type":"text","text":"Configuration for Chartboost Mediation preinitialization."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerID":{"role":"symbol","abstract":[{"type":"text","text":"A "},{"code":"String","type":"codeVoice"},{"text":" that identifies a partner.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/partnerid","type":"topic","title":"PartnerID","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"PartnerID","kind":"identifier"}],"navigatorTitle":[{"text":"PartnerID","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","title":"Chartboost Developers","type":"link","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PreinitializationConfiguration/skippedPartnerIDs":{"kind":"symbol","type":"topic","title":"skippedPartnerIDs","role":"symbol","abstract":[{"type":"text","text":"Set of Partner adapters to skip during Chartboost Mediation SDK initialization."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skippedPartnerIDs"},{"kind":"text","text":": "},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa","text":"PartnerID","kind":"typeIdentifier"},{"kind":"text","text":">"}],"url":"\/documentation\/chartboostmediationsdk\/preinitializationconfiguration\/skippedpartnerids","navigatorTitle":[{"text":"skippedPartnerIDs","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration\/skippedPartnerIDs"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"skippedPartnerIDs","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"skippedPartnerIDs"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"skippedPartnerIDs","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/title","value":"CBMPreinitializationConfiguration"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/fragments","op":"replace","value":[{"text":"CBMPreinitializationConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration~1skippedPartnerIDs\/title","value":"skippedPartnerIDs"},{"value":[{"kind":"identifier","text":"skippedPartnerIDs"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration~1skippedPartnerIDs\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}