{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializedAdapterInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumAdapterInfo","text":"HeliumAdapterInfo"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/helium\/initializedadapterinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/helium\/initializedadapterinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/initializedAdapterInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An array of all initialized adapters, or an empty array if the SDK is not initialized."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializedAdapterInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HeliumAdapterInfo","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumAdapterInfo"},{"kind":"text","text":"]"}],"title":"initializedAdapterInfo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)Helium(py)initializedAdapterInfo","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initializedAdapterInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium":{"role":"symbol","title":"Helium","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Helium"}],"url":"\/documentation\/chartboostmediationsdk\/helium"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumAdapterInfo":{"role":"symbol","title":"HeliumAdapterInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumAdapterInfo"}],"abstract":[{"type":"text","text":"General info about a partner adapter."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumAdapterInfo"}],"url":"\/documentation\/chartboostmediationsdk\/heliumadapterinfo"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/initializedAdapterInfo":{"role":"symbol","title":"initializedAdapterInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializedAdapterInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HeliumAdapterInfo","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumAdapterInfo"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"An array of all initialized adapters, or an empty array if the SDK is not initialized."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/initializedAdapterInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializedAdapterInfo"}],"url":"\/documentation\/chartboostmediationsdk\/helium\/initializedadapterinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"initializedAdapterInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"initializedAdapterInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<HeliumAdapterInfo *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"initializedAdapterInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium\/title","value":"Helium"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium\/fragments","value":[{"kind":"identifier","text":"Helium"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumAdapterInfo\/title","value":"HeliumAdapterInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumAdapterInfo\/fragments","value":[{"kind":"identifier","text":"HeliumAdapterInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium~1initializedAdapterInfo\/title","value":"initializedAdapterInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium~1initializedAdapterInfo\/fragments","value":[{"kind":"identifier","text":"initializedAdapterInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}