{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(rewardedAdProviderWithDelegate:andPlacementName:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumRewardedAdDelegate","text":"CHBHeliumRewardedAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"placementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumRewardedAd","text":"HeliumRewardedAd"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The rewarded ad provider if successful; otherwise "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" will be returned."}]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Delegate to receive rewarded ad callbacks."}]}]},{"name":"placementName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Rewarded ad placement from the Chartboost dashboard."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/helium\/rewardedadprovider(with:andplacementname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/helium\/rewardedadprovider(with:andplacementname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/rewardedAdProvider(with:andPlacementName:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Factory method to create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd"},{"type":"text","text":" which will be used to load and show rewarded ads."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"rewardedAdProviderWithDelegate:andPlacementName:"}],"role":"symbol","title":"rewardedAdProvider(with:andPlacementName:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBHeliumRewardedAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumRewardedAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeliumRewardedAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumRewardedAd"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)Helium(im)rewardedAdProviderWithDelegate:andPlacementName:","modules":[{"name":"ChartboostMediationSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use loadFullscreenAd(with:completion:) for the most comprehensive fullscreen ad experience."}]}],"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/rewardedAdProvider(with:andPlacementName:)":{"deprecated":true,"role":"symbol","title":"rewardedAdProvider(with:andPlacementName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBHeliumRewardedAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumRewardedAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeliumRewardedAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumRewardedAd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Factory method to create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd"},{"type":"text","text":" which will be used to load and show rewarded ads."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/rewardedAdProvider(with:andPlacementName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rewardedAdProviderWithDelegate:andPlacementName:"}],"url":"\/documentation\/chartboostmediationsdk\/helium\/rewardedadprovider(with:andplacementname:)"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium":{"role":"symbol","title":"Helium","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Helium"}],"url":"\/documentation\/chartboostmediationsdk\/helium"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumRewardedAdDelegate":{"role":"symbol","title":"CHBHeliumRewardedAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"}],"abstract":[{"type":"text","text":"Callbacks for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumRewardedAd":{"role":"symbol","title":"HeliumRewardedAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumRewardedAd"}],"abstract":[{"type":"text","text":"Helium rewarded ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumRewardedAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliumrewardedad"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rewardedAdProviderWithDelegate:andPlacementName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rewardedAdProviderWithDelegate:andPlacementName:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<HeliumRewardedAd>","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)HeliumRewardedAd"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"rewardedAdProviderWithDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<CHBHeliumRewardedAdDelegate>","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)CHBHeliumRewardedAdDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"andPlacementName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"placementName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium~1rewardedAdProvider(with:andPlacementName:)\/title","value":"rewardedAdProviderWithDelegate:andPlacementName:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium~1rewardedAdProvider(with:andPlacementName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rewardedAdProviderWithDelegate:andPlacementName:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium\/title","value":"Helium"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium\/fragments","value":[{"kind":"identifier","text":"Helium"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CHBHeliumRewardedAdDelegate\/title","value":"CHBHeliumRewardedAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CHBHeliumRewardedAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumRewardedAd\/title","value":"HeliumRewardedAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumRewardedAd\/fragments","value":[{"kind":"identifier","text":"HeliumRewardedAd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}