{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didExpire"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAd","text":"ChartboostMediationFullscreenAd"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"name":"ad","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ad that triggered this event."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenaddelegate\/didexpire(ad:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenaddelegate\/didexpire(ad:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAdDelegate\/didExpire(ad:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the ad expired."}],"kind":"symbol","metadata":{"role":"symbol","title":"didExpire(ad:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didExpire"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationFullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAd"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAdDelegate(im)didExpireWithAd:","required":true,"modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAdDelegate"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAdDelegate":{"role":"symbol","title":"ChartboostMediationFullscreenAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationFullscreenAdDelegate"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd"},{"type":"text","text":" delegate that receives ad callbacks."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationFullscreenAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenaddelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd":{"role":"symbol","title":"ChartboostMediationFullscreenAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"abstract":[{"type":"text","text":"A Chartboost Mediation fullscreen ad ready to be shown."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAdDelegate/didExpire(ad:)":{"role":"symbol","title":"didExpire(ad:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didExpire"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationFullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the ad expired."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAdDelegate\/didExpire(ad:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenaddelegate\/didexpire(ad:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didExpireWithAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ChartboostMediationFullscreenAd>","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAd"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ad"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}