{"seeAlsoSections":[{"title":"Ad Objects","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAd","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Chartboost Mediation fullscreen ad ready to be shown."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"title":"ChartboostMediationFullscreenAd","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAd","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/customData","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/delegate","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/request","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/winningBidInfo"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/invalidate()","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/show(with:completion:)"]}],"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd/winningBidInfo":{"navigatorTitle":[{"kind":"identifier","text":"winningBidInfo"}],"role":"symbol","title":"winningBidInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"winningBidInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Information about the bid that won the auction."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/winningBidInfo","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad\/winningbidinfo"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd/customData":{"navigatorTitle":[{"kind":"identifier","text":"customData"}],"role":"symbol","title":"customData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Optional custom data that will be sent on every rewarded callback."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/customData","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad\/customdata"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd/invalidate()":{"navigatorTitle":[{"kind":"identifier","text":"invalidate"}],"role":"symbol","title":"invalidate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidate"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Invalidates the ad so it gets discarded by Chartboost Mediation’s internal cache."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/invalidate()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad\/invalidate()"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd/delegate":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationFullscreenAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAdDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The delegate to receive ad callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/delegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad\/delegate"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd":{"role":"symbol","title":"ChartboostMediationFullscreenAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"abstract":[{"type":"text","text":"A Chartboost Mediation fullscreen ad ready to be shown."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInterstitialAd":{"role":"symbol","title":"HeliumInterstitialAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInterstitialAd"}],"abstract":[{"type":"text","text":"Helium interstitial ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumInterstitialAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminterstitialad"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumRewardedAd":{"role":"symbol","title":"HeliumRewardedAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumRewardedAd"}],"abstract":[{"type":"text","text":"Helium rewarded ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumRewardedAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliumrewardedad"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd/request":{"navigatorTitle":[{"kind":"identifier","text":"request"}],"role":"symbol","title":"request","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationAdLoadRequest","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationAdLoadRequest"}],"abstract":[{"type":"text","text":"The request that resulted in this ad getting loaded."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/request","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad\/request"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd/show(with:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"showWith:completion:"}],"role":"symbol","title":"show(with:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChartboostMediationAdShowResult","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationAdShowResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Shows the ad on the specified view controller."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/show(with:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad\/show(with:completion:)"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerAd":{"role":"symbol","title":"HeliumBannerAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumBannerAd"}],"abstract":[{"type":"text","text":"Helium banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumBannerAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliumbannerad"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerView":{"role":"symbol","title":"HeliumBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumBannerView"}],"abstract":[{"type":"text","text":"Helium banner ad view."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumBannerView"}],"url":"\/documentation\/chartboostmediationsdk\/heliumbannerview"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ChartboostMediationFullscreenAd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/customData","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/delegate","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/request","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/winningBidInfo"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/invalidate()","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd\/show(with:completion:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Ad Objects","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAd","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInterstitialAd","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1winningBidInfo\/title","value":"winningBidInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1winningBidInfo\/fragments","value":[{"kind":"identifier","text":"winningBidInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1customData\/title","value":"customData"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1customData\/fragments","value":[{"kind":"identifier","text":"customData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1invalidate()\/title","value":"invalidate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1invalidate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd\/title","value":"ChartboostMediationFullscreenAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInterstitialAd\/title","value":"HeliumInterstitialAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInterstitialAd\/fragments","value":[{"kind":"identifier","text":"HeliumInterstitialAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumRewardedAd\/title","value":"HeliumRewardedAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumRewardedAd\/fragments","value":[{"kind":"identifier","text":"HeliumRewardedAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1request\/title","value":"request"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1request\/fragments","value":[{"kind":"identifier","text":"request"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1show(with:completion:)\/title","value":"showWith:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd~1show(with:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showWith:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumBannerAd\/title","value":"HeliumBannerAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumBannerAd\/fragments","value":[{"kind":"identifier","text":"HeliumBannerAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumBannerView\/title","value":"HeliumBannerView"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumBannerView\/fragments","value":[{"kind":"identifier","text":"HeliumBannerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}