{"seeAlsoSections":[{"title":"Initializing the SDK","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerIdentifier"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInitializationOptions"}],"title":"HeliumInitializationOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChartboostMediationSDK@objc(cs)HeliumInitializationOptions","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HeliumInitializationOptions"}]},"abstract":[{"type":"text","text":"Options for Helium initialization."}],"sections":[],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/com.chartboost.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/com.chartboost.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.chartboost.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/com.chartboost.ChartboostMediationSDK\/SQ","doc:\/\/com.chartboost.ChartboostMediationSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions\/init(skippedPartnerIdentifiers:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions\/skippedPartnerIdentifiers"]}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/heliuminitializationoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/heliuminitializationoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(HeliumInitializationOptions) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInitializationOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumAdapterInfo":{"role":"symbol","title":"HeliumAdapterInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumAdapterInfo"}],"abstract":[{"type":"text","text":"General info about a partner adapter."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumAdapterInfo"}],"url":"\/documentation\/chartboostmediationsdk\/heliumadapterinfo"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium":{"role":"symbol","title":"Helium","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Helium"}],"url":"\/documentation\/chartboostmediationsdk\/helium"},"doc://com.chartboost.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInitializationOptions":{"role":"symbol","title":"HeliumInitializationOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInitializationOptions"}],"abstract":[{"type":"text","text":"Options for Helium initialization."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumInitializationOptions"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminitializationoptions"},"doc://com.chartboost.ChartboostMediationSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(cs)NSObject"},"doc://com.chartboost.ChartboostMediationSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/SQ"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/SH"},"doc://com.chartboost.ChartboostMediationSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/s23CustomStringConvertibleP"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInitializationOptions/init(skippedPartnerIdentifiers:)":{"role":"symbol","title":"init(skippedPartnerIdentifiers:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"skippedPartnerIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PartnerIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK17PartnerIdentifiera"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"HeliumInitializationOptions"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions\/init(skippedPartnerIdentifiers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSkippedPartnerIdentifiers:"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminitializationoptions\/init(skippedpartneridentifiers:)"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerIdentifier":{"role":"symbol","title":"PartnerIdentifier","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerIdentifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"String"},{"type":"text","text":" that identifies a partner."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerIdentifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PartnerIdentifier"}],"url":"\/documentation\/chartboostmediationsdk\/partneridentifier"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInitializationOptions/skippedPartnerIdentifiers":{"role":"symbol","title":"skippedPartnerIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"skippedPartnerIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"PartnerIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK17PartnerIdentifiera"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Set of Partner adapters to skip during Helium SDK initialization."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions\/skippedPartnerIdentifiers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"skippedPartnerIdentifiers"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminitializationoptions\/skippedpartneridentifiers"},"doc://com.chartboost.ChartboostMediationSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/s7CVarArgP"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HeliumInitializationOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HeliumInitializationOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HeliumInitializationOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions\/skippedPartnerIdentifiers"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions\/init(skippedPartnerIdentifiers:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Initializing the SDK","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInitializationOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumAdapterInfo\/title","value":"HeliumAdapterInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumAdapterInfo\/fragments","value":[{"kind":"identifier","text":"HeliumAdapterInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium\/title","value":"Helium"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Helium\/fragments","value":[{"kind":"identifier","text":"Helium"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions\/title","value":"HeliumInitializationOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions\/fragments","value":[{"kind":"identifier","text":"HeliumInitializationOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions~1init(skippedPartnerIdentifiers:)\/title","value":"initWithSkippedPartnerIdentifiers:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions~1init(skippedPartnerIdentifiers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSkippedPartnerIdentifiers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions~1skippedPartnerIdentifiers\/title","value":"skippedPartnerIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions~1skippedPartnerIdentifiers\/fragments","value":[{"kind":"identifier","text":"skippedPartnerIdentifiers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}