{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/cbmpartneradapterconfiguration\/adapterversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/cbmpartneradapterconfiguration\/adapterversion"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMPartnerAdapterConfiguration\/adapterVersion","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adapterVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"required":true,"symbolKind":"property","roleHeading":"Type Property","role":"symbol","externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMPartnerAdapterConfiguration(cpy)adapterVersion","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"text":"adapterVersion","kind":"identifier"}],"title":"adapterVersion","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adapterVersion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"sections":[],"abstract":[{"type":"text","text":"The version of the adapter."},{"type":"text","text":" "},{"text":"It should have either 5 or 6 digits separated by periods, where the first digit is Chartboost Mediation SDK’s major version, the","type":"text"},{"text":" ","type":"text"},{"text":"last digit is the adapter’s build version, and intermediate digits are the partner SDK’s version.","type":"text"},{"type":"text","text":" "},{"text":"Format: ","type":"text"},{"code":"<Chartboost Mediation major version>.<Partner major version>.<Partner minor version>.<Partner patch version>. <Partner build version>.<Adapter build version>","type":"codeVoice"},{"type":"text","text":" where "},{"code":".<Partner build version>","type":"codeVoice"},{"type":"text","text":" is optional."}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CBMPartnerAdapterConfiguration/adapterVersion":{"url":"\/documentation\/chartboostmediationsdk\/cbmpartneradapterconfiguration\/adapterversion","kind":"symbol","required":true,"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adapterVersion"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","abstract":[{"type":"text","text":"The version of the adapter."},{"type":"text","text":" "},{"type":"text","text":"It should have either 5 or 6 digits separated by periods, where the first digit is Chartboost Mediation SDK’s major version, the"},{"type":"text","text":" "},{"text":"last digit is the adapter’s build version, and intermediate digits are the partner SDK’s version.","type":"text"},{"type":"text","text":" "},{"text":"Format: ","type":"text"},{"code":"<Chartboost Mediation major version>.<Partner major version>.<Partner minor version>.<Partner patch version>. <Partner build version>.<Adapter build version>","type":"codeVoice"},{"type":"text","text":" where "},{"type":"codeVoice","code":".<Partner build version>"},{"type":"text","text":" is optional."}],"navigatorTitle":[{"text":"adapterVersion","kind":"identifier"}],"title":"adapterVersion","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMPartnerAdapterConfiguration\/adapterVersion"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PartnerAdapterConfiguration","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/partneradapterconfiguration","navigatorTitle":[{"text":"PartnerAdapterConfiguration","kind":"identifier"}],"title":"PartnerAdapterConfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterConfiguration","abstract":[{"type":"text","text":"A configuration type that contains adapter and partner info."},{"text":" ","type":"text"},{"type":"text","text":"It may also be used to expose custom partner SDK options to the publisher."}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"adapterVersion","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"adapterVersion","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"adapterVersion","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"adapterVersion","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMPartnerAdapterConfiguration~1adapterVersion\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMPartnerAdapterConfiguration~1adapterVersion\/fragments","op":"replace","value":[{"text":"adapterVersion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/title","op":"replace","value":"CBMPartnerAdapterConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"CBMPartnerAdapterConfiguration"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}