{"sections":[],"abstract":[{"type":"text","text":"A brief description of what triggered the error."},{"type":"text","text":" "},{"text":"In Objective-C, access this value in the ","type":"text"},{"type":"codeVoice","code":"ChartboostMediationError.userInfo"},{"text":" dictionary","type":"text"},{"type":"text","text":" "},{"text":"with the key ","type":"text"},{"type":"codeVoice","code":"NSLocalizedDescriptionKey"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/message","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"s:22ChartboostMediationSDK0aB5ErrorC4CodeO7messageSSvp","roleHeading":"Instance Property","title":"message","role":"symbol","extendedModule":"ChartboostMediationSDK","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","modules":[{"name":"ChartboostMediationSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/message"]}],"kind":"symbol","references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"abstract":[{"type":"text","text":"Chartboost Mediation SDK error codes."}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code","role":"symbol","title":"ChartboostMediationError.Code","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code/message":{"abstract":[{"type":"text","text":"A brief description of what triggered the error."},{"type":"text","text":" "},{"text":"In Objective-C, access this value in the ","type":"text"},{"code":"ChartboostMediationError.userInfo","type":"codeVoice"},{"text":" dictionary","type":"text"},{"text":" ","type":"text"},{"text":"with the key ","type":"text"},{"code":"NSLocalizedDescriptionKey","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","title":"message","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/message","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/message","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError":{"navigatorTitle":[{"text":"ChartboostMediationError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","abstract":[{"type":"text","text":"Error type passed by the Chartboost Mediation SDK in its public delegate methods to provide context relative to the failure of a"},{"type":"text","text":" "},{"type":"text","text":"certain operation."}],"title":"ChartboostMediationError","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChartboostMediationError","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"CBMError","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CBMError"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/navigatorTitle","value":[{"kind":"identifier","text":"CBMError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}