{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prebidFailureUnknown"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"There was an error that was not accounted for."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code"]]},"metadata":{"role":"symbol","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"prebidFailureUnknown","kind":"identifier"}],"externalID":"s:22ChartboostMediationSDK0aB5ErrorC4CodeO20prebidFailureUnknownyA2EmF","symbolKind":"case","title":"ChartboostMediationError.Code.prebidFailureUnknown","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/prebidFailureUnknown"},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/prebidfailureunknown"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError":{"navigatorTitle":[{"text":"ChartboostMediationError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChartboostMediationError","kind":"identifier"}],"abstract":[{"text":"Error type passed by the Chartboost Mediation SDK in its public delegate methods to provide context relative to the failure of a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"certain operation."}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror","title":"ChartboostMediationError","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code/prebidFailureUnknown":{"type":"topic","abstract":[{"text":"There was an error that was not accounted for.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"prebidFailureUnknown","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/prebidfailureunknown","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/prebidFailureUnknown","title":"ChartboostMediationError.Code.prebidFailureUnknown","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"role":"symbol","title":"ChartboostMediationError.Code","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Chartboost Mediation SDK error codes."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/title","value":"CBMError"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/fragments","value":[{"kind":"identifier","text":"CBMError"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/navigatorTitle","value":[{"text":"CBMError","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}