{"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/prebidFailureUnsupportedAdFormat","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The partner does not support that ad format."}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/prebidfailureunsupportedadformat"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"ChartboostMediationError.Code.prebidFailureUnsupportedAdFormat","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prebidFailureUnsupportedAdFormat"}],"roleHeading":"Case","symbolKind":"case","externalID":"s:22ChartboostMediationSDK0aB5ErrorC4CodeO32prebidFailureUnsupportedAdFormatyA2EmF","modules":[{"name":"ChartboostMediationSDK"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prebidFailureUnsupportedAdFormat"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"role":"symbol","title":"ChartboostMediationError.Code","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Chartboost Mediation SDK error codes."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code/prebidFailureUnsupportedAdFormat":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/prebidFailureUnsupportedAdFormat","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/prebidfailureunsupportedadformat","abstract":[{"type":"text","text":"The partner does not support that ad format."}],"title":"ChartboostMediationError.Code.prebidFailureUnsupportedAdFormat","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prebidFailureUnsupportedAdFormat"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError":{"navigatorTitle":[{"text":"ChartboostMediationError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChartboostMediationError","kind":"identifier"}],"abstract":[{"text":"Error type passed by the Chartboost Mediation SDK in its public delegate methods to provide context relative to the failure of a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"certain operation."}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror","title":"ChartboostMediationError","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"CBMError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMError"}]},{"value":[{"text":"CBMError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}