{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prebidFailurePartnerNotIntegrated","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prebidFailurePartnerNotIntegrated"}],"roleHeading":"Case","externalID":"s:22ChartboostMediationSDK0aB5ErrorC4CodeO33prebidFailurePartnerNotIntegratedyA2EmF","symbolKind":"case","role":"symbol","title":"ChartboostMediationError.Code.prebidFailurePartnerNotIntegrated","modules":[{"name":"ChartboostMediationSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The partner adapter and\/or SDK might not have been properly integrated."}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/prebidfailurepartnernotintegrated"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/prebidFailurePartnerNotIntegrated"},"sections":[],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"role":"symbol","title":"ChartboostMediationError.Code","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Chartboost Mediation SDK error codes."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError":{"navigatorTitle":[{"text":"ChartboostMediationError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChartboostMediationError","kind":"identifier"}],"abstract":[{"text":"Error type passed by the Chartboost Mediation SDK in its public delegate methods to provide context relative to the failure of a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"certain operation."}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror","title":"ChartboostMediationError","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code/prebidFailurePartnerNotIntegrated":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prebidFailurePartnerNotIntegrated"}],"title":"ChartboostMediationError.Code.prebidFailurePartnerNotIntegrated","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/prebidFailurePartnerNotIntegrated","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/prebidfailurepartnernotintegrated","abstract":[{"type":"text","text":"The partner adapter and\/or SDK might not have been properly integrated."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/title","value":"CBMError"},{"op":"replace","value":[{"text":"CBMError","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/fragments"},{"value":[{"kind":"identifier","text":"CBMError"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/navigatorTitle","op":"replace"}]}]}