{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"s:22ChartboostMediationSDK0aB5ErrorC4CodeO26showFailureAdapterNotFoundyA2EmF","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showFailureAdapterNotFound"}],"title":"ChartboostMediationError.Code.showFailureAdapterNotFound","modules":[{"name":"ChartboostMediationSDK"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/showfailureadapternotfound"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/showFailureAdapterNotFound","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"showFailureAdapterNotFound","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"text":"The adapter instance responsible to this show operation is no longer in memory.","type":"text"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"abstract":[{"type":"text","text":"Chartboost Mediation SDK error codes."}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code","role":"symbol","title":"ChartboostMediationError.Code","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code/showFailureAdapterNotFound":{"kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/showfailureadapternotfound","role":"symbol","abstract":[{"type":"text","text":"The adapter instance responsible to this show operation is no longer in memory."}],"title":"ChartboostMediationError.Code.showFailureAdapterNotFound","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"showFailureAdapterNotFound","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/showFailureAdapterNotFound"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError":{"navigatorTitle":[{"text":"ChartboostMediationError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","abstract":[{"type":"text","text":"Error type passed by the Chartboost Mediation SDK in its public delegate methods to provide context relative to the failure of a"},{"type":"text","text":" "},{"type":"text","text":"certain operation."}],"title":"ChartboostMediationError","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChartboostMediationError","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBMError","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMError"}]},{"value":[{"text":"CBMError","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/navigatorTitle","op":"replace"}]}]}