// Copyright 2022-2023 Chartboost, Inc.
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

import Foundation

/// Data used to send a client to server request when the user has earned a reward.
struct RewardedCallback: Equatable {
    /// Estimated revenue generated by the ad.
    let adRevenue: Decimal?
    /// Estimated CPM of the ad.
    let cpmPrice: Decimal?
    /// Identifier for thet partner that served the ad.
    let partnerIdentifier: PartnerIdentifier
    /// The URL to transmit the rewarded callback to.
    let urlString: String
    /// The HTTP method, e.g. GET or POST
    let method: HTTP.Method
    /// The maximum number of retries.
    let maxRetries: Int
    /// The amount of time to wait between each retry.
    let retryDelay: TimeInterval
    /// A JSON body of data to transmit.
    let body: String?
}
