{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenAdQueueDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdQueueDelegate","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/delegate"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"]]},"abstract":[{"type":"text","text":"The delegate is notified each time an ad load completes and each time a queued ad expires."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/delegate"},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdQueueDelegate","text":"FullscreenAdQueueDelegate"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"symbolKind":"property","title":"delegate","role":"symbol","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue(py)delegate"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueueDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenAdQueueDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol for getting notified about "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","isActive":true},{"type":"text","text":" events."}],"title":"FullscreenAdQueueDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdQueueDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueuedelegate","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueueDelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"abstract":[{"text":"Manages the pre-loading of fullscreen ads. Each ","type":"text"},{"type":"codeVoice","code":"FullscreenAdQueue"},{"text":" manages ads for one placement.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","role":"symbol","title":"FullscreenAdQueue","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdQueue"}],"navigatorTitle":[{"text":"FullscreenAdQueue","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue/delegate":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenAdQueueDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdQueueDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/delegate","abstract":[{"type":"text","text":"The delegate is notified each time an ad load completes and each time a queued ad expires."}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/delegate","kind":"symbol","title":"delegate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<CBMFullscreenAdQueueDelegate>","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdQueueDelegate","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"CBMFullscreenAdQueueDelegate","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdQueueDelegate"}]},{"value":[{"text":"CBMFullscreenAdQueueDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueueDelegate\/navigatorTitle","op":"replace"},{"value":"CBMFullscreenAdQueue","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAdQueue"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/navigatorTitle","op":"replace","value":[{"text":"CBMFullscreenAdQueue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue~1delegate\/title","value":"delegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]}]}]}