{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/getNextAd()"},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/getnextad()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/getnextad()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNextAd"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","text":"FullscreenAd"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"title":"getNextAd()","modules":[{"name":"ChartboostMediationSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue(im)getNextAd","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getNextAd","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"getNextAd","kind":"identifier"}]},"abstract":[{"text":"Returns the oldest ad in the queue, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the queue is empty"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"abstract":[{"text":"Manages the pre-loading of fullscreen ads. Each ","type":"text"},{"type":"codeVoice","code":"FullscreenAdQueue"},{"text":" manages ads for one placement.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","role":"symbol","title":"FullscreenAdQueue","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdQueue"}],"navigatorTitle":[{"text":"FullscreenAdQueue","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue/getNextAd()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getNextAd","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd"},{"text":"?","kind":"text"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/getnextad()","navigatorTitle":[{"text":"getNextAd","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/getNextAd()","title":"getNextAd()","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Returns the oldest ad in the queue, or "},{"type":"codeVoice","code":"nil"},{"text":" if the queue is empty","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"title":"FullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenAd","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenAd"}],"type":"topic","abstract":[{"text":"A Chartboost Mediation fullscreen ad ready to be shown.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"getNextAd","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getNextAd"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","text":"CBMFullscreenAd"},{"text":" *) ","kind":"text"},{"text":"getNextAd","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"CBMFullscreenAdQueue","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdQueue"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/navigatorTitle","value":[{"text":"CBMFullscreenAdQueue","kind":"identifier"}]},{"op":"replace","value":"getNextAd","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue~1getNextAd()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue~1getNextAd()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getNextAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title","value":"CBMFullscreenAd","op":"replace"},{"op":"replace","value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAd"}]}]}]}