{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"keywords","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/keywords"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/keywords"]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue(py)keywords","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"keywords","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"symbolKind":"property","title":"keywords","modules":[{"name":"ChartboostMediationSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"keywords"}]},"abstract":[{"type":"text","text":"This keyword dictionary is used in each "},{"type":"codeVoice","code":"AdLoadRequest"},{"type":"text","text":" sent by the queue."}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/keywords","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue/keywords":{"abstract":[{"text":"This keyword dictionary is used in each ","type":"text"},{"type":"codeVoice","code":"AdLoadRequest"},{"type":"text","text":" sent by the queue."}],"role":"symbol","title":"keywords","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/keywords","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keywords"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/keywords","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"keywords"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"title":"FullscreenAdQueue","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"FullscreenAdQueue","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdQueue"}],"abstract":[{"type":"text","text":"Manages the pre-loading of fullscreen ads. Each "},{"type":"codeVoice","code":"FullscreenAdQueue"},{"type":"text","text":" manages ads for one placement."}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"keywords","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"keywords","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"text":" * ","kind":"text"},{"text":"keywords","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue~1keywords\/title","value":"keywords"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue~1keywords\/fragments","value":[{"text":"keywords","kind":"identifier"}],"op":"replace"},{"value":"CBMFullscreenAdQueue","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments","value":[{"text":"CBMFullscreenAdQueue","kind":"identifier"}]},{"op":"replace","value":[{"text":"CBMFullscreenAdQueue","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/navigatorTitle"}]}]}