{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/queue(forplacement:)"]},{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/queue(forplacement:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/queue(forPlacement:)"},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue(cm)queueForPlacement:","symbolKind":"method","navigatorTitle":[{"text":"queueForPlacement:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPlacement","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","text":"FullscreenAdQueue","kind":"typeIdentifier"}],"title":"queue(forPlacement:)","roleHeading":"Type Method","modules":[{"name":"ChartboostMediationSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queue"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPlacement"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"placement"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"typeIdentifier","text":"FullscreenAdQueue"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Identifier for the Chartboost placement this queue should load ads from."}],"type":"paragraph"}],"name":"placement"}]}],"abstract":[{"type":"text","text":"Returns a FullscreenAdQueue. Queue will not begin loading ads until "},{"type":"codeVoice","code":"startRunning()"},{"type":"text","text":" is called."},{"type":"text","text":" "},{"type":"text","text":"Calling "},{"type":"codeVoice","code":"FullscreenAdQueue.queue(forPlacement:)"},{"text":" more than once with the same placement ID","type":"text"},{"type":"text","text":" "},{"text":"returns the same object each time.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","titleInlineContent":[{"text":"Chartboost Developers","type":"text"}],"url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","type":"link","title":"Chartboost Developers"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"title":"FullscreenAdQueue","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdQueue"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenAdQueue","kind":"identifier"}],"abstract":[{"type":"text","text":"Manages the pre-loading of fullscreen ads. Each "},{"code":"FullscreenAdQueue","type":"codeVoice"},{"text":" manages ads for one placement.","type":"text"}],"type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue/queue(forPlacement:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"queue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPlacement","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","text":"FullscreenAdQueue","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/queue(forPlacement:)","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/queue(forplacement:)","navigatorTitle":[{"text":"queueForPlacement:","kind":"identifier"}],"title":"queue(forPlacement:)","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Returns a FullscreenAdQueue. Queue will not begin loading ads until ","type":"text"},{"type":"codeVoice","code":"startRunning()"},{"text":" is called.","type":"text"},{"type":"text","text":" "},{"text":"Calling ","type":"text"},{"type":"codeVoice","code":"FullscreenAdQueue.queue(forPlacement:)"},{"type":"text","text":" more than once with the same placement ID"},{"text":" ","type":"text"},{"type":"text","text":"returns the same object each time."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"queueForPlacement:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"queueForPlacement:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue","text":"CBMFullscreenAdQueue","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"},{"text":" *) ","kind":"text"},{"text":"queueForPlacement:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"placement","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"CBMFullscreenAdQueue","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdQueue"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue~1queue(forPlacement:)\/title","value":"queueForPlacement:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue~1queue(forPlacement:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"queueForPlacement:","kind":"identifier"}],"op":"replace"}]}]}