{"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/start()","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/start()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/start()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ChartboostMediationSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"start"}],"symbolKind":"method","title":"start()","role":"symbol","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdQueue(im)start"},"abstract":[{"type":"text","text":"Tell the queue to begin running. When running, the queue will load ads until it reaches full capacity. If ads are removed from"},{"text":" ","type":"text"},{"type":"text","text":"a running queue, it will resume loading in order to replace them. To stop a running queue, call "},{"type":"codeVoice","code":"stop()"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Calling ","type":"text"},{"code":"start()","type":"codeVoice"},{"type":"text","text":" on a running queue does nothing."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue/start()":{"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/start()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"start","kind":"identifier"}],"title":"start()","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/start()","type":"topic","abstract":[{"type":"text","text":"Tell the queue to begin running. When running, the queue will load ads until it reaches full capacity. If ads are removed from"},{"type":"text","text":" "},{"type":"text","text":"a running queue, it will resume loading in order to replace them. To stop a running queue, call "},{"code":"stop()","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Calling "},{"type":"codeVoice","code":"start()"},{"type":"text","text":" on a running queue does nothing."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"abstract":[{"text":"Manages the pre-loading of fullscreen ads. Each ","type":"text"},{"type":"codeVoice","code":"FullscreenAdQueue"},{"text":" manages ads for one placement.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","role":"symbol","title":"FullscreenAdQueue","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdQueue"}],"navigatorTitle":[{"text":"FullscreenAdQueue","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"start","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"start","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue~1start()\/title","value":"start","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue~1start()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}],"op":"replace"},{"value":"CBMFullscreenAdQueue","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/title","op":"replace"},{"op":"replace","value":[{"text":"CBMFullscreenAdQueue","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/fragments"},{"value":[{"kind":"identifier","text":"CBMFullscreenAdQueue"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdQueue\/navigatorTitle","op":"replace"}]}]}