{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/stop()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/stop()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/stop()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Stops a running queue so that it will not send any more ad load requests. One additional ad may be loaded into the queue after"},{"type":"text","text":" "},{"type":"text","text":"calling this if there is already a request “in flight”. Calling "},{"type":"codeVoice","code":"stop()"},{"type":"text","text":" on a stopped queue does nothing."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"title":"stop()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationFullscreenAdQueue(im)stop","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue":{"role":"symbol","title":"FullscreenAdQueue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAdQueue"}],"abstract":[{"type":"text","text":"Manages the pre-loading of fullscreen ads. Each "},{"type":"codeVoice","code":"FullscreenAdQueue"},{"type":"text","text":" manages ads for one placement."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdQueue"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdQueue/stop()":{"role":"symbol","title":"stop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops a running queue so that it will not send any more ad load requests. One additional ad may be loaded into the queue after"},{"type":"text","text":" "},{"type":"text","text":"calling this if there is already a request “in flight”. Calling "},{"type":"codeVoice","code":"stop()"},{"type":"text","text":" on a stopped queue does nothing."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdQueue\/stop()","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/fullscreenadqueue\/stop()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"stop"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}