{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"View controller used to present the ad."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When complete, the delegate method"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAdDelegate\/heliumBannerAd(placementName:requestIdentifier:winningBidInfo:didLoadWithError:)"},{"type":"text","text":" "},{"type":"text","text":"will be invoked."},{"type":"text","text":" "},{"type":"text","text":"When the banner view is visible in the app’s view hierarchy it will automatically present the loaded ad."},{"type":"text","text":" "},{"type":"text","text":"Calling this method will start the banner auto-refresh process."},{"type":"text","text":" "},{"type":"text","text":"Only one "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAdDelegate\/heliumBannerAd(placementName:requestIdentifier:winningBidInfo:didLoadWithError:)"},{"type":"text","text":" call will be"},{"type":"text","text":" "},{"type":"text","text":"made per "},{"type":"codeVoice","code":"load(with:)"},{"type":"text","text":" call, even if more ads are loaded as result of the banner auto-refresh process."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/heliumbannerview\/load(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/heliumbannerview\/load(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView\/load(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Asynchronously loads an ad."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"title":"load(with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)HeliumBannerView(im)loadAdWithViewController:","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerView/load(with:)":{"role":"symbol","title":"load(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Asynchronously loads an ad."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView\/load(with:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/heliumbannerview\/load(with:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerView":{"role":"symbol","title":"HeliumBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumBannerView"}],"abstract":[{"type":"text","text":"Helium banner ad view."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumBannerView"}],"url":"\/documentation\/chartboostmediationsdk\/heliumbannerview"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerAdDelegate/heliumBannerAd(placementName:requestIdentifier:winningBidInfo:didLoadWithError:)":{"role":"symbol","title":"heliumBannerAd(placementName:requestIdentifier:winningBidInfo:didLoadWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumBannerAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"placementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requestIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"winningBidInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"didLoadWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Ad finished loading with an optional error."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAdDelegate\/heliumBannerAd(placementName:requestIdentifier:winningBidInfo:didLoadWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/heliumbanneraddelegate\/heliumbannerad(placementname:requestidentifier:winningbidinfo:didloadwitherror:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"loadAdWithViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}