{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumRewardedAdDidRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"placementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"placementName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Placement associated with the impression event."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate\/heliumrewardedaddidrecordimpression(withplacementname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate\/heliumrewardedaddidrecordimpression(withplacementname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAdDidRecordImpression(withPlacementName:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Ad impression recorded by Helium as result of an ad being shown."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumRewardedAdDidRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"heliumRewardedAdDidRecordImpression(withPlacementName:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumRewardedAdDelegate(im)heliumRewardedAdDidRecordImpressionWithPlacementName:","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"heliumRewardedAdDidRecordImpressionWithPlacementName:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumRewardedAdDelegate/heliumRewardedAdDidRecordImpression(withPlacementName:)":{"role":"symbol","title":"heliumRewardedAdDidRecordImpression(withPlacementName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumRewardedAdDidRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Ad impression recorded by Helium as result of an ad being shown."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate\/heliumRewardedAdDidRecordImpression(withPlacementName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"heliumRewardedAdDidRecordImpressionWithPlacementName:"}],"url":"\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate\/heliumrewardedaddidrecordimpression(withplacementname:)"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumRewardedAd":{"role":"symbol","title":"HeliumRewardedAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumRewardedAd"}],"abstract":[{"type":"text","text":"Helium rewarded ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumRewardedAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliumrewardedad"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHeliumRewardedAdDelegate":{"role":"symbol","title":"CHBHeliumRewardedAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"}],"abstract":[{"type":"text","text":"Callbacks for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHeliumRewardedAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/chbheliumrewardedaddelegate"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"heliumRewardedAdDidRecordImpressionWithPlacementName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"heliumRewardedAdDidRecordImpressionWithPlacementName:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"heliumRewardedAdDidRecordImpressionWithPlacementName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"placementName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CHBHeliumRewardedAdDelegate~1heliumRewardedAdDidRecordImpression(withPlacementName:)\/title","value":"heliumRewardedAdDidRecordImpressionWithPlacementName:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CHBHeliumRewardedAdDelegate~1heliumRewardedAdDidRecordImpression(withPlacementName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"heliumRewardedAdDidRecordImpressionWithPlacementName:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumRewardedAd\/title","value":"HeliumRewardedAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumRewardedAd\/fragments","value":[{"kind":"identifier","text":"HeliumRewardedAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CHBHeliumRewardedAdDelegate\/title","value":"CHBHeliumRewardedAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CHBHeliumRewardedAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBHeliumRewardedAdDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}