{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationbannertype\/fixed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationbannertype\/fixed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerType\/fixed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The banner ad is a fixed size, and will not change when the size of the containing"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView"},{"type":"text","text":" changes."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixed"}],"title":"ChartboostMediationBannerType.fixed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChartboostMediationSDK@E@ChartboostMediationBannerType@ChartboostMediationBannerTypeFixed","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerTypeFixed"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerType"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerType":{"role":"symbol","title":"ChartboostMediationBannerType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerType"}],"abstract":[{"type":"text","text":"The type of a banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerType"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannertype"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView":{"role":"symbol","title":"ChartboostMediationBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerView"}],"abstract":[{"type":"text","text":"A view that can load and display a Chartboost Mediation banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerView"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerType/fixed":{"role":"symbol","title":"ChartboostMediationBannerType.fixed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixed"}],"abstract":[{"type":"text","text":"The banner ad is a fixed size, and will not change when the size of the containing"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView"},{"type":"text","text":" changes."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerType\/fixed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerTypeFixed"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannertype\/fixed"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ChartboostMediationBannerTypeFixed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerTypeFixed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ChartboostMediationBannerTypeFixed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerType\/title","value":"ChartboostMediationBannerType"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerType\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView\/title","value":"ChartboostMediationBannerView"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerType~1fixed\/title","value":"ChartboostMediationBannerTypeFixed"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerType~1fixed\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerTypeFixed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}