{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/loglevel\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/loglevel\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogLevel\/none","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No logging is expected to be performed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"LogLevel.none","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChartboostMediationSDK@E@ChartboostMediationLogLevel@ChartboostMediationLogLevelNone","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationLogLevelNone"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogLevel"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogLevel":{"role":"symbol","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[{"type":"text","text":"Log severity levels for the unified logging subsystem."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/chartboostmediationsdk\/loglevel"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogLevel/none":{"role":"symbol","title":"LogLevel.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"No logging is expected to be performed."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogLevel\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationLogLevelNone"}],"url":"\/documentation\/chartboostmediationsdk\/loglevel\/none"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ChartboostMediationLogLevelNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationLogLevelNone"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ChartboostMediationLogLevelNone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1LogLevel\/title","value":"ChartboostMediationLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1LogLevel\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1LogLevel~1none\/title","value":"ChartboostMediationLogLevelNone"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1LogLevel~1none\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationLogLevelNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}