{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumDidReceiveILRD"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To listen for ILRD notification events, register a notification handler using this constant as the notification name."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"[NSNotificationCenter.defaultCenter addObserverForName:kHeliumDidReceiveILRDNotification"},{"type":"text","text":" "},{"type":"text","text":"object:nil"},{"type":"text","text":" "},{"type":"text","text":"queue:nil"},{"type":"text","text":" "},{"type":"text","text":"usingBlock:^(NSNotification * _Nonnull notification) {"},{"type":"text","text":" "},{"type":"text","text":"\/\/ Extract the ILRD payload."},{"type":"text","text":" "},{"type":"text","text":"HeliumImpressionData *ilrd = (HeliumImpressionData *)notification.object;"},{"type":"text","text":" "},{"type":"text","text":"NSString *placement = ilrd.placement;"},{"type":"text","text":" "},{"type":"text","text":"NSDictionary *json = ilrd.jsonData;"},{"type":"text","text":" "},{"type":"text","text":"}];"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/foundation\/nsnotification\/name\/heliumdidreceiveilrd-28zza"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/foundation\/nsnotification\/name\/heliumdidreceiveilrd-28zza"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Foundation\/NSNotification\/Name\/heliumDidReceiveILRD-28zza","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"kHeliumDidReceiveILRDNotification"}],"role":"symbol","title":"heliumDidReceiveILRD","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumDidReceiveILRD"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"symbolKind":"property","externalID":"c:@kHeliumDidReceiveILRDNotification","modules":[{"name":"ChartboostMediationSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"references":{"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Foundation/NSNotification/Name/heliumDidReceiveILRD-28zza":{"deprecated":true,"role":"symbol","title":"heliumDidReceiveILRD","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumDidReceiveILRD"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Foundation\/NSNotification\/Name\/heliumDidReceiveILRD-28zza","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHeliumDidReceiveILRDNotification"}],"url":"\/documentation\/chartboostmediationsdk\/foundation\/nsnotification\/name\/heliumdidreceiveilrd-28zza"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"kHeliumDidReceiveILRDNotification"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHeliumDidReceiveILRDNotification"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"kHeliumDidReceiveILRDNotification"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Foundation~1NSNotification~1Name~1heliumDidReceiveILRD-28zza\/title","value":"kHeliumDidReceiveILRDNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Foundation~1NSNotification~1Name~1heliumDidReceiveILRD-28zza\/fragments","value":[{"kind":"identifier","text":"kHeliumDidReceiveILRDNotification"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}