{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumDidReceiveInitResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To listen for initialization result notification events, register a notification handler using this constant as the notification name."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"[NSNotificationCenter.defaultCenter addObserverForName:kHeliumDidReceiveInitResultsNotification"},{"type":"text","text":" "},{"type":"text","text":"object:nil"},{"type":"text","text":" "},{"type":"text","text":"queue:nil"},{"type":"text","text":" "},{"type":"text","text":"usingBlock:^(NSNotification * _Nonnull notification) {"},{"type":"text","text":" "},{"type":"text","text":"\/\/ Extract the results payload."},{"type":"text","text":" "},{"type":"text","text":"NSDictionary *results = (NSDictionary *)notification.object;"},{"type":"text","text":" "},{"type":"text","text":"}];"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/foundation\/nsnotification\/name\/heliumdidreceiveinitresults-6hl3c"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/foundation\/nsnotification\/name\/heliumdidreceiveinitresults-6hl3c"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Foundation\/NSNotification\/Name\/heliumDidReceiveInitResults-6hl3c","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"ChartboostMediationSDK","relatedModules":["Foundation"]}],"navigatorTitle":[{"kind":"identifier","text":"kHeliumDidReceiveInitResultsNotification"}],"role":"symbol","title":"heliumDidReceiveInitResults","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumDidReceiveInitResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"symbolKind":"property","externalID":"c:@kHeliumDidReceiveInitResultsNotification","extendedModule":"Foundation","platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Foundation","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Foundation\/NSNotification","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Foundation\/NSNotification\/Name"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Foundation/NSNotification/Name/heliumDidReceiveInitResults-6hl3c":{"deprecated":true,"role":"symbol","title":"heliumDidReceiveInitResults","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"heliumDidReceiveInitResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Foundation\/NSNotification\/Name\/heliumDidReceiveInitResults-6hl3c","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHeliumDidReceiveInitResultsNotification"}],"url":"\/documentation\/chartboostmediationsdk\/foundation\/nsnotification\/name\/heliumdidreceiveinitresults-6hl3c"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Foundation/NSNotification/Name":{"role":"symbol","title":"NSNotification.Name","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"identifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Foundation\/NSNotification\/Name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Name"}],"url":"\/documentation\/chartboostmediationsdk\/foundation\/nsnotification\/name"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Foundation":{"role":"collection","title":"Foundation","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Foundation","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/foundation"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Foundation/NSNotification":{"role":"symbol","title":"NSNotification","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Foundation\/NSNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSNotification"}],"url":"\/documentation\/chartboostmediationsdk\/foundation\/nsnotification"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"kHeliumDidReceiveInitResultsNotification"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHeliumDidReceiveInitResultsNotification"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"kHeliumDidReceiveInitResultsNotification"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Foundation~1NSNotification~1Name~1heliumDidReceiveInitResults-6hl3c\/title","value":"kHeliumDidReceiveInitResultsNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1Foundation~1NSNotification~1Name~1heliumDidReceiveInitResults-6hl3c\/fragments","value":[{"kind":"identifier","text":"kHeliumDidReceiveInitResultsNotification"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}