{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"ChartboostMediationError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMError","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"ad","content":[{"type":"paragraph","inlineContent":[{"text":"The ad that triggered this event.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that caused the closing of the ad, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the closing of the ad was expected."}]}],"name":"error"}]}],"abstract":[{"type":"text","text":"Called when the ad is closed and no longer visible."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didClose(ad:error:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenaddelegate\/didclose(ad:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenaddelegate\/didclose(ad:error:)"]}],"sections":[],"metadata":{"roleHeading":"Instance Method","title":"didClose(ad:error:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didClose"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ad"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","text":"FullscreenAd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMError","text":"ChartboostMediationError"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"didCloseWithAd:error:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate(im)didCloseWithAd:error:","modules":[{"name":"ChartboostMediationSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"title":"FullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenAd","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenAd"}],"type":"topic","abstract":[{"text":"A Chartboost Mediation fullscreen ad ready to be shown.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate/didClose(ad:error:)":{"role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate\/didclose(ad:error:)","abstract":[{"type":"text","text":"Called when the ad is closed and no longer visible."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didClose","kind":"identifier"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd","text":"FullscreenAd"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMError","text":"ChartboostMediationError","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"didClose(ad:error:)","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate\/didClose(ad:error:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"didCloseWithAd:error:"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate":{"navigatorTitle":[{"text":"FullscreenAdDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenAdDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","title":"FullscreenAdDelegate","url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate","kind":"symbol","type":"topic","abstract":[{"text":"A ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"},{"type":"text","text":" delegate that receives ad callbacks."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError":{"navigatorTitle":[{"text":"ChartboostMediationError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","abstract":[{"type":"text","text":"Error type passed by the Chartboost Mediation SDK in its public delegate methods to provide context relative to the failure of a"},{"type":"text","text":" "},{"type":"text","text":"certain operation."}],"title":"ChartboostMediationError","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChartboostMediationError","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"didCloseWithAd:error:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"didCloseWithAd:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didCloseWithAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBMFullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ad"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","kind":"typeIdentifier","text":"CBMError","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"ad","content":[{"inlineContent":[{"type":"text","text":"The ad that triggered this event."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The error that caused the closing of the ad, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the closing of the ad was expected."}]}],"name":"error"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title","value":"CBMFullscreenAd"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAd"}]},{"value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/navigatorTitle"},{"op":"replace","value":"didCloseWithAd:error:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didClose(ad:error:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didCloseWithAd:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate~1didClose(ad:error:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/title","op":"replace","value":"CBMFullscreenAdDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"CBMFullscreenAdDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/fragments"},{"value":[{"text":"CBMFullscreenAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/navigatorTitle","op":"replace"},{"value":"CBMError","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/fragments","value":[{"text":"CBMError","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"CBMError"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}