{"kind":"symbol","abstract":[{"text":"The partner’s unique identifier.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerID"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID","kind":"typeIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa","text":"PartnerID"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo"]]},"metadata":{"role":"symbol","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMPartnerAdapterInfo(py)partnerID","symbolKind":"property","title":"partnerID","navigatorTitle":[{"text":"partnerID","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa","kind":"typeIdentifier","text":"PartnerID"}],"roleHeading":"Instance Property","modules":[{"name":"ChartboostMediationSDK"}]},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/cbmpartneradapterinfo\/partnerid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/cbmpartneradapterinfo\/partnerid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMPartnerAdapterInfo\/partnerID"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CBMPartnerAdapterInfo/partnerID":{"kind":"symbol","abstract":[{"text":"The partner’s unique identifier.","type":"text"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/cbmpartneradapterinfo\/partnerid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"partnerID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22ChartboostMediationSDK9PartnerIDa","text":"PartnerID","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"partnerID"}],"title":"partnerID","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMPartnerAdapterInfo\/partnerID"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerID":{"navigatorTitle":[{"kind":"identifier","text":"PartnerID"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerID","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"PartnerID","kind":"identifier"}],"title":"PartnerID","abstract":[{"text":"A ","type":"text"},{"code":"String","type":"codeVoice"},{"type":"text","text":" that identifies a partner."}],"url":"\/documentation\/chartboostmediationsdk\/partnerid"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterInfo":{"title":"PartnerAdapterInfo","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo","abstract":[{"text":"General info about a partner adapter.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PartnerAdapterInfo"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partneradapterinfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapterInfo"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"partnerID"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"partnerID","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"partnerID","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"partnerID","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMPartnerAdapterInfo~1partnerID\/title"},{"op":"replace","value":[{"text":"partnerID","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMPartnerAdapterInfo~1partnerID\/fragments"},{"op":"replace","value":"CBMPartnerAdapterInfo","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/title"},{"value":[{"text":"CBMPartnerAdapterInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}