{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"skippedPartnerIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK17PartnerIdentifiera","text":"PartnerIdentifier"},{"kind":"text","text":"]?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"skippedPartnerIdentifiers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional partner adapters to skip initialization."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/heliuminitializationoptions\/init(skippedpartneridentifiers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/heliuminitializationoptions\/init(skippedpartneridentifiers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions\/init(skippedPartnerIdentifiers:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"HeliumInitializationOptions"},{"type":"text","text":" instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"skippedPartnerIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PartnerIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK17PartnerIdentifiera"},{"kind":"text","text":"]?)"}],"title":"init(skippedPartnerIdentifiers:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ChartboostMediationSDK@objc(cs)HeliumInitializationOptions(im)initWithSkippedPartnerIdentifiers:","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSkippedPartnerIdentifiers:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInitializationOptions":{"role":"symbol","title":"HeliumInitializationOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInitializationOptions"}],"abstract":[{"type":"text","text":"Options for Helium initialization."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumInitializationOptions"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminitializationoptions"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInitializationOptions/init(skippedPartnerIdentifiers:)":{"role":"symbol","title":"init(skippedPartnerIdentifiers:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"skippedPartnerIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PartnerIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK17PartnerIdentifiera"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"HeliumInitializationOptions"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions\/init(skippedPartnerIdentifiers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSkippedPartnerIdentifiers:"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminitializationoptions\/init(skippedpartneridentifiers:)"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerIdentifier":{"role":"symbol","title":"PartnerIdentifier","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerIdentifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"String"},{"type":"text","text":" that identifies a partner."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerIdentifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PartnerIdentifier"}],"url":"\/documentation\/chartboostmediationsdk\/partneridentifier"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithSkippedPartnerIdentifiers:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSkippedPartnerIdentifiers:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSkippedPartnerIdentifiers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"skippedPartnerIdentifiers"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions\/title","value":"HeliumInitializationOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions\/fragments","value":[{"kind":"identifier","text":"HeliumInitializationOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions~1init(skippedPartnerIdentifiers:)\/title","value":"initWithSkippedPartnerIdentifiers:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumInitializationOptions~1init(skippedPartnerIdentifiers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSkippedPartnerIdentifiers:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}