{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CHBHBannerSize_Leaderboard) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaderboard"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chbhbannersize\/leaderboard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chbhbannersize\/leaderboard"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize\/leaderboard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Leaderboard 728x90 size."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaderboard"}],"title":"CHBHBannerSize.leaderboard","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChartboostMediationSDK@E@CHBHBannerSize@CHBHBannerSize_Leaderboard","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHBannerSize/leaderboard":{"role":"symbol","title":"CHBHBannerSize.leaderboard","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaderboard"}],"abstract":[{"type":"text","text":"Leaderboard 728x90 size."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize\/leaderboard","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbhbannersize\/leaderboard"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHBannerSize":{"role":"symbol","title":"CHBHBannerSize","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHBannerSize"}],"abstract":[{"type":"text","text":"Chartboost Mediation banner size to request."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBHBannerSize"}],"url":"\/documentation\/chartboostmediationsdk\/chbhbannersize"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CHBHBannerSize_Leaderboard"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}