{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CHBHBannerSize_Medium) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"medium"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chbhbannersize\/medium"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chbhbannersize\/medium"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize\/medium","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Medium Rectangle 300x250 size."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"medium"}],"title":"CHBHBannerSize.medium","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChartboostMediationSDK@E@CHBHBannerSize@CHBHBannerSize_Medium","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHBannerSize/medium":{"role":"symbol","title":"CHBHBannerSize.medium","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"medium"}],"abstract":[{"type":"text","text":"Medium Rectangle 300x250 size."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize\/medium","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/chbhbannersize\/medium"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHBannerSize":{"role":"symbol","title":"CHBHBannerSize","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHBannerSize"}],"abstract":[{"type":"text","text":"Chartboost Mediation banner size to request."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBHBannerSize"}],"url":"\/documentation\/chartboostmediationsdk\/chbhbannersize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CHBHBannerSize_Medium"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}