{"seeAlsoSections":[{"title":"Banner Ads","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerSize","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerType","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerLoadRequest","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerLoadResult","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerHorizontalAlignment","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerVerticalAlignment"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerView"}],"title":"ChartboostMediationBannerView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationBannerView","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerView"}]},"abstract":[{"type":"text","text":"A view that can load and display a Chartboost Mediation banner ad."}],"sections":[],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)NSCoding","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)NSObject","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)CALayerDelegate","doc:\/\/com.chartboost.ChartboostMediationSDK\/s7CVarArgP","doc:\/\/com.chartboost.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.chartboost.ChartboostMediationSDK\/s23CustomStringConvertibleP","doc:\/\/com.chartboost.ChartboostMediationSDK\/SQ","doc:\/\/com.chartboost.ChartboostMediationSDK\/SH","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIAppearance","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UICoordinateSpace","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIDynamicItem","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIFocusItem","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIFocusItemContainer","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.chartboost.ChartboostMediationSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/delegate","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/horizontalAlignment","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/intrinsicContentSize","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/isHidden","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/keywords","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/loadMetrics","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/request","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/size","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/verticalAlignment","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/winningBidInfo"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/didMoveToSuperview()","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/layoutSubviews()","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/load(with:viewController:completion:)","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/reset()"]}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerView"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/reset()":{"role":"symbol","title":"reset()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reset"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Clears the loaded ad, removes the currently presented ad if any, and stops the auto-refresh process."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/reset()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reset"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/reset()"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerViewDelegate":{"role":"symbol","title":"ChartboostMediationBannerViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerViewDelegate"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView"},{"type":"text","text":" delegate that receives ad callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerViewDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerviewdelegate"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/horizontalAlignment":{"role":"symbol","title":"horizontalAlignment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationBannerHorizontalAlignment","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@ChartboostMediationBannerHorizontalAlignment"}],"abstract":[{"type":"text","text":"The horizontal alignment of the banner ad within this view, if the size of this view is made larger than the banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/horizontalAlignment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"horizontalAlignment"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/horizontalalignment"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UILargeContentViewerItem"},"doc://com.chartboost.ChartboostMediationSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/SH"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/intrinsicContentSize":{"role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/intrinsicContentSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/intrinsiccontentsize"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIAccessibilityIdentification"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerLoadResult":{"role":"symbol","title":"ChartboostMediationBannerLoadResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerLoadResult"}],"abstract":[{"type":"text","text":"The result of a banner load operation."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerLoadResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerLoadResult"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerloadresult"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/isHidden":{"role":"symbol","title":"isHidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/isHidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hidden"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/ishidden"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/keywords":{"role":"symbol","title":"keywords","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keywords"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Optional keywords that can be associated with the advertisement placement."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/keywords","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keywords"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/keywords"},"doc://com.chartboost.ChartboostMediationSDK/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(cs)UIView"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView":{"role":"symbol","title":"ChartboostMediationBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerView"}],"abstract":[{"type":"text","text":"A view that can load and display a Chartboost Mediation banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerView"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UICoordinateSpace"},"doc://com.chartboost.ChartboostMediationSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/SQ"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/verticalAlignment":{"role":"symbol","title":"verticalAlignment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationBannerVerticalAlignment","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@ChartboostMediationBannerVerticalAlignment"}],"abstract":[{"type":"text","text":"The vertical alignment of the banner ad within this view, if the size of this view is made larger than the banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/verticalAlignment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"verticalAlignment"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/verticalalignment"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/init(frame:)"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)CALayerDelegate"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UITraitEnvironment"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerVerticalAlignment":{"role":"symbol","title":"ChartboostMediationBannerVerticalAlignment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerVerticalAlignment"}],"abstract":[{"type":"text","text":"The vertical alignment of an ad within "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerVerticalAlignment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerVerticalAlignment"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerverticalalignment"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerHorizontalAlignment":{"role":"symbol","title":"ChartboostMediationBannerHorizontalAlignment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerHorizontalAlignment"}],"abstract":[{"type":"text","text":"The horizontal alignment of an ad within "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerHorizontalAlignment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerHorizontalAlignment"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerhorizontalalignment"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIAppearance"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIDynamicItem"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerSize":{"role":"symbol","title":"ChartboostMediationBannerSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerSize"}],"abstract":[{"type":"text","text":"The size of a banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerSize"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannersize"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/layoutsubviews()"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerLoadRequest":{"role":"symbol","title":"ChartboostMediationBannerLoadRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerLoadRequest"}],"abstract":[{"type":"text","text":"A request used to load a banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerLoadRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerLoadRequest"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerloadrequest"},"doc://com.chartboost.ChartboostMediationSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/s7CVarArgP"},"doc://com.chartboost.ChartboostMediationSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/s28CustomDebugStringConvertibleP"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/load(with:viewController:completion:)":{"role":"symbol","title":"load(with:viewController:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationBannerLoadRequest","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationBannerLoadRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChartboostMediationBannerLoadResult","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationBannerLoadResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Loads a banner ad using the information provided in the request."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/load(with:viewController:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadWith:viewController:completion:"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/load(with:viewcontroller:completion:)"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIAppearanceContainer"},"doc://com.chartboost.ChartboostMediationSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/s23CustomStringConvertibleP"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)NSCoding"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationBannerSize"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The actual size of the ad that has been loaded, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if a banner is not loaded."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/size","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"size"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/size"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationBannerViewDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationBannerViewDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The delegate of this banner view."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/delegate"},"doc://com.chartboost.ChartboostMediationSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/5UIKit23UITraitChangeObservableP"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIFocusItem"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/didMoveToSuperview()":{"role":"symbol","title":"didMoveToSuperview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/didMoveToSuperview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didMoveToSuperview"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/didmovetosuperview()"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIResponderStandardEditActions"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIFocusItemContainer"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/winningBidInfo":{"role":"symbol","title":"winningBidInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"winningBidInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Information about the winning bid, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if a banner is not loaded."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/winningBidInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"winningBidInfo"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/winningbidinfo"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/loadMetrics":{"role":"symbol","title":"loadMetrics","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMetrics"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The load metrics for the most recent successful load operation, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if a banner is not loaded."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/loadMetrics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMetrics"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/loadmetrics"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIFocusEnvironment"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.chartboost.ChartboostMediationSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(pl)NSObject"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerView/request":{"role":"symbol","title":"request","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationBannerLoadRequest","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationBannerLoadRequest"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The original "},{"type":"codeVoice","code":"request"},{"type":"text","text":" that "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/load(with:viewController:completion:)"},{"type":"text","text":" was called with, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if a"},{"type":"text","text":" "},{"type":"text","text":"banner is not loaded."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/request","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"request"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannerview\/request"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationBannerType":{"role":"symbol","title":"ChartboostMediationBannerType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerType"}],"abstract":[{"type":"text","text":"The type of a banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationBannerType"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationbannertype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ChartboostMediationBannerView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChartboostMediationBannerView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/delegate","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/horizontalAlignment","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/intrinsicContentSize","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/isHidden","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/keywords","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/loadMetrics","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/request","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/size","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/verticalAlignment","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/winningBidInfo"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/didMoveToSuperview()","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/init(frame:)","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/layoutSubviews()","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/load(with:viewController:completion:)","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerView\/reset()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Banner Ads","identifiers":["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerViewDelegate","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerSize","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerType","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerLoadRequest","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerLoadResult","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerHorizontalAlignment","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationBannerVerticalAlignment"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationBannerView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1reset()\/title","value":"reset"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1reset()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reset"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerViewDelegate\/title","value":"ChartboostMediationBannerViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerViewDelegate\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1horizontalAlignment\/title","value":"horizontalAlignment"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1horizontalAlignment\/fragments","value":[{"kind":"identifier","text":"horizontalAlignment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerLoadResult\/title","value":"ChartboostMediationBannerLoadResult"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerLoadResult\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerLoadResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1isHidden\/title","value":"hidden"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1isHidden\/fragments","value":[{"kind":"identifier","text":"hidden"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1keywords\/title","value":"keywords"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1keywords\/fragments","value":[{"kind":"identifier","text":"keywords"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView\/title","value":"ChartboostMediationBannerView"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1verticalAlignment\/title","value":"verticalAlignment"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1verticalAlignment\/fragments","value":[{"kind":"identifier","text":"verticalAlignment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerVerticalAlignment\/title","value":"ChartboostMediationBannerVerticalAlignment"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerVerticalAlignment\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerVerticalAlignment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerHorizontalAlignment\/title","value":"ChartboostMediationBannerHorizontalAlignment"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerHorizontalAlignment\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerHorizontalAlignment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerSize\/title","value":"ChartboostMediationBannerSize"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerSize\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerLoadRequest\/title","value":"ChartboostMediationBannerLoadRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerLoadRequest\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerLoadRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1load(with:viewController:completion:)\/title","value":"loadWith:viewController:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1load(with:viewController:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadWith:viewController:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1didMoveToSuperview()\/title","value":"didMoveToSuperview"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1didMoveToSuperview()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToSuperview"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1winningBidInfo\/title","value":"winningBidInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1winningBidInfo\/fragments","value":[{"kind":"identifier","text":"winningBidInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1loadMetrics\/title","value":"loadMetrics"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1loadMetrics\/fragments","value":[{"kind":"identifier","text":"loadMetrics"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1request\/title","value":"request"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerView~1request\/fragments","value":[{"kind":"identifier","text":"request"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerType\/title","value":"ChartboostMediationBannerType"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationBannerType\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationBannerType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}