{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/top"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/bannerverticalalignment\/top"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/bannerverticalalignment\/top"]}],"abstract":[{"type":"text","text":"The ad will be displayed at the top of the view."}],"metadata":{"navigatorTitle":[{"text":"CBMBannerVerticalAlignmentTop","kind":"identifier"}],"externalID":"c:@M@ChartboostMediationSDK@E@CBMBannerVerticalAlignment@CBMBannerVerticalAlignmentTop","title":"BannerVerticalAlignment.top","role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"top","kind":"identifier"}],"modules":[{"name":"ChartboostMediationSDK"}]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","abstract":[{"type":"text","text":"A view that can load and display a Chartboost Mediation banner ad."}],"role":"symbol","title":"BannerAdView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerAdView","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BannerAdView","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment/top":{"role":"symbol","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment\/top","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment\/top","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"}],"title":"BannerVerticalAlignment.top","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBMBannerVerticalAlignmentTop"}],"abstract":[{"type":"text","text":"The ad will be displayed at the top of the view."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerVerticalAlignment":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerVerticalAlignment","abstract":[{"type":"text","text":"The vertical alignment of an ad within "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","type":"reference","isActive":true},{"text":".","type":"text"}],"role":"symbol","title":"BannerVerticalAlignment","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerVerticalAlignment","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BannerVerticalAlignment","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/bannerverticalalignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"CBMBannerVerticalAlignmentTop","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"CBMBannerVerticalAlignmentTop","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"CBMBannerVerticalAlignmentTop","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","value":"CBMBannerAdView"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMBannerAdView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment~1top\/title","op":"replace","value":"CBMBannerVerticalAlignmentTop"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment~1top\/fragments","value":[{"kind":"identifier","text":"CBMBannerVerticalAlignmentTop"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/title","value":"CBMBannerVerticalAlignment","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerVerticalAlignment\/fragments","op":"replace","value":[{"text":"CBMBannerVerticalAlignment","kind":"identifier"}]}]}]}