{"metadata":{"roleHeading":"Type Method","title":"adaptive(width:maxHeight:)","role":"symbol","navigatorTitle":[{"text":"adaptiveWithWidth:maxHeight:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptive"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"maxHeight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","text":"BannerSize","kind":"typeIdentifier"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize(cm)adaptiveWithWidth:maxHeight:","modules":[{"name":"ChartboostMediationSDK"}],"symbolKind":"method"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive(width:maxHeight:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/adaptive(width:maxheight:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/adaptive(width:maxheight:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adaptive","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier","text":"BannerSize"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"width","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum width for the banner."}]}]},{"name":"maxHeight","content":[{"inlineContent":[{"text":"The maximum height for the banner.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"code":"BannerSize","type":"codeVoice"},{"type":"text","text":" that can be used to load a banner."}]}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"This will generally be used when requesting an anchored adaptive banner, or when requesting an inline adaptive banner where","type":"text"},{"text":" ","type":"text"},{"text":"the maximum height should be constained. To request an adaptive size banner without a ","type":"text"},{"type":"codeVoice","code":"maxHeight"},{"text":", use","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive(width:)","isActive":true},{"type":"text","text":" instead."}],"type":"paragraph"},{"style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"This is only a maximum banner size. Depending on how your waterfall is configured, smaller or different aspect ratio"},{"text":" ","type":"text"},{"type":"text","text":"ads may be served."}],"type":"paragraph"}],"name":"Note"}]}],"abstract":[{"type":"text","text":"Returns a size for an adaptive banner with the specified "},{"type":"codeVoice","code":"width"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxHeight"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize/adaptive(width:)":{"abstract":[{"text":"Returns a size for an adaptive banner with the specified ","type":"text"},{"type":"codeVoice","code":"width"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/bannersize\/adaptive(width:)","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive(width:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adaptive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","text":"BannerSize"}],"title":"adaptive(width:)","navigatorTitle":[{"text":"adaptiveWithWidth:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"url":"\/documentation\/chartboostmediationsdk\/bannersize","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"abstract":[{"type":"text","text":"The size of a banner ad."}],"kind":"symbol","title":"BannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerSize"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize/adaptive(width:maxHeight:)":{"navigatorTitle":[{"text":"adaptiveWithWidth:maxHeight:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adaptive","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier","text":"BannerSize"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive(width:maxHeight:)","title":"adaptive(width:maxHeight:)","type":"topic","abstract":[{"type":"text","text":"Returns a size for an adaptive banner with the specified "},{"code":"width","type":"codeVoice"},{"type":"text","text":" and "},{"code":"maxHeight","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/chartboostmediationsdk\/bannersize\/adaptive(width:maxheight:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"adaptiveWithWidth:maxHeight:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"adaptiveWithWidth:maxHeight:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","kind":"typeIdentifier","text":"CBMBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"},{"text":" *) ","kind":"text"},{"text":"adaptiveWithWidth:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") "},{"text":"width","kind":"internalParam"},{"kind":"text","text":" "},{"text":"maxHeight:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"maxHeight","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"width","content":[{"inlineContent":[{"text":"The maximum width for the banner.","type":"text"}],"type":"paragraph"}]},{"name":"maxHeight","content":[{"inlineContent":[{"type":"text","text":"The maximum height for the banner."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"A ","type":"text"},{"code":"BannerSize","type":"codeVoice"},{"text":" that can be used to load a banner.","type":"text"}],"type":"paragraph"}]}},{"op":"replace","value":"adaptiveWithWidth:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive(width:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive(width:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adaptiveWithWidth:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title","value":"CBMBannerSize","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments","op":"replace","value":[{"text":"CBMBannerSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/navigatorTitle","value":[{"text":"CBMBannerSize","kind":"identifier"}]},{"value":"adaptiveWithWidth:maxHeight:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive(width:maxHeight:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive(width:maxHeight:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"adaptiveWithWidth:maxHeight:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}