{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adaptive1x2"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","text":"BannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier"}]}]},{"parameters":[{"name":"width","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum width for the banner."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A "},{"code":"BannerSize","type":"codeVoice"},{"text":" that can be used to load a banner.","type":"text"}],"type":"paragraph"}]},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"This is only a maximum banner size. Depending on how your waterfall is configured, smaller or different aspect ratio","type":"text"},{"type":"text","text":" "},{"text":"ads may be served.","type":"text"}]}],"style":"note"}],"kind":"content"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive1x2(width:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/adaptive1x2(width:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/adaptive1x2(width:)"]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adaptive1x2"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"width"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"text":"BannerSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"}],"modules":[{"name":"ChartboostMediationSDK"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize(cm)adaptive1x2WithWidth:","title":"adaptive1x2(width:)","navigatorTitle":[{"text":"adaptive1x2WithWidth:","kind":"identifier"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method"},"sections":[],"abstract":[{"text":"Convenience that returns a 1:2 ","type":"text"},{"code":"BannerSize","type":"codeVoice"},{"text":" for the specified ","type":"text"},{"type":"codeVoice","code":"width"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize/adaptive1x2(width:)":{"url":"\/documentation\/chartboostmediationsdk\/bannersize\/adaptive1x2(width:)","title":"adaptive1x2(width:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Convenience that returns a 1:2 "},{"type":"codeVoice","code":"BannerSize"},{"text":" for the specified ","type":"text"},{"type":"codeVoice","code":"width"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive1x2(width:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptive1x2"},{"kind":"text","text":"("},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","text":"BannerSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"adaptive1x2WithWidth:","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"url":"\/documentation\/chartboostmediationsdk\/bannersize","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"abstract":[{"type":"text","text":"The size of a banner ad."}],"kind":"symbol","title":"BannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerSize"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"adaptive1x2WithWidth:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"adaptive1x2WithWidth:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","text":"CBMBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"adaptive1x2WithWidth:"},{"kind":"text","text":"("},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"width","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The maximum width for the banner."}],"type":"paragraph"}],"name":"width"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"code":"BannerSize","type":"codeVoice"},{"type":"text","text":" that can be used to load a banner."}]}],"kind":"content"}},{"op":"replace","value":"adaptive1x2WithWidth:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive1x2(width:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive1x2(width:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"adaptive1x2WithWidth:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title","value":"CBMBannerSize","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments","value":[{"text":"CBMBannerSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/navigatorTitle","op":"replace","value":[{"text":"CBMBannerSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}