{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adaptive10x1","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","kind":"typeIdentifier","text":"BannerSize"}],"languages":["swift"]}]},{"parameters":[{"name":"width","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum width for the banner."}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"code":"BannerSize","type":"codeVoice"},{"type":"text","text":" that can be used to load a banner."}]}],"kind":"content"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is only a maximum banner size. Depending on how your waterfall is configured, smaller or different aspect ratio"},{"text":" ","type":"text"},{"type":"text","text":"ads may be served."}]}],"type":"aside","name":"Note"}]}],"metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize(cm)adaptive10x1WithWidth:","roleHeading":"Type Method","title":"adaptive10x1(width:)","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adaptive10x1","kind":"identifier"},{"kind":"text","text":"("},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"text":"BannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"adaptive10x1WithWidth:","kind":"identifier"}],"modules":[{"name":"ChartboostMediationSDK"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Convenience that returns a 10:1 "},{"type":"codeVoice","code":"BannerSize"},{"type":"text","text":" for the specified "},{"code":"width","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/adaptive10x1(width:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/adaptive10x1(width:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive10x1(width:)"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize/adaptive10x1(width:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive10x1(width:)","kind":"symbol","title":"adaptive10x1(width:)","url":"\/documentation\/chartboostmediationsdk\/bannersize\/adaptive10x1(width:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adaptive10x1","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","text":"BannerSize"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"adaptive10x1WithWidth:","kind":"identifier"}],"abstract":[{"text":"Convenience that returns a 10:1 ","type":"text"},{"type":"codeVoice","code":"BannerSize"},{"type":"text","text":" for the specified "},{"type":"codeVoice","code":"width"},{"text":".","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BannerSize","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannersize","type":"topic","abstract":[{"type":"text","text":"The size of a banner ad."}],"role":"symbol","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"title":"BannerSize","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"adaptive10x1WithWidth:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"adaptive10x1WithWidth:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","text":"CBMBannerSize","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"adaptive10x1WithWidth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"width","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive10x1(width:)\/title","op":"replace","value":"adaptive10x1WithWidth:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive10x1(width:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adaptive10x1WithWidth:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title","value":"CBMBannerSize"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMBannerSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}