{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive6x1(width:)"},"metadata":{"modules":[{"name":"ChartboostMediationSDK"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"adaptive6x1WithWidth:","kind":"identifier"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptive6x1"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier","text":"BannerSize"}],"title":"adaptive6x1(width:)","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize(cm)adaptive6x1WithWidth:"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Convenience that returns a 6:1 "},{"code":"BannerSize","type":"codeVoice"},{"text":" for the specified ","type":"text"},{"type":"codeVoice","code":"width"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/adaptive6x1(width:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/adaptive6x1(width:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptive6x1"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","text":"BannerSize"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"width","content":[{"inlineContent":[{"type":"text","text":"The maximum width for the banner."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A "},{"code":"BannerSize","type":"codeVoice"},{"type":"text","text":" that can be used to load a banner."}],"type":"paragraph"}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is only a maximum banner size. Depending on how your waterfall is configured, smaller or different aspect ratio"},{"text":" ","type":"text"},{"type":"text","text":"ads may be served."}]}],"type":"aside"}],"kind":"content"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize/adaptive6x1(width:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"adaptive6x1WithWidth:"}],"type":"topic","title":"adaptive6x1(width:)","url":"\/documentation\/chartboostmediationsdk\/bannersize\/adaptive6x1(width:)","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive6x1(width:)","role":"symbol","abstract":[{"type":"text","text":"Convenience that returns a 6:1 "},{"code":"BannerSize","type":"codeVoice"},{"type":"text","text":" for the specified "},{"code":"width","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adaptive6x1","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","text":"BannerSize"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"url":"\/documentation\/chartboostmediationsdk\/bannersize","type":"topic","title":"BannerSize","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerSize","kind":"identifier"}],"abstract":[{"type":"text","text":"The size of a banner ad."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"kind":"symbol","type":"topic","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"adaptive6x1WithWidth:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"adaptive6x1WithWidth:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","kind":"typeIdentifier","text":"CBMBannerSize"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"adaptive6x1WithWidth:"},{"kind":"text","text":"("},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"width"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive6x1(width:)\/title","value":"adaptive6x1WithWidth:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"adaptive6x1WithWidth:"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive6x1(width:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title","value":"CBMBannerSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments","value":[{"text":"CBMBannerSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}