{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adaptive1x4"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"BannerSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize(cm)adaptive1x4WithWidth:","modules":[{"name":"ChartboostMediationSDK"}],"symbolKind":"method","title":"adaptive1x4(width:)","roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"text":"adaptive1x4WithWidth:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adaptive1x4"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","text":"BannerSize"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The maximum width for the banner.","type":"text"}]}],"name":"width"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"BannerSize"},{"type":"text","text":" that can be used to load a banner."}]}]},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"style":"note","type":"aside","content":[{"inlineContent":[{"text":"This is only a maximum banner size. Depending on how your waterfall is configured, smaller or different aspect ratio","type":"text"},{"text":" ","type":"text"},{"text":"ads may be served.","type":"text"}],"type":"paragraph"}],"name":"Note"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/adaptive1x4(width:)"]},{"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/adaptive1x4(width:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive1x4(width:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Convenience that returns a 1:4 "},{"type":"codeVoice","code":"BannerSize"},{"type":"text","text":" for the specified "},{"type":"codeVoice","code":"width"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize/adaptive1x4(width:)":{"navigatorTitle":[{"text":"adaptive1x4WithWidth:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adaptive1x4","kind":"identifier"},{"kind":"text","text":"("},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","kind":"typeIdentifier","text":"BannerSize"}],"url":"\/documentation\/chartboostmediationsdk\/bannersize\/adaptive1x4(width:)","kind":"symbol","abstract":[{"text":"Convenience that returns a 1:4 ","type":"text"},{"type":"codeVoice","code":"BannerSize"},{"type":"text","text":" for the specified "},{"code":"width","type":"codeVoice"},{"text":".","type":"text"}],"title":"adaptive1x4(width:)","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive1x4(width:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"url":"\/documentation\/chartboostmediationsdk\/bannersize","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"abstract":[{"type":"text","text":"The size of a banner ad."}],"kind":"symbol","title":"BannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerSize"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"adaptive1x4WithWidth:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adaptive1x4WithWidth:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","text":"CBMBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"},{"kind":"text","text":" *) "},{"text":"adaptive1x4WithWidth:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"width","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"width","content":[{"inlineContent":[{"text":"The maximum width for the banner.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","value":{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"BannerSize"},{"type":"text","text":" that can be used to load a banner."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"value":"adaptive1x4WithWidth:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive1x4(width:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive1x4(width:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"adaptive1x4WithWidth:","kind":"identifier"}],"op":"replace"},{"value":"CBMBannerSize","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments","value":[{"text":"CBMBannerSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/navigatorTitle","value":[{"kind":"identifier","text":"CBMBannerSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}