{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaderboard"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","kind":"typeIdentifier","text":"BannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/leaderboard"},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/leaderboard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/bannersize\/leaderboard"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"leaderboard","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize(cpy)leaderboard","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"leaderboard","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BannerSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"leaderboard"}],"roleHeading":"Type Property","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize"]]},"abstract":[{"text":"A size object for a fixed size 728x90 leaderboard banner.","type":"text"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize":{"url":"\/documentation\/chartboostmediationsdk\/bannersize","navigatorTitle":[{"text":"BannerSize","kind":"identifier"}],"abstract":[{"type":"text","text":"The size of a banner ad."}],"kind":"symbol","title":"BannerSize","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerSize"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize/leaderboard":{"title":"leaderboard","role":"symbol","abstract":[{"text":"A size object for a fixed size 728x90 leaderboard banner.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leaderboard","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize","text":"BannerSize"}],"url":"\/documentation\/chartboostmediationsdk\/bannersize\/leaderboard","type":"topic","kind":"symbol","navigatorTitle":[{"text":"leaderboard","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/leaderboard"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"leaderboard","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"leaderboard","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize","text":"CBMBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"},{"kind":"text","text":" * "},{"text":"leaderboard","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"CBMBannerSize","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CBMBannerSize"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize\/navigatorTitle","value":[{"text":"CBMBannerSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1leaderboard\/title","value":"leaderboard"},{"value":[{"text":"leaderboard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1leaderboard\/fragments"}]}]}