{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/cbmfullscreenad\/delegate"]},{"paths":["\/documentation\/chartboostmediationsdk\/cbmfullscreenad\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"]]},"metadata":{"role":"symbol","title":"delegate","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd(py)delegate","roleHeading":"Instance Property","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenAdDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The delegate to receive ad callbacks.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMFullscreenAd\/delegate","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","text":"FullscreenAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","navigatorTitle":[{"text":"FullscreenAd","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAd"}],"abstract":[{"text":"A Chartboost Mediation fullscreen ad ready to be shown.","type":"text"}],"type":"topic","title":"FullscreenAd"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdDelegate"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdDelegate"}],"abstract":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"},{"text":" delegate that receives ad callbacks.","type":"text"}],"type":"topic","title":"FullscreenAdDelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CBMFullscreenAd/delegate":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"abstract":[{"text":"The delegate to receive ad callbacks.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FullscreenAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/cbmfullscreenad\/delegate","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMFullscreenAd\/delegate","type":"topic","title":"delegate","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"delegate","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":") ","kind":"text"},{"text":"id<CBMFullscreenAdDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"CBMFullscreenAd","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAd"}]},{"value":"CBMFullscreenAdDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdDelegate"}],"op":"replace"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMFullscreenAd~1delegate\/title"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMFullscreenAd~1delegate\/fragments"}]}]}