{"metadata":{"role":"symbol","title":"loadID","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd(py)loadID","roleHeading":"Instance Property","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"loadID","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"loadID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/cbmfullscreenad\/loadid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/cbmfullscreenad\/loadid"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMFullscreenAd\/loadID"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"]]},"abstract":[{"text":"A unique identifier for the load request.","type":"text"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","navigatorTitle":[{"text":"FullscreenAd","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAd"}],"abstract":[{"text":"A Chartboost Mediation fullscreen ad ready to be shown.","type":"text"}],"type":"topic","title":"FullscreenAd"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CBMFullscreenAd/loadID":{"title":"loadID","abstract":[{"text":"A unique identifier for the load request.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMFullscreenAd\/loadID","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/cbmfullscreenad\/loadid","navigatorTitle":[{"text":"loadID","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"loadID","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"loadID","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"loadID"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title","value":"CBMFullscreenAd","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMFullscreenAd~1loadID\/title","op":"replace","value":"loadID"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMFullscreenAd~1loadID\/fragments","value":[{"kind":"identifier","text":"loadID"}],"op":"replace"}]}]}