{"kind":"symbol","metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd(py)request","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"request","kind":"identifier"}],"modules":[{"name":"ChartboostMediationSDK"}],"role":"symbol","title":"request","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenAdLoadRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadRequest"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/cbmfullscreenad\/request"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/cbmfullscreenad\/request"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMFullscreenAd\/request"},"abstract":[{"text":"The request that resulted in this ad getting loaded.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"request"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenAdLoadRequest","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadRequest"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","navigatorTitle":[{"text":"FullscreenAd","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAd"}],"abstract":[{"text":"A Chartboost Mediation fullscreen ad ready to be shown.","type":"text"}],"type":"topic","title":"FullscreenAd"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CBMFullscreenAd/request":{"kind":"symbol","navigatorTitle":[{"text":"request","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"request"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadRequest","text":"FullscreenAdLoadRequest","kind":"typeIdentifier"}],"url":"\/documentation\/chartboostmediationsdk\/cbmfullscreenad\/request","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMFullscreenAd\/request","abstract":[{"text":"The request that resulted in this ad getting loaded.","type":"text"}],"title":"request"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadRequest":{"kind":"symbol","navigatorTitle":[{"text":"FullscreenAdLoadRequest","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdLoadRequest"}],"url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadrequest","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","abstract":[{"text":"A request used to load a Chartboost Mediation fullscreen ad.","type":"text"}],"title":"FullscreenAdLoadRequest"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"request","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"request","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CBMFullscreenAdLoadRequest","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadRequest"},{"text":" * ","kind":"text"},{"text":"request","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title","value":"CBMFullscreenAd","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","op":"replace","value":[{"text":"CBMFullscreenAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMFullscreenAd~1request\/title","value":"request"},{"value":[{"text":"request","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMFullscreenAd~1request\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/title","value":"CBMFullscreenAdLoadRequest"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdLoadRequest"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}