{"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMAdShowResult\/metrics","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult"]]},"sections":[],"metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMAdShowResult(py)metrics","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"metrics","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"modules":[{"name":"ChartboostMediationSDK"}],"title":"metrics","navigatorTitle":[{"kind":"identifier","text":"metrics"}],"symbolKind":"property","roleHeading":"Instance Property"},"abstract":[{"text":"Metrics data about the show operation.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/chartboostmediationsdk\/cbmadshowresult\/metrics"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/cbmadshowresult\/metrics"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"metrics"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}]}]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CBMAdShowResult/metrics":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"metrics"}],"role":"symbol","title":"metrics","url":"\/documentation\/chartboostmediationsdk\/cbmadshowresult\/metrics","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMAdShowResult\/metrics","kind":"symbol","abstract":[{"text":"Metrics data about the show operation.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"metrics"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/AdShowResult":{"type":"topic","navigatorTitle":[{"text":"AdShowResult","kind":"identifier"}],"role":"symbol","title":"AdShowResult","url":"\/documentation\/chartboostmediationsdk\/adshowresult","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/AdShowResult","kind":"symbol","abstract":[{"type":"text","text":"A result returned by Chartboost Mediation at the end of an ad show operation."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AdShowResult","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"metrics","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"metrics"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"metrics"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"metrics","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMAdShowResult~1metrics\/title"},{"op":"replace","value":[{"text":"metrics","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1CBMAdShowResult~1metrics\/fragments"},{"value":"CBMAdShowResult","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/title"},{"value":[{"text":"CBMAdShowResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1AdShowResult\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}