{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate","kind":"typeIdentifier","text":"FullscreenAdDelegate"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd(py)delegate","title":"delegate"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenad\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenad\/delegate"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate","kind":"typeIdentifier","text":"FullscreenAdDelegate","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The delegate to receive ad callbacks."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/delegate"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"url":"\/documentation\/chartboostmediationsdk\/fullscreenad","navigatorTitle":[{"kind":"identifier","text":"FullscreenAd"}],"type":"topic","title":"FullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","abstract":[{"type":"text","text":"A Chartboost Mediation fullscreen ad ready to be shown."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FullscreenAd","kind":"identifier"}]},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","titleInlineContent":[{"text":"Chartboost Developers","type":"text"}],"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","title":"Chartboost Developers","type":"link"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/delegate":{"role":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/delegate","title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","abstract":[{"text":"The delegate to receive ad callbacks.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate","text":"FullscreenAdDelegate"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/delegate","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenAdDelegate"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdDelegate","url":"\/documentation\/chartboostmediationsdk\/fullscreenaddelegate","navigatorTitle":[{"text":"FullscreenAdDelegate","kind":"identifier"}],"title":"FullscreenAdDelegate","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A "},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","isActive":true,"type":"reference"},{"text":" delegate that receives ad callbacks.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"id<CBMFullscreenAdDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)CBMFullscreenAdDelegate"},{"kind":"text","text":" * "},{"text":"delegate","kind":"identifier"}]}]}},{"value":"CBMFullscreenAd","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1delegate\/title","value":"delegate"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1delegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/title","value":"CBMFullscreenAdDelegate","op":"replace"},{"value":[{"text":"CBMFullscreenAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdDelegate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}