{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/load(with:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"load","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"request"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenAdLoadRequest","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadRequest","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"FullscreenAdLoadResult","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadResult"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"name":"request","content":[{"inlineContent":[{"text":"A request containing the information used to load the ad.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure executed when the load operation is done."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Chartboost Mediation may return the same ad from a previous successful load if it was never shown nor invalidated"},{"type":"text","text":" "},{"type":"text","text":"before it got discarded."}]}]}],"sections":[],"abstract":[{"text":"Loads a Chartboost Mediation fullscreen ad using the information provided in the request.","type":"text"}],"metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd(cm)loadWith:completion:","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadRequest","kind":"typeIdentifier","text":"FullscreenAdLoadRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"FullscreenAdLoadResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadResult"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"roleHeading":"Type Method","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"text":"loadWith:completion:","kind":"identifier"}],"title":"load(with:completion:)","symbolKind":"method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"]]},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenad\/load(with:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenad\/load(with:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/load(with:completion:)":{"url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/load(with:completion:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadRequest","kind":"typeIdentifier","text":"FullscreenAdLoadRequest"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"FullscreenAdLoadResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadResult"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/load(with:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadWith:completion:"}],"abstract":[{"text":"Loads a Chartboost Mediation fullscreen ad using the information provided in the request.","type":"text"}],"title":"load(with:completion:)","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"url":"\/documentation\/chartboostmediationsdk\/fullscreenad","navigatorTitle":[{"kind":"identifier","text":"FullscreenAd"}],"type":"topic","title":"FullscreenAd","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd","abstract":[{"type":"text","text":"A Chartboost Mediation fullscreen ad ready to be shown."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FullscreenAd","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadRequest":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenAdLoadRequest"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadrequest","navigatorTitle":[{"text":"FullscreenAdLoadRequest","kind":"identifier"}],"title":"FullscreenAdLoadRequest","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"A request used to load a Chartboost Mediation fullscreen ad.","type":"text"}]},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAdLoadResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenAdLoadResult","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadResult","url":"\/documentation\/chartboostmediationsdk\/fullscreenadloadresult","navigatorTitle":[{"kind":"identifier","text":"FullscreenAdLoadResult"}],"title":"FullscreenAdLoadResult","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"A result returned by Chartboost Mediation at the end of a fullscreen ad load operation.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"loadWith:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"loadWith:completion:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"loadWith:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CBMFullscreenAdLoadRequest","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadRequest","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAdLoadRequest","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"request"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(CBMFullscreenAdLoadResult *)","preciseIdentifier":"c:BFv(#*$@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAdLoadResult)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1load(with:completion:)\/title","value":"loadWith:completion:"},{"value":[{"kind":"text","text":"+ "},{"text":"loadWith:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1load(with:completion:)\/fragments"},{"value":"CBMFullscreenAd","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","value":[{"text":"CBMFullscreenAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/title","value":"CBMFullscreenAdLoadRequest","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadRequest\/fragments","value":[{"kind":"identifier","text":"CBMFullscreenAdLoadRequest"}]},{"op":"replace","value":"CBMFullscreenAdLoadResult","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/title"},{"value":[{"text":"CBMFullscreenAdLoadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAdLoadResult\/fragments"}]}]}