{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/loadID"},"sections":[],"abstract":[{"text":"A unique identifier for the load request.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/fullscreenad\/loadid"]},{"paths":["\/documentation\/chartboostmediationsdk\/fullscreenad\/loadid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"loadID","kind":"identifier"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMFullscreenAd(py)loadID","roleHeading":"Instance Property","modules":[{"name":"ChartboostMediationSDK"}],"symbolKind":"property","title":"loadID","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadID"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"loadID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenAd","kind":"identifier"}],"title":"FullscreenAd","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/fullscreenad","abstract":[{"text":"A Chartboost Mediation fullscreen ad ready to be shown.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"FullscreenAd","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"kind":"symbol","type":"topic","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/FullscreenAd/loadID":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadID"}],"type":"topic","title":"loadID","url":"\/documentation\/chartboostmediationsdk\/fullscreenad\/loadid","abstract":[{"text":"A unique identifier for the load request.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/FullscreenAd\/loadID","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"loadID","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"loadID"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"loadID"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/title","value":"CBMFullscreenAd"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd\/fragments","value":[{"text":"CBMFullscreenAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1loadID\/title","value":"loadID"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1FullscreenAd~1loadID\/fragments","value":[{"kind":"identifier","text":"loadID"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}