{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"coreModuleID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/coreModuleID","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation"]]},"metadata":{"roleHeading":"Type Property","modules":[{"name":"ChartboostMediationSDK"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coreModuleID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","title":"coreModuleID","externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediation(cpy)coreModuleID","navigatorTitle":[{"text":"coreModuleID","kind":"identifier"}]},"sections":[],"abstract":[{"text":"The module ID of the ","type":"text"},{"code":"ChartboostCoreSDK","type":"codeVoice"},{"type":"text","text":" module that represents "},{"type":"codeVoice","code":"ChartboostMediationSDK"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"ChartboostCoreSDK.initializeSDK()"},{"text":" initializes ","type":"text"},{"code":"ChartboostMediationSDK","type":"codeVoice"},{"type":"text","text":" by default. In order to skip"},{"text":" ","type":"text"},{"type":"codeVoice","code":"ChartboostMediationSDK"},{"text":" initialization, provide this module ID to ","type":"text"},{"code":"ChartboostCoreSDK.SDKConfiguration.skippedModuleIDs","type":"codeVoice"},{"text":" ","type":"text"},{"text":"when calling ","type":"text"},{"code":"ChartboostCoreSDK.initializeSDK()","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/coremoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/coremoduleid"]}],"references":{"https://developers.chartboost.com/docs/mediation-ios-get-started":{"titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"title":"Chartboost Developers","type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation":{"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK that provides some configuration options."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","url":"\/documentation\/chartboostmediationsdk\/chartboostmediation","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChartboostMediation"}],"role":"symbol","title":"ChartboostMediation","navigatorTitle":[{"text":"ChartboostMediation","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation/coreModuleID":{"abstract":[{"type":"text","text":"The module ID of the "},{"type":"codeVoice","code":"ChartboostCoreSDK"},{"type":"text","text":" module that represents "},{"type":"codeVoice","code":"ChartboostMediationSDK"},{"type":"text","text":"."},{"type":"text","text":" "},{"code":"ChartboostCoreSDK.initializeSDK()","type":"codeVoice"},{"text":" initializes ","type":"text"},{"code":"ChartboostMediationSDK","type":"codeVoice"},{"text":" by default. In order to skip","type":"text"},{"type":"text","text":" "},{"code":"ChartboostMediationSDK","type":"codeVoice"},{"type":"text","text":" initialization, provide this module ID to "},{"type":"codeVoice","code":"ChartboostCoreSDK.SDKConfiguration.skippedModuleIDs"},{"type":"text","text":" "},{"type":"text","text":"when calling "},{"code":"ChartboostCoreSDK.initializeSDK()","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/coreModuleID","url":"\/documentation\/chartboostmediationsdk\/chartboostmediation\/coremoduleid","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"coreModuleID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","title":"coreModuleID","navigatorTitle":[{"text":"coreModuleID","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"value":"coreModuleID","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"coreModuleID","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"coreModuleID","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/title","value":"ChartboostMediation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/fragments","value":[{"kind":"identifier","text":"ChartboostMediation"}]},{"value":"coreModuleID","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1coreModuleID\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1coreModuleID\/fragments","value":[{"text":"coreModuleID","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}