{"metadata":{"roleHeading":"Type Property","title":"discardOversizedAds","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediation(cpy)discardOversizedAds","modules":[{"name":"ChartboostMediationSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discardOversizedAds"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"text":"discardOversizedAds","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Boolean value indicating that ads returned from adapters that are larger than the requested size should be discarded.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/discardOversizedAds","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discardOversizedAds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"An ad is defined as too large if either the width or the height of the resulting ad is larger than the requested ad size","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(unless the height of the requested ad size is 0, as is the case when using"},{"text":" ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive(width:)","type":"reference","isActive":true},{"type":"text","text":"). In this case,"},{"type":"text","text":" "},{"text":"a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/loadFailureAdTooLarge"},{"text":" error will be returned.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This currently only applies to banners. Defaults to "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/discardoversizedads"]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/discardoversizedads"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerSize/adaptive(width:)":{"abstract":[{"type":"text","text":"Returns a size for an adaptive banner with the specified "},{"type":"codeVoice","code":"width"},{"text":".","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerSize\/adaptive(width:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adaptive"},{"kind":"text","text":"("},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMBannerSize"}],"navigatorTitle":[{"text":"adaptiveWithWidth:","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannersize\/adaptive(width:)","title":"adaptive(width:)","type":"topic","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation":{"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK that provides some configuration options."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","url":"\/documentation\/chartboostmediationsdk\/chartboostmediation","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChartboostMediation"}],"role":"symbol","title":"ChartboostMediation","navigatorTitle":[{"text":"ChartboostMediation","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation/discardOversizedAds":{"role":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediation\/discardoversizedads","title":"discardOversizedAds","navigatorTitle":[{"text":"discardOversizedAds","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Boolean value indicating that ads returned from adapters that are larger than the requested size should be discarded."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"discardOversizedAds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/discardOversizedAds"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","title":"Chartboost Developers"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code/loadFailureAdTooLarge":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadFailureAdTooLarge"}],"kind":"symbol","title":"ChartboostMediationError.Code.loadFailureAdTooLarge","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code\/loadfailureadtoolarge","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code\/loadFailureAdTooLarge","abstract":[{"type":"text","text":"The returned ad was larger than the requested size."}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"discardOversizedAds","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"discardOversizedAds"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"discardOversizedAds","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive(width:)\/title","value":"adaptiveWithWidth:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerSize~1adaptive(width:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adaptiveWithWidth:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/title","op":"replace","value":"ChartboostMediation"},{"value":[{"kind":"identifier","text":"ChartboostMediation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/fragments"},{"op":"replace","value":"discardOversizedAds","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1discardOversizedAds\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1discardOversizedAds\/fragments","value":[{"kind":"identifier","text":"discardOversizedAds"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}