{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation"]]},"metadata":{"externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediation(cpy)initializedAdapterInfo","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializedAdapterInfo","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMPartnerAdapterInfo","text":"PartnerAdapterInfo","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"initializedAdapterInfo","kind":"identifier"}],"title":"initializedAdapterInfo","role":"symbol","symbolKind":"property","modules":[{"name":"ChartboostMediationSDK"}],"roleHeading":"Type Property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"An array of all initialized adapters, or an empty array if the SDK is not initialized."}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializedAdapterInfo","kind":"identifier"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo","text":"PartnerAdapterInfo","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMPartnerAdapterInfo","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/initializedadapterinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/initializedadapterinfo"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/initializedAdapterInfo"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterInfo":{"title":"PartnerAdapterInfo","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo","abstract":[{"text":"General info about a partner adapter.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PartnerAdapterInfo"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/partneradapterinfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerAdapterInfo"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation/initializedAdapterInfo":{"title":"initializedAdapterInfo","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/initializedAdapterInfo","abstract":[{"text":"An array of all initialized adapters, or an empty array if the SDK is not initialized.","type":"text"}],"navigatorTitle":[{"text":"initializedAdapterInfo","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediation\/initializedadapterinfo","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initializedAdapterInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PartnerAdapterInfo","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMPartnerAdapterInfo"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation":{"title":"ChartboostMediation","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","abstract":[{"text":"The main interface to the Chartboost Mediation SDK that provides some configuration options.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ChartboostMediation"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChartboostMediation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initializedAdapterInfo","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"initializedAdapterInfo","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<CBMPartnerAdapterInfo *>"},{"kind":"text","text":" * "},{"text":"initializedAdapterInfo","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/title","value":"CBMPartnerAdapterInfo"},{"value":[{"kind":"identifier","text":"CBMPartnerAdapterInfo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1initializedAdapterInfo\/title","op":"replace","value":"initializedAdapterInfo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1initializedAdapterInfo\/fragments","value":[{"kind":"identifier","text":"initializedAdapterInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/title","value":"ChartboostMediation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/fragments","value":[{"kind":"identifier","text":"ChartboostMediation"}]}]}]}