{"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isTestModeEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isTestModeEnabled","roleHeading":"Type Property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediation(cpy)isTestModeEnabled","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"isTestModeEnabled"}],"symbolKind":"property"},"abstract":[{"type":"text","text":"A Boolean flag for setting test mode in this SDK."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/isTestModeEnabled"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/istestmodeenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/istestmodeenabled"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isTestModeEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"style":"warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Do not enable test mode in production builds."}]}],"name":"Warning"}],"kind":"content"}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChartboostMediation","kind":"identifier"}],"abstract":[{"text":"The main interface to the Chartboost Mediation SDK that provides some configuration options.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediation"}],"type":"topic","title":"ChartboostMediation"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation/isTestModeEnabled":{"type":"topic","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediation\/istestmodeenabled","abstract":[{"text":"A Boolean flag for setting test mode in this SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isTestModeEnabled"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/isTestModeEnabled","title":"isTestModeEnabled","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isTestModeEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"isTestModeEnabled","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isTestModeEnabled","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"isTestModeEnabled","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/title","op":"replace","value":"ChartboostMediation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/fragments","value":[{"kind":"identifier","text":"ChartboostMediation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/navigatorTitle","value":[{"text":"ChartboostMediation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1isTestModeEnabled\/title","op":"replace","value":"isTestModeEnabled"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1isTestModeEnabled\/fragments","value":[{"kind":"identifier","text":"isTestModeEnabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}