{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","text":"LogLevel"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This property can be called at any time, however it ideally should be called before initializing the SDK."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":".info"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"property","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","kind":"typeIdentifier","text":"LogLevel"}],"title":"logLevel","navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"role":"symbol","modules":[{"name":"ChartboostMediationSDK"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediation(cpy)logLevel"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Set the logging level."}],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/loglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/loglevel"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/logLevel","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation":{"title":"ChartboostMediation","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","abstract":[{"text":"The main interface to the Chartboost Mediation SDK that provides some configuration options.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ChartboostMediation"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChartboostMediation","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation/logLevel":{"title":"logLevel","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/logLevel","abstract":[{"type":"text","text":"Set the logging level."}],"navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediation\/loglevel","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"logLevel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"logLevel","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"logLevel"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","text":"CBCLogLevel"},{"kind":"text","text":" "},{"text":"logLevel","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/title","value":"ChartboostMediation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/fragments","value":[{"kind":"identifier","text":"ChartboostMediation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1logLevel\/title","value":"logLevel"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1logLevel\/fragments","op":"replace","value":[{"text":"logLevel","kind":"identifier"}]}]}]}