{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/setpreinitializationconfiguration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediation\/setpreinitializationconfiguration(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/setPreinitializationConfiguration(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set the SDK preinitialization configuration."},{"type":"text","text":" "},{"type":"text","text":"This method should be called before any attempt to initialize the SDK, otherwise the provided configuration is discarded,"},{"text":" ","type":"text"},{"text":"and a ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","isActive":true},{"type":"text","text":" is returned."}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setPreinitializationConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMPreinitializationConfiguration","text":"PreinitializationConfiguration"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMError","kind":"typeIdentifier","text":"ChartboostMediationError"},{"text":"?","kind":"text"}],"roleHeading":"Type Method","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"text":"setPreinitializationConfiguration:","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediation(cm)setPreinitializationConfiguration:","title":"setPreinitializationConfiguration(_:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPreinitializationConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"configuration","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PreinitializationConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMPreinitializationConfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMError","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","text":"ChartboostMediationError","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation/setPreinitializationConfiguration(_:)":{"role":"symbol","title":"setPreinitializationConfiguration(_:)","navigatorTitle":[{"text":"setPreinitializationConfiguration:","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Set the SDK preinitialization configuration.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method should be called before any attempt to initialize the SDK, otherwise the provided configuration is discarded,"},{"type":"text","text":" "},{"text":"and a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","type":"reference"},{"type":"text","text":" is returned."}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediation\/setpreinitializationconfiguration(_:)","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation\/setPreinitializationConfiguration(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPreinitializationConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMPreinitializationConfiguration","text":"PreinitializationConfiguration","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMError","text":"ChartboostMediationError","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PreinitializationConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PreinitializationConfiguration"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration","title":"PreinitializationConfiguration","type":"topic","abstract":[{"text":"Configuration for Chartboost Mediation preinitialization.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"PreinitializationConfiguration","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/preinitializationconfiguration"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChartboostMediation","kind":"identifier"}],"abstract":[{"text":"The main interface to the Chartboost Mediation SDK that provides some configuration options.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediation"}],"type":"topic","title":"ChartboostMediation"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError":{"navigatorTitle":[{"text":"ChartboostMediationError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChartboostMediationError","kind":"identifier"}],"abstract":[{"text":"Error type passed by the Chartboost Mediation SDK in its public delegate methods to provide context relative to the failure of a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"certain operation."}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror","title":"ChartboostMediationError","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"setPreinitializationConfiguration:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setPreinitializationConfiguration:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"CBMError","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMError","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError"},{"text":" *) ","kind":"text"},{"text":"setPreinitializationConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CBMPreinitializationConfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PreinitializationConfiguration","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)CBMPreinitializationConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1setPreinitializationConfiguration(_:)\/title","value":"setPreinitializationConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation~1setPreinitializationConfiguration(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setPreinitializationConfiguration:","kind":"identifier"}]},{"op":"replace","value":"CBMPreinitializationConfiguration","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/fragments","op":"replace","value":[{"text":"CBMPreinitializationConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PreinitializationConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"CBMPreinitializationConfiguration"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/title","op":"replace","value":"ChartboostMediation"},{"value":[{"kind":"identifier","text":"ChartboostMediation"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/fragments","op":"replace"},{"value":[{"text":"ChartboostMediation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediation\/navigatorTitle"},{"op":"replace","value":"CBMError","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/fragments","value":[{"text":"CBMError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/navigatorTitle","value":[{"text":"CBMError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}