{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"skippedPartnerIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK17PartnerIdentifiera","text":"PartnerIdentifier"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/heliuminitializationoptions\/skippedpartneridentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/heliuminitializationoptions\/skippedpartneridentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions\/skippedPartnerIdentifiers","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set of Partner adapters to skip during Helium SDK initialization."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"skippedPartnerIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"PartnerIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK17PartnerIdentifiera"},{"kind":"text","text":">"}],"title":"skippedPartnerIdentifiers","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)HeliumInitializationOptions(py)skippedPartnerIdentifiers","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInitializationOptions":{"role":"symbol","title":"HeliumInitializationOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumInitializationOptions"}],"abstract":[{"type":"text","text":"Options for Chartboost Mediation initialization."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumInitializationOptions"}],"url":"\/documentation\/chartboostmediationsdk\/heliuminitializationoptions"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerIdentifier":{"role":"symbol","title":"PartnerIdentifier","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PartnerIdentifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"String"},{"type":"text","text":" that identifies a partner."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerIdentifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PartnerIdentifier"}],"url":"\/documentation\/chartboostmediationsdk\/partneridentifier"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumInitializationOptions/skippedPartnerIdentifiers":{"role":"symbol","title":"skippedPartnerIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"skippedPartnerIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"PartnerIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK17PartnerIdentifiera"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Set of Partner adapters to skip during Helium SDK initialization."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumInitializationOptions\/skippedPartnerIdentifiers","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/heliuminitializationoptions\/skippedpartneridentifiers"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSSet<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" * "},{"kind":"identifier","text":"skippedPartnerIdentifiers"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}