{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/heliumimpressiondata\/placement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/heliumimpressiondata\/placement"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumImpressionData\/placement","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The placement associated with Impression Level Revenue Data."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"placement","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)HeliumImpressionData(py)placement","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"placement"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumImpressionData"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumImpressionData/placement":{"role":"symbol","title":"placement","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The placement associated with Impression Level Revenue Data."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumImpressionData\/placement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placement"}],"url":"\/documentation\/chartboostmediationsdk\/heliumimpressiondata\/placement"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumImpressionData":{"role":"symbol","title":"HeliumImpressionData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumImpressionData"}],"abstract":[{"type":"text","text":"Impression Level Revenue Data (ILRD) object that will be contained in the "},{"type":"codeVoice","code":"NSNotification.object"},{"type":"text","text":" field for"},{"type":"text","text":" "},{"type":"codeVoice","code":"Notification.Name.heliumDidReceiveILRD"},{"type":"text","text":" notifications."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumImpressionData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumImpressionData"}],"url":"\/documentation\/chartboostmediationsdk\/heliumimpressiondata"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"placement"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"placement"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"placement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumImpressionData~1placement\/title","value":"placement"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumImpressionData~1placement\/fragments","value":[{"kind":"identifier","text":"placement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumImpressionData\/title","value":"HeliumImpressionData"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumImpressionData\/fragments","value":[{"kind":"identifier","text":"HeliumImpressionData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}