{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subsystem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This value is used as the subsystem for "},{"type":"codeVoice","code":"OSLog(subsystem:category:)"},{"type":"text","text":" on iOS 12+."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/logentry\/subsystem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/logentry\/subsystem"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/subsystem","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A subsystem for the log."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subsystem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"subsystem","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationLogEntry(py)subsystem","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"subsystem"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry"]]},"references":{"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogEntry":{"role":"symbol","title":"LogEntry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogEntry"}],"abstract":[{"type":"text","text":"An object containing information about a single log message."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogEntry"}],"url":"\/documentation\/chartboostmediationsdk\/logentry"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogEntry/subsystem":{"role":"symbol","title":"subsystem","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subsystem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"A subsystem for the log."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry\/subsystem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subsystem"}],"url":"\/documentation\/chartboostmediationsdk\/logentry\/subsystem"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"subsystem"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"subsystem"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"subsystem"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1LogEntry\/title","value":"ChartboostMediationLogEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1LogEntry\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationLogEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1LogEntry~1subsystem\/title","value":"subsystem"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1LogEntry~1subsystem\/fragments","value":[{"kind":"identifier","text":"subsystem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}