{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(bannerProviderWithDelegate:andPlacementName:andSize:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumBannerAdDelegate","text":"HeliumBannerAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"placementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andSize"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bannerSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CHBHBannerSize","text":"CHBHBannerSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumBannerView","text":"HeliumBannerView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Delegate to receive banner ad callbacks."}]}]},{"name":"placementName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Banner ad placement from the Chartboost dashboard."}]}]},{"name":"bannerSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Size of the banner to request."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The banner ad provider if successful; otherwise "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" will be returned."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/helium\/bannerprovider(with:andplacementname:andsize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/helium\/bannerprovider(with:andplacementname:andsize:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/bannerProvider(with:andPlacementName:andSize:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Factory method to create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView"},{"type":"text","text":" which will be used to load and show banner ads."}],"kind":"symbol","metadata":{"role":"symbol","title":"bannerProvider(with:andPlacementName:andSize:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumBannerAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumBannerAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBHBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CHBHBannerSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeliumBannerView","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumBannerView"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)Helium(im)bannerProviderWithDelegate:andPlacementName:andSize:","modules":[{"name":"ChartboostMediationSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use ChartboostMediationBannerView for the most comprehensive banner ad experience."}]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerAdDelegate":{"role":"symbol","title":"HeliumBannerAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumBannerAdDelegate"}],"abstract":[{"type":"text","text":"Callbacks for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAd"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumBannerAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/heliumbanneraddelegate"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerAd":{"role":"symbol","title":"HeliumBannerAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumBannerAd"}],"abstract":[{"type":"text","text":"Chartboost Mediation banner ad."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumBannerAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliumbannerad"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium":{"role":"symbol","title":"Helium","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Helium"}],"url":"\/documentation\/chartboostmediationsdk\/helium"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/bannerProvider(with:andPlacementName:andSize:)":{"role":"symbol","title":"bannerProvider(with:andPlacementName:andSize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumBannerAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumBannerAdDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andPlacementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBHBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CHBHBannerSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HeliumBannerView","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumBannerView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Factory method to create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView"},{"type":"text","text":" which will be used to load and show banner ads."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/bannerProvider(with:andPlacementName:andSize:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/chartboostmediationsdk\/helium\/bannerprovider(with:andplacementname:andsize:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerView":{"role":"symbol","title":"HeliumBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumBannerView"}],"abstract":[{"type":"text","text":"Chartboost Mediation banner ad view."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumBannerView"}],"url":"\/documentation\/chartboostmediationsdk\/heliumbannerview"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CHBHBannerSize":{"role":"symbol","title":"CHBHBannerSize","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBHBannerSize"}],"abstract":[{"type":"text","text":"Chartboost Mediation banner size to request."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBHBannerSize"}],"url":"\/documentation\/chartboostmediationsdk\/chbhbannersize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumBannerView","text":"HeliumBannerView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"bannerProviderWithDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<CHBHeliumBannerAdDelegate>","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)CHBHeliumBannerAdDelegate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"andPlacementName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"placementName"},{"kind":"text","text":" "},{"kind":"identifier","text":"andSize:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CHBHBannerSize","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CHBHBannerSize","text":"CHBHBannerSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"bannerSize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}