{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachLogHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogHandler","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationLogHandler","text":"LogHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"name":"handler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A custom class that conforms to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogHandler"},{"type":"text","text":" protocol."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/helium\/detachloghandler(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/helium\/detachloghandler(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/detachLogHandler(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Detatch a custom logger handler to the logging system."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachLogHandler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogHandler","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationLogHandler"},{"kind":"text","text":")"}],"title":"detachLogHandler(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)Helium(im)detachLogHandler:","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/detachLogHandler(_:)":{"role":"symbol","title":"detachLogHandler(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachLogHandler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogHandler","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationLogHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Detatch a custom logger handler to the logging system."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/detachLogHandler(_:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/detachloghandler(_:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium":{"role":"symbol","title":"Helium","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Helium"}],"url":"\/documentation\/chartboostmediationsdk\/helium"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogHandler":{"role":"symbol","title":"LogHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogHandler"}],"abstract":[{"type":"text","text":"The protocol for custom log handlers for the unified logging subsystem."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogHandler"}],"url":"\/documentation\/chartboostmediationsdk\/loghandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"detachLogHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ChartboostMediationLogHandler>","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)ChartboostMediationLogHandler"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}