{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogLevel","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@ChartboostMediationLogLevel","text":"LogLevel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property can be called at any time, however it ideally should be called before"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/start(withAppId:andAppSignature:options:delegate:)"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogLevel\/info"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/helium\/loglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/helium\/loglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/logLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set the logging level."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@ChartboostMediationLogLevel"}],"title":"logLevel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)Helium(py)logLevel","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogLevel/info":{"role":"symbol","title":"LogLevel.info","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"abstract":[{"type":"text","text":"Log helpful, non-essential information."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogLevel\/info","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/loglevel\/info"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogLevel":{"role":"symbol","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[{"type":"text","text":"Log severity levels for the unified logging subsystem."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/chartboostmediationsdk\/loglevel"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/logLevel":{"role":"symbol","title":"logLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@ChartboostMediationLogLevel"}],"abstract":[{"type":"text","text":"Set the logging level."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/logLevel","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/loglevel"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium":{"role":"symbol","title":"Helium","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Helium"}],"url":"\/documentation\/chartboostmediationsdk\/helium"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/start(withAppId:andAppSignature:options:delegate:)":{"role":"symbol","title":"start(withAppId:andAppSignature:options:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andAppSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumInitializationOptions","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)HeliumInitializationOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumSdkDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)HeliumSdkDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Deprecated."},{"type":"text","text":" "},{"type":"text","text":"Initializes the Chartboost Mediation SDK."},{"type":"text","text":" "},{"type":"text","text":"This method must be called before ads can be served."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/start(withAppId:andAppSignature:options:delegate:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/chartboostmediationsdk\/helium\/start(withappid:andappsignature:options:delegate:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogLevel","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@ChartboostMediationLogLevel","text":"ChartboostMediationLogLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}