{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(sharedHelium) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)Helium","text":"Helium"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Shared instance of the Helium SDK."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/helium\/shared()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/helium\/shared()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/shared()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shared instance of the Helium SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Helium","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)Helium"}],"title":"shared()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(cs)Helium(cm)sharedHelium","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium":{"role":"symbol","title":"Helium","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Helium"}],"abstract":[{"type":"text","text":"The main interface to the Chartboost Mediation SDK."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Helium"}],"url":"\/documentation\/chartboostmediationsdk\/helium"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/shared()":{"role":"symbol","title":"shared()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Helium","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)Helium"}],"abstract":[{"type":"text","text":"Shared instance of the Helium SDK."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/shared()","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/shared()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)Helium","text":"Helium"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"sharedHelium"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}