{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAd","text":"ChartboostMediationFullscreenAd"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"ad","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ad that triggered this event."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenaddelegate\/didrecordimpression(ad:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenaddelegate\/didrecordimpression(ad:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAdDelegate\/didRecordImpression(ad:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when Chartboost Mediation records an impression as result of the ad being shown."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationFullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAd"},{"kind":"text","text":")"}],"title":"didRecordImpression(ad:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAdDelegate(im)didRecordImpressionWithAd:","modules":[{"name":"ChartboostMediationSDK"}],"navigatorTitle":[{"kind":"identifier","text":"didRecordImpressionWithAd:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAdDelegate"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAd":{"role":"symbol","title":"ChartboostMediationFullscreenAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"abstract":[{"type":"text","text":"A Chartboost Mediation fullscreen ad ready to be shown."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenad"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAdDelegate/didRecordImpression(ad:)":{"role":"symbol","title":"didRecordImpression(ad:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecordImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChartboostMediationFullscreenAd","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when Chartboost Mediation records an impression as result of the ad being shown."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAdDelegate\/didRecordImpression(ad:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didRecordImpressionWithAd:"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenaddelegate\/didrecordimpression(ad:)"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationFullscreenAdDelegate":{"role":"symbol","title":"ChartboostMediationFullscreenAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostMediationFullscreenAdDelegate"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAd"},{"type":"text","text":" delegate that receives ad callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationFullscreenAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostMediationFullscreenAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationfullscreenaddelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didRecordImpressionWithAd:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRecordImpressionWithAd:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didRecordImpressionWithAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ChartboostMediationFullscreenAd>","preciseIdentifier":"c:Qo@M@ChartboostMediationSDK@objc(pl)ChartboostMediationFullscreenAd"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"ad"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd\/title","value":"ChartboostMediationFullscreenAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAd\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationFullscreenAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAdDelegate~1didRecordImpression(ad:)\/title","value":"didRecordImpressionWithAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAdDelegate~1didRecordImpression(ad:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRecordImpressionWithAd:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAdDelegate\/title","value":"ChartboostMediationFullscreenAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationFullscreenAdDelegate\/fragments","value":[{"kind":"identifier","text":"ChartboostMediationFullscreenAdDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}