{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"chartboostMediationCode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code","preciseIdentifier":"s:22ChartboostMediationSDK0aB5ErrorC4CodeO","text":"Code"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/chartboostmediationcode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/chartboostmediationcode"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/chartboostMediationCode","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","modules":[{"name":"ChartboostMediationSDK"}],"roleHeading":"Instance Property","title":"chartboostMediationCode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"chartboostMediationCode"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chartboostMediationCode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:22ChartboostMediationSDK0aB5ErrorC4CodeO","text":"Code"}],"externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMError(py)chartboostMediationCode"},"abstract":[{"text":"The underlying ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code","type":"reference","isActive":true},{"type":"text","text":" for this error."}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/CBMErrorCode":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMErrorCode","abstract":[{"text":"Chartboost Mediation SDK error codes.","type":"text"}],"fragments":[{"text":"CBMErrorCode","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/cbmerrorcode","title":"CBMErrorCode","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/chartboostMediationCode":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chartboostMediationCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22ChartboostMediationSDK0aB5ErrorC4CodeO","kind":"typeIdentifier","text":"Code"}],"kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/chartboostmediationcode","title":"chartboostMediationCode","navigatorTitle":[{"text":"chartboostMediationCode","kind":"identifier"}],"abstract":[{"type":"text","text":"The underlying "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code","type":"reference"},{"text":" for this error.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/chartboostMediationCode"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError/Code":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Chartboost Mediation SDK error codes."}],"title":"ChartboostMediationError.Code","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror\/code","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError\/Code"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"kind":"symbol","type":"topic","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/ChartboostMediationError":{"navigatorTitle":[{"text":"ChartboostMediationError","kind":"identifier"}],"abstract":[{"text":"Error type passed by the Chartboost Mediation SDK in its public delegate methods to provide context relative to the failure of a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"certain operation."}],"title":"ChartboostMediationError","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/chartboostmediationerror","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChartboostMediationError"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/ChartboostMediationError","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"chartboostMediationCode","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"chartboostMediationCode"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"CBMErrorCode","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/CBMErrorCode","preciseIdentifier":"c:@M@ChartboostMediationSDK@E@CBMErrorCode"},{"text":" ","kind":"text"},{"text":"chartboostMediationCode","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError~1chartboostMediationCode\/title","value":"chartboostMediationCode"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError~1chartboostMediationCode\/fragments","op":"replace","value":[{"text":"chartboostMediationCode","kind":"identifier"}]},{"value":"CBMError","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1ChartboostMediationError\/fragments","value":[{"kind":"identifier","text":"CBMError"}]}]}]}