{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/heliumadapterinfo\/partneridentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/heliumadapterinfo\/partneridentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo\/partnerIdentifier","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The partner’s unique identifier."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"partnerIdentifier","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)HeliumAdapterInfo(py)partnerIdentifier","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumAdapterInfo/partnerIdentifier":{"role":"symbol","title":"partnerIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The partner’s unique identifier."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo\/partnerIdentifier","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/heliumadapterinfo\/partneridentifier"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumAdapterInfo":{"role":"symbol","title":"HeliumAdapterInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumAdapterInfo"}],"abstract":[{"type":"text","text":"General info about a partner adapter."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumAdapterInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumAdapterInfo"}],"url":"\/documentation\/chartboostmediationsdk\/heliumadapterinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"partnerIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}