{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"entry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationLogEntry","text":"LogEntry"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/loghandler\/handle(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/loghandler\/handle(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogHandler\/handle(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called on every handler previously registered with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/attachLogHandler(_:)"},{"type":"text","text":" to handle "},{"type":"codeVoice","code":"entry"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"handle(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogEntry","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationLogEntry"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationLogHandler(im)handle:","required":true,"modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogHandler"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/Helium/attachLogHandler(_:)":{"role":"symbol","title":"attachLogHandler(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachLogHandler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogHandler","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)ChartboostMediationLogHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Attach a custom logger handler to the logging system."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/attachLogHandler(_:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/helium\/attachloghandler(_:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogHandler":{"role":"symbol","title":"LogHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogHandler"}],"abstract":[{"type":"text","text":"The protocol for custom log handlers for the unified logging subsystem."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogHandler"}],"url":"\/documentation\/chartboostmediationsdk\/loghandler"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogEntry":{"role":"symbol","title":"LogEntry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogEntry"}],"abstract":[{"type":"text","text":"An object containing information about a single log message."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogEntry"}],"url":"\/documentation\/chartboostmediationsdk\/logentry"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/LogHandler/handle(_:)":{"role":"symbol","title":"handle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LogEntry","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationLogEntry"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on every handler previously registered with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/Helium\/attachLogHandler(_:)"},{"type":"text","text":" to handle "},{"type":"codeVoice","code":"entry"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogHandler\/handle(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/loghandler\/handle(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"handle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/LogEntry","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(cs)ChartboostMediationLogEntry","text":"ChartboostMediationLogEntry"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"entry"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}