{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearLoadedAd"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/heliumrewardedad\/clearloadedad()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostmediationsdk\/heliumrewardedad\/clearloadedad()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd\/clearLoadedAd()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Clears the loaded ad."}],"kind":"symbol","metadata":{"role":"symbol","title":"clearLoadedAd()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearLoadedAd"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@ChartboostMediationSDK@objc(pl)HeliumRewardedAd(im)clearLoadedAd","required":true,"modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd"]]},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumRewardedAd/clearLoadedAd()":{"role":"symbol","title":"clearLoadedAd()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearLoadedAd"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Clears the loaded ad."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd\/clearLoadedAd()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostmediationsdk\/heliumrewardedad\/clearloadedad()"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumRewardedAd":{"role":"symbol","title":"HeliumRewardedAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumRewardedAd"}],"abstract":[{"type":"text","text":"Chartboost Mediation rewarded ad."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumRewardedAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumRewardedAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliumrewardedad"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearLoadedAd"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}