{"metadata":{"symbolKind":"op","extendedModule":"Swift","modules":[{"name":"ChartboostMediationSDK","relatedModules":["Swift"]}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@ChartboostMediationSDK@E@CBMBannerHorizontalAlignment","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"roleHeading":"Operator","role":"symbol","title":"!=(_:_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/Equatable-Implementations"]]},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/!=(_:_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment":{"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment","type":"topic","title":"BannerHorizontalAlignment","navigatorTitle":[{"text":"BannerHorizontalAlignment","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerHorizontalAlignment","kind":"identifier"}],"abstract":[{"type":"text","text":"The horizontal alignment of an ad within "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","role":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/Equatable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/Equatable-Implementations","url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/equatable-implementations","title":"Equatable Implementations"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/!=(_:_:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/!=(_:_:)","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/!=(_:_:)","title":"!=(_:_:)"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"kind":"symbol","type":"topic","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","role":"collection","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"title":"BannerAdView","type":"topic","kind":"symbol","url":"\/documentation\/chartboostmediationsdk\/banneradview","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","navigatorTitle":[{"kind":"identifier","text":"BannerAdView"}],"abstract":[{"type":"text","text":"A view that can load and display a Chartboost Mediation banner ad."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerAdView"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"CBMBannerHorizontalAlignment","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/fragments","value":[{"kind":"identifier","text":"CBMBannerHorizontalAlignment"}]},{"value":"CBMBannerAdView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title"},{"op":"replace","value":[{"text":"CBMBannerAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}