{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment"]]},"metadata":{"title":"BannerHorizontalAlignment.center","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"center"}],"externalID":"c:@M@ChartboostMediationSDK@E@CBMBannerHorizontalAlignment@CBMBannerHorizontalAlignmentCenter","role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentCenter"}],"modules":[{"name":"ChartboostMediationSDK"}]},"abstract":[{"text":"The ad will be displayed at the center of the view.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/center","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/center"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/center"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerAdView","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","title":"BannerAdView","type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview","navigatorTitle":[{"kind":"identifier","text":"BannerAdView"}],"abstract":[{"text":"A view that can load and display a Chartboost Mediation banner ad.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/center":{"title":"BannerHorizontalAlignment.center","abstract":[{"type":"text","text":"The ad will be displayed at the center of the view."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/center","url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/center","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentCenter"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BannerHorizontalAlignment","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment","type":"topic","abstract":[{"type":"text","text":"The horizontal alignment of an ad within "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerHorizontalAlignment"}],"title":"BannerHorizontalAlignment","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"CBMBannerHorizontalAlignmentCenter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CBMBannerHorizontalAlignmentCenter","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentCenter"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CBMBannerAdView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title"},{"value":[{"text":"CBMBannerAdView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1center\/title","value":"CBMBannerHorizontalAlignmentCenter"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1center\/fragments","value":[{"text":"CBMBannerHorizontalAlignmentCenter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/title","op":"replace","value":"CBMBannerHorizontalAlignment"},{"op":"replace","value":[{"text":"CBMBannerHorizontalAlignment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}