{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/left"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/left"]}],"sections":[],"abstract":[{"text":"The ad will be displayed at the left of the view.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/left","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Case","title":"BannerHorizontalAlignment.left","externalID":"c:@M@ChartboostMediationSDK@E@CBMBannerHorizontalAlignment@CBMBannerHorizontalAlignmentLeft","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentLeft"}],"modules":[{"name":"ChartboostMediationSDK"}],"symbolKind":"case"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment","abstract":[{"text":"The horizontal alignment of an ad within ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView"},{"type":"text","text":"."}],"role":"symbol","title":"BannerHorizontalAlignment","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BannerHorizontalAlignment"}],"kind":"symbol","navigatorTitle":[{"text":"BannerHorizontalAlignment","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","abstract":[{"text":"For more information on the Chartboost Mediation SDK, see ","type":"text"},{"type":"reference","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","title":"ChartboostMediationSDK","url":"\/documentation\/chartboostmediationsdk","type":"topic","kind":"symbol"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","abstract":[{"type":"text","text":"A view that can load and display a Chartboost Mediation banner ad."}],"role":"symbol","title":"BannerAdView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BannerAdView","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BannerAdView","kind":"identifier"}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/left":{"abstract":[{"text":"The ad will be displayed at the left of the view.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentLeft"}],"role":"symbol","url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/left","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/left","kind":"symbol","type":"topic","title":"BannerHorizontalAlignment.left"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"type":"link","title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"CBMBannerHorizontalAlignmentLeft"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"CBMBannerHorizontalAlignmentLeft","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"CBMBannerHorizontalAlignmentLeft","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/title","value":"CBMBannerHorizontalAlignment","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBMBannerHorizontalAlignment"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","op":"replace","value":"CBMBannerAdView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments","value":[{"text":"CBMBannerAdView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1left\/title","value":"CBMBannerHorizontalAlignmentLeft"},{"op":"replace","value":[{"text":"CBMBannerHorizontalAlignmentLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1left\/fragments"}]}]}