{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"ChartboostMediationSDK"}],"title":"BannerHorizontalAlignment.right","role":"symbol","externalID":"c:@M@ChartboostMediationSDK@E@CBMBannerHorizontalAlignment@CBMBannerHorizontalAlignmentRight","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"navigatorTitle":[{"text":"CBMBannerHorizontalAlignmentRight","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case"},"abstract":[{"text":"The ad will be displayed at the right of the view.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/right"]},{"paths":["\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/right"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/right"},"references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerAdView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BannerAdView","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","title":"BannerAdView","type":"topic","url":"\/documentation\/chartboostmediationsdk\/banneradview","navigatorTitle":[{"kind":"identifier","text":"BannerAdView"}],"abstract":[{"text":"A view that can load and display a Chartboost Mediation banner ad.","type":"text"}]},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","url":"\/documentation\/chartboostmediationsdk","type":"topic","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"A programmatic ad monetization platform for mobile games and apps."}],"role":"collection"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BannerHorizontalAlignment","kind":"identifier"}],"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment","type":"topic","abstract":[{"type":"text","text":"The horizontal alignment of an ad within "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerAdView","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BannerHorizontalAlignment"}],"title":"BannerHorizontalAlignment","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/BannerHorizontalAlignment/right":{"abstract":[{"text":"The ad will be displayed at the right of the view.","type":"text"}],"url":"\/documentation\/chartboostmediationsdk\/bannerhorizontalalignment\/right","title":"BannerHorizontalAlignment.right","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/BannerHorizontalAlignment\/right","kind":"symbol","navigatorTitle":[{"text":"CBMBannerHorizontalAlignmentRight","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CBMBannerHorizontalAlignmentRight"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentRight"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentRight"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/title","value":"CBMBannerAdView"},{"value":[{"text":"CBMBannerAdView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerAdView\/fragments"},{"value":"CBMBannerHorizontalAlignment","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/title"},{"op":"replace","value":[{"text":"CBMBannerHorizontalAlignment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment\/fragments"},{"value":"CBMBannerHorizontalAlignmentRight","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1right\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBMBannerHorizontalAlignmentRight"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1BannerHorizontalAlignment~1right\/fragments"}]}]}