{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumBannerAdDelegate","text":"HeliumBannerAdDelegate"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/heliumbannerview\/delegate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView\/delegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumBannerAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumBannerAdDelegate"},{"kind":"text","text":"?"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:22ChartboostMediationSDK16HeliumBannerViewC8delegateAA0dE10AdDelegate_pSgvp","modules":[{"name":"ChartboostMediationSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView"]]},"references":{"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerView":{"role":"symbol","title":"HeliumBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumBannerView"}],"abstract":[{"type":"text","text":"Helium banner ad view."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumBannerView"}],"url":"\/documentation\/chartboostmediationsdk\/heliumbannerview"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HeliumBannerAdDelegate","preciseIdentifier":"c:@M@ChartboostMediationSDK@objc(pl)CHBHeliumBannerAdDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerView\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk\/heliumbannerview\/delegate"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"role":"collection","title":"ChartboostMediationSDK","abstract":[{"type":"text","text":"For more information on the Chartboost Mediation SDK, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostmediationsdk"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerAd":{"role":"symbol","title":"HeliumBannerAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumBannerAd"}],"abstract":[{"type":"text","text":"Helium banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumBannerAd"}],"url":"\/documentation\/chartboostmediationsdk\/heliumbannerad"},"doc://com.chartboost.ChartboostMediationSDK/documentation/ChartboostMediationSDK/HeliumBannerAdDelegate":{"role":"symbol","title":"HeliumBannerAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeliumBannerAdDelegate"}],"abstract":[{"type":"text","text":"Callbacks for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAd"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.chartboost.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/HeliumBannerAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeliumBannerAdDelegate"}],"url":"\/documentation\/chartboostmediationsdk\/heliumbanneraddelegate"},"https://developers.chartboost.com/docs/mediation-ios-get-started":{"title":"Chartboost Developers","titleInlineContent":[{"type":"text","text":"Chartboost Developers"}],"type":"link","identifier":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started","url":"https:\/\/developers.chartboost.com\/docs\/mediation-ios-get-started"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumBannerView\/title","value":"HeliumBannerView"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumBannerView\/fragments","value":[{"kind":"identifier","text":"HeliumBannerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumBannerAd\/title","value":"HeliumBannerAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumBannerAd\/fragments","value":[{"kind":"identifier","text":"HeliumBannerAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumBannerAdDelegate\/title","value":"CHBHeliumBannerAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1HeliumBannerAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBHeliumBannerAdDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}