{"abstract":[{"text":"The version of the partner SDK.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo\/partnerVersion","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/chartboostmediationsdk\/partneradapterinfo\/partnerversion"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostmediationsdk\/partneradapterinfo\/partnerversion"]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ChartboostMediationSDK"}],"title":"partnerVersion","navigatorTitle":[{"text":"partnerVersion","kind":"identifier"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ChartboostMediationSDK@objc(cs)CBMPartnerAdapterInfo(py)partnerVersion","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"partnerVersion","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"partnerVersion","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK":{"url":"\/documentation\/chartboostmediationsdk","role":"collection","abstract":[{"text":"A programmatic ad monetization platform for mobile games and apps.","type":"text"}],"title":"ChartboostMediationSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK","type":"topic"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterInfo":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PartnerAdapterInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"General info about a partner adapter."}],"type":"topic","url":"\/documentation\/chartboostmediationsdk\/partneradapterinfo","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PartnerAdapterInfo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo","title":"PartnerAdapterInfo"},"doc://org.cocoapods.ChartboostMediationSDK/documentation/ChartboostMediationSDK/PartnerAdapterInfo/partnerVersion":{"abstract":[{"type":"text","text":"The version of the partner SDK."}],"url":"\/documentation\/chartboostmediationsdk\/partneradapterinfo\/partnerversion","navigatorTitle":[{"text":"partnerVersion","kind":"identifier"}],"kind":"symbol","title":"partnerVersion","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostMediationSDK\/documentation\/ChartboostMediationSDK\/PartnerAdapterInfo\/partnerVersion","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerVersion"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"partnerVersion"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"partnerVersion","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"partnerVersion"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"CBMPartnerAdapterInfo","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/title"},{"value":[{"text":"CBMPartnerAdapterInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo\/navigatorTitle","op":"replace","value":[{"text":"CBMPartnerAdapterInfo","kind":"identifier"}]},{"value":"partnerVersion","path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo~1partnerVersion\/title","op":"replace"},{"op":"replace","value":[{"text":"partnerVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostMediationSDK~1documentation~1ChartboostMediationSDK~1PartnerAdapterInfo~1partnerVersion\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}